# EDA

### Goal of this notebook:
1. Audit the merged NHANES adults dataset
2. Identify candidate target variables for fatigue / low energy / sleep / depression proxies
3. Build a clinically plausible core feature set
4. Assess missingness, subgroup coverage, and feature usefulness
5. Produce a recommendation for next modeling / MVP steps

## Import & Settings

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path
from IPython.display import display

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 120)

sns.set_theme(style="whitegrid")
RANDOM_STATE = 42

In [7]:
DATA_PATH = Path("../data/processed/nhanes_merged_adults.csv")

df = pd.read_csv(DATA_PATH)

print(f"Shape: {df.shape}")
display(df.head())

Shape: (7437, 371)

C:\Users\Philipp\AppData\Local\Temp\ipykernel_38404\357236.py:3: DtypeWarning: Columns (0: medication_18, 1: medication_19, 2: medication_20, 3: medication_21, 4: medication_22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATA_PATH)

,SEQN,RIAGENDR,RIDAGEYR,RIDRETH3,RIDRETH1,RIDEXPRG,DMDEDUC2,DMDMARTZ,DMDBORN4,INDFMPIR,WTMECPRP,WTINTPRP,SDMVPSU,SDMVSTRA,gender,ethnicity,education,marital_status,pregnancy_status,country_of_birth,calories,protein,carbs,fat,iron,vitamin_b12,vitamin_d,folate,magnesium,zinc,height_cm,weight_kg,bmi,waist_cm,hip_cm,sbp_1,sbp_2,sbp_3,dbp_1,dbp_2,dbp_3,pulse_1,pulse_2,pulse_3,liver_cap_dbm,liver_stiffness_kpa,liver_exam_status,liver_valid_measures,liver_stiffness_iqr_ratio,oral_gum_problem_yesno,oral_decayed_teeth_yesno,oral_hygiene_issue_yesno,any_implant,any_root_caries,any_root_restoration_caries,fasting_hours_part,fasting_minutes_part,fasting_glucose_mg_dl,insulin_uU_ml,total_cholesterol_mg_dl,hdl_cholesterol_mg_dl,triglycerides_mg_dl,ferritin_ng_ml,serum_iron_ug_dl,tibc_ug_dl,transferrin_saturation_pct,transferrin_receptor_mg_l,uacr_mg_g,serum_creatinine_mg_dl,bun_mg_dl,alt_u_l,ast_u_l,ggt_u_l,alp_u_l,total_bilirubin_mg_dl,serum_albumin_g_dl,alq111___ever_had_a_drink_of_any_kind_of_alcohol,alq121___past_12_mo_how_often_drink_alcoholic_bev,alq130___avg_#_alcoholic_drinks/day___past_12_mos,alq142___#_days_have_4_or_5_drinks/past_12_mos,alq270___#_times_4_5_drinks_in_2hrs/past_12_mos,alq280___#_times_8+_drinks_in_1_day/past_12_mos,alq290___#_times_12+_drinks_in_1_day/past_12_mos,alq151___ever_have_4/5_or_more_drinks_every_day?,alq170___past_30_days_#_times_4_5_drinks_on_an_oc,bpq020___ever_told_you_had_high_blood_pressure,bpq030___told_had_high_blood_pressure___2+_times,bpd035___age_told_had_hypertension,bpq040a___taking_prescription_for_hypertension,bpq050a___now_taking_prescribed_medicine_for_hbp,bpq080___doctor_told_you___high_cholesterol_level,bpq060___ever_had_blood_cholesterol_checked,bpq070___when_blood_cholesterol_last_checked,bpq090d___told_to_take_prescriptn_for_cholesterol,bpq100d___now_taking_prescribed_medicine,cdq001___sp_ever_had_pain_or_discomfort_in_chest,cdq002___sp_get_it_walking_uphill_or_in_a_hurry,cdq003___during_an_ordinary_pace_on_level_ground,cdq004___if_so_does_sp_continue_or_slow_down,cdq005___does_standing_relieve_pain/discomfort,...,rxqseen___medicine_container_seen_by_interviewer,rxddays___number_of_days_taken_medicine,rxdrsc1___icd_10_cm_code_1,rxdrsc2___icd_10_cm_code_2,rxdrsc3___icd_10_cm_code_3,rxdrsd1___icd_10_cm_code_1_description,rxdrsd2___icd_10_cm_code_2_description,rxdrsd3___icd_10_cm_code_3_description,rxdcount___number_of_prescription_medicines_taken,slq300___usual_sleep_time_on_weekdays_or_workdays,slq310___usual_wake_time_on_weekdays_or_workdays,sld012___sleep_hours___weekdays_or_workdays,slq320___usual_sleep_time_on_weekends,slq330___usual_wake_time_on_weekends,sld013___sleep_hours___weekends,slq030___how_often_do_you_snore?,slq040___how_often_do_you_snort_or_stop_breathing,slq050___ever_told_doctor_had_trouble_sleeping?,smq020___smoked_at_least_100_cigarettes_in_life,smd030___age_started_smoking_cigarettes_regularly,smq040___do_you_now_smoke_cigarettes?,smq050q___how_long_since_quit_smoking_cigarettes,smq050u___unit_of_measure_(day/week/month/year),smd057___#_cigarettes_smoked_per_day_when_quit,smq078___how_soon_after_waking_do_you_smoke,smd641___#_days_smoked_cigs_during_past_30_days,smd650___avg_#_cigarettes/day_during_past_30_days,smd100fl___cigarette_filter_type,smd100mn___cigarette_menthol_indicator,smq670___tried_to_quit_smoking,smq621___cigarettes_smoked_in_entire_life,smd630___age_first_smoked_whole_cigarette,smaquex2___questionnaire_mode_flag,whd010___current_self_reported_height_(inches),whd020___current_self_reported_weight_(pounds),whq030___how_do_you_consider_your_weight,"whq040___like_to_weigh_more,_less_or_same",whd050___self_reported_weight___1_yr_ago_(pounds),whq060___weight_change_intentional,whq070___tried_to_lose_weight_in_past_year,whd080a___ate_less_to_lose_weight,whd080b___switched_to_foods_with_lower_calories,whd080c___ate_less_fat_to_lose_weight,whd080d___exercised_to_lose_weight,whd080e___skipped_meals,whd080f___ate_diet_foods_or_products,whd080g___used_a_liquid_diet_formula,whd080h___joined_a_weight_loss_program,whd080i___took_prescription_diet_pills,whd080j___took_non_rx_suppl._to_lose_weight,whd080k___took_laxatives_or_vomited,whd080m___drank_a_lot_of_water,whd080n___followed_a_special_diet,whd080o___ate_fewer_carbohydrates,whd080p___started_to_smoke_or_began_to_smoke_again,"whd080q___ate_more_fruits,_vegetables,_salads",whd080r___changed_eating_habits,"whd080s___ate_less_sugar,_candy,_sweets",whd080t___ate_less_junk_food_or_fast_food,whd080u___had_weight_loss_surgery_to_lose_weight,whd080l___other,whq225___times_lost_10_lbs_or_more_to_lose_weight,whd110___self_reported_weight_10_yrs_ago_(pounds),whd120___self_reported_weight_age_25_(pounds),whd130___self_reported_height___age_25_(inches),whd140___self_reported_greatest_weight_(pounds),whq150___age_when_heaviest_weight,ocd150___type_of_work_done_last_week,ocq180___hours_worked_last_week_in_total_all_jobs,ocq210___usually_work_35_or_more_hours_per_week,ocq670___overall_work_schedule_past_3_months,ocd383___main_reason_did_not_work_last_week,SEQN.1,medication_1,medication_2,medication_3,medication_4,medication_5,medication_6,medication_7,medication_8,medication_9,medication_10,medication_11,medication_12,medication_13,medication_14,medication_15,medication_16,medication_17,medication_18,medication_19,medication_20,medication_21,medication_22,med_count,fatigue_binary,cluster,nan_count,nan_group
0,109266,2.0,29.0,6.0,5.0,2.0,5.0,3.0,2.0,5.00,8.154968e+03,7825.646112,2.0,168.0,Female,Non-Hispanic Asian,College graduate or above,Never married,Not pregnant,Born in Mexico,1698.0,52.58,217.69,73.81,12.07,1.65,1.6,283.0,300.0,6.64,160.2,97.1,37.8,117.9,126.1,99.0,99.0,99.0,56.0,55.0,52.0,68.0,66.0,66.0,277.0,6.4,1.0,10.0,15.6,NaN,NaN,1.0,2.0,2.0,2.0,16.0,51.0,NaN,NaN,195.0,56.0,NaN,11.6,50.0,424.0,12.0,3.7,15.28,0.63,8.0,15.0,14.0,8.0,74.0,0.5,3.8,1.0,10.0,1.0,0.0,NaN,NaN,NaN,2.0,0.0,2.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22:00,05:30,7.5,23:00,07:00,8.0,1.0,0.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,64.0,210.0,1.0,2.0,200.0,NaN,1.0,NaN,11.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.0,30.0,NaN,NaN,NaN,44.0,NaN,46.0,NaN,NaN,2.0,NaN,210.0,NaN,218.0,28.0,1.0,40.0,NaN,1.0,NaN,109266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,172,151-200
1,109267,2.0,21.0,2.0,2.0,3.0,4.0,3.0,2.0,5.00,5.397605e-79,26379.991724,1.0,156.0,Female,Other Hispanic,Some college / AA,Never married,Cannot determine,Born in Mexico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,00:00,08:00,8.0,03:00,11:00,8.0,0.0,0.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,63.0,130.0,3.0,1.0,125.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,148.0,19.0,1.0,40.0,NaN,1.0,NaN,109267,99999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,201,201-250
2,109268,2.0,18.0,3.0,3.0,NaN,NaN,NaN,1.0,1.66,5.397605e-79,19639.221008,1.0,155.0,Female,Non-Hispanic White,NaN,NaN,NaN,Born in 50 US states or DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,61.0,Z79.3,NaN,NaN,Long term (current) use of hormonal contraceptives,NaN,NaN,1.0,22:00,06:30,8.5,23:00,07:00,8.0,0.0,0.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,65.0,120.0,3.0,3.0,120.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,135.0,11.0,4.0,NaN,NaN,NaN,2.0,109268,ETHINYL ESTRADIOL; NORGESTIMATE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,216,201-250
3,109271,1.0,49.0,3.0,3.0,NaN,2.0,3.0,1.0,NaN,8.658733e+03,8481.589837,1.0,167.0,Male,Non-Hispanic White,9-11th grade,Never married,NaN,Born in 50 US states or DC,2310.0,110.62,207.54,113.77,14.04,5.67,1.1,486.0,411.0,18.77,182.3,98.8,29.7,120.4,108.2,102.0,108.0,111.0,65.0,68.0,68.0,73.0,71.0,70.0,303.0,5.5,1.0,10.0,10.9,1.0,1.0,1.0,2.0,1.0,2.0,10.0,26.0,103.0,16.96,147.0,33.0,84.0,196.0,64.0,284.0,23.0,NaN,7.50,0.78,8.0,8.0,14.0,12.0,88.0,0.5,3.8,1.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,...,1.0,2920.0,L40,NaN,NaN,Psoriasis,NaN,NaN,3.0,23:00,09:00,10.0,23:00,12:00,13.0,0.0,0.0,1.0,1.0,18.0,1.0,NaN,NaN,NaN,2.0,30.0,20.0,NaN,NaN,1.0,NaN,NaN,1.0,72.0,222.0,3.0,3.0,180.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,280.0,350.0,NaN,350.0,24.0,4.0,NaN,NaN,NaN,4.0,109271,ADALIMUMAB,LEVETIRACETAM,SIMVASTATIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,3,166,151-200
4,109273,1.0,36.0,3.0,3.0,NaN,4.0,3.0,1.0,0.83,2.216360e+04,20171.847767,1.0,155.0,Male,Non-Hispanic White,Some college / AA,Never married,NaN,Born in 50 US states or DC,1403.0,56.73,265.59,13.70,8.85,8.75,0.0,426.0,120.0,3.80,184.2,74.3,21.9,86.8,94.5,116.0,110.0,115.0,68.0,66.0,68.0,71.0,70.0,70.0,222.0,2.7,1.0,10.0,25.9,1.0,NaN,NaN,2.0,2.0,2.0,9.0,29.0,NaN,NaN,164.0,42.0,NaN,313.0,210.0,295.0,71.0,NaN,4.05,0.92,11.0,35.0,27.0,19.0,70.0,0.6,4.6,1.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,7.0,K08.8,NaN,NaN,Other specified disorders of teeth and supporting structures,NaN,NaN,3.0,08:00,14:35,6.5,21:00,05:00,8.0,0.0,0.0,1.0,1.0,18.0,1.0,NaN,NaN,NaN,1.0,30.0,15.0,1.0,1.0,1.0,NaN,NaN,1.0,72.0,165.0,2.0,1.0,155.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,150.0,155.0,NaN,300.0,16.0,1.0,28.0,2.0,2.0,NaN,109273,ACETAMINOPHEN; HYDROCODONE,FAMOTIDINE,PENICILLIN V POTASSIUM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,3,172,151-200

In [8]:
def dataset_overview(dataframe):
    overview = pd.DataFrame({
        "column": dataframe.columns,
        "dtype": dataframe.dtypes.astype(str).values,
        "missing_n": dataframe.isna().sum().values,
        "missing_pct": (dataframe.isna().mean().values * 100).round(2),
        "n_unique": dataframe.nunique(dropna=True).values
    }).sort_values("missing_pct", ascending=False)
    return overview

overview = dataset_overview(df)
display(overview.head(30))

print("Rows:", len(df))
print("Columns:", df.shape[1])
print("Numeric columns:", df.select_dtypes(include=np.number).shape[1])
print("Non-numeric columns:", df.select_dtypes(exclude=np.number).shape[1])

,column,dtype,missing_n,missing_pct,n_unique
301,smq621___cigarettes_smoked_in_entire_life,float64,7437,100.00,0
302,smd630___age_first_smoked_whole_cigarette,float64,7437,100.00,0
174,mcq151___age_in_years_at_first_menstrual_period,float64,7437,100.00,0
173,mcq149___menstrual_periods_started_yet?,float64,7437,100.00,0
365,medication_22,str,7435,99.97,2
364,medication_21,str,7435,99.97,2
363,medication_20,str,7434,99.96,3
210,mcq230c___what_kind_of_cancer_third_mention,float64,7432,99.93,4
362,medication_19,str,7432,99.93,5
196,mcq510b___liver_condition_non_alcoholic_fatty_liver,float64,7431,99.92,1
361,medication_18,str,7430,99.91,7
107,cdq009g___pain_in_left_arm,float64,7426,99.85,1
360,medication_17,str,7425,99.84,12
103,cdq009c___pain_in_neck,float64,7425,99.84,1
199,mcq510e___liver_condition_autoimmune,float64,7424,99.83,1
101,cdq009a___pain_in_right_arm,float64,7423,99.81,1
359,medication_16,str,7419,99.76,18
197,mcq510c___liver_condition_alcoholic_liver_disease,float64,7415,99.70,1
240,rhq020___age_range_at_first_menstrual_period,float64,7413,99.68,5
330,whd080u___had_weight_loss_surgery_to_lose_weight,float64,7412,99.66,1
358,medication_15,str,7412,99.66,23
209,mcq230b___what_kind_of_cancer_second_mention,float64,7408,99.61,15
244,rhq070___age_range_at_last_menstrual_period,float64,7408,99.61,8
357,medication_14,str,7402,99.53,26
356,medication_13,str,7394,99.42,30
102,cdq009b___pain_in_right_chest,float64,7393,99.41,1
264,rhq542b___hormone_patches_used,float64,7386,99.31,1
325,whd080p___started_to_smoke_or_began_to_smoke_again,float64,7385,99.30,1
105,cdq009e___pain_in_lower_sternum,float64,7380,99.23,1
198,mcq510d___liver_condition_hepatitis,float64,7378,99.21,1

Rows: 7437
Columns: 371
Numeric columns: 330
Non-numeric columns: 41

## Rename column names (domain demographics) and remove doubles

In [21]:
from pathlib import Path
import pandas as pd

# Sicherheitskopie
df_clean = df.copy()

# 1) Kryptische NHANES-Spalten droppen, wenn bereits eine lesbare Version existiert
drop_if_readable_exists = {
    "RIAGENDR": "gender",
    "RIDRETH1": "ethnicity",
    "RIDRETH3": "ethnicity",
    "DMDEDUC2": "education",
    "DMDMARTZ": "marital_status",
    "RIDEXPRG": "pregnancy_status",
    "DMDBORN4": "country_of_birth",
}

cols_to_drop = [
    raw_col
    for raw_col, readable_col in drop_if_readable_exists.items()
    if raw_col in df_clean.columns and readable_col in df_clean.columns
]

# 2) Spalten umbenennen, für die es noch keine lesbare Version gibt
rename_map = {
    "RIDAGEYR": "age_years",
    "INDFMPIR": "income_poverty_ratio",
    "WTMECPRP": "mec_exam_weight",
    "WTINTPRP": "interview_weight",
    "SDMVPSU": "survey_psu",
    "SDMVSTRA": "survey_stratum",
}

# Nur umbenennen, wenn die Originalspalte existiert und der Zielname noch nicht existiert
rename_map_final = {
    old: new
    for old, new in rename_map.items()
    if old in df_clean.columns and new not in df_clean.columns
}

# Anwenden
df_clean = df_clean.drop(columns=cols_to_drop).rename(columns=rename_map_final)

print("Gedroppt:")
print(cols_to_drop)

print("\nUmbenannt:")
print(rename_map_final)

print("\nNeue Shape:", df_clean.shape)
display(df_clean.head())

Gedroppt:
['RIAGENDR', 'RIDRETH1', 'RIDRETH3', 'DMDEDUC2', 'DMDMARTZ', 'RIDEXPRG', 'DMDBORN4']

Umbenannt:
{'RIDAGEYR': 'age_years', 'INDFMPIR': 'income_poverty_ratio', 'WTMECPRP': 'mec_exam_weight', 'WTINTPRP': 'interview_weight', 'SDMVPSU': 'survey_psu', 'SDMVSTRA': 'survey_stratum'}

Neue Shape: (7437, 364)

,SEQN,age_years,income_poverty_ratio,mec_exam_weight,interview_weight,survey_psu,survey_stratum,gender,ethnicity,education,marital_status,pregnancy_status,country_of_birth,calories,protein,carbs,fat,iron,vitamin_b12,vitamin_d,folate,magnesium,zinc,height_cm,weight_kg,bmi,waist_cm,hip_cm,sbp_1,sbp_2,sbp_3,dbp_1,dbp_2,dbp_3,pulse_1,pulse_2,pulse_3,liver_cap_dbm,liver_stiffness_kpa,liver_exam_status,liver_valid_measures,liver_stiffness_iqr_ratio,oral_gum_problem_yesno,oral_decayed_teeth_yesno,oral_hygiene_issue_yesno,any_implant,any_root_caries,any_root_restoration_caries,fasting_hours_part,fasting_minutes_part,fasting_glucose_mg_dl,insulin_uU_ml,total_cholesterol_mg_dl,hdl_cholesterol_mg_dl,triglycerides_mg_dl,ferritin_ng_ml,serum_iron_ug_dl,tibc_ug_dl,transferrin_saturation_pct,transferrin_receptor_mg_l,uacr_mg_g,serum_creatinine_mg_dl,bun_mg_dl,alt_u_l,ast_u_l,ggt_u_l,alp_u_l,total_bilirubin_mg_dl,serum_albumin_g_dl,alq111___ever_had_a_drink_of_any_kind_of_alcohol,alq121___past_12_mo_how_often_drink_alcoholic_bev,alq130___avg_#_alcoholic_drinks/day___past_12_mos,alq142___#_days_have_4_or_5_drinks/past_12_mos,alq270___#_times_4_5_drinks_in_2hrs/past_12_mos,alq280___#_times_8+_drinks_in_1_day/past_12_mos,alq290___#_times_12+_drinks_in_1_day/past_12_mos,alq151___ever_have_4/5_or_more_drinks_every_day?,alq170___past_30_days_#_times_4_5_drinks_on_an_oc,bpq020___ever_told_you_had_high_blood_pressure,bpq030___told_had_high_blood_pressure___2+_times,bpd035___age_told_had_hypertension,bpq040a___taking_prescription_for_hypertension,bpq050a___now_taking_prescribed_medicine_for_hbp,bpq080___doctor_told_you___high_cholesterol_level,bpq060___ever_had_blood_cholesterol_checked,bpq070___when_blood_cholesterol_last_checked,bpq090d___told_to_take_prescriptn_for_cholesterol,bpq100d___now_taking_prescribed_medicine,cdq001___sp_ever_had_pain_or_discomfort_in_chest,cdq002___sp_get_it_walking_uphill_or_in_a_hurry,cdq003___during_an_ordinary_pace_on_level_ground,cdq004___if_so_does_sp_continue_or_slow_down,cdq005___does_standing_relieve_pain/discomfort,cdq006___how_soon_is_the_pain_relieved,cdq009a___pain_in_right_arm,cdq009b___pain_in_right_chest,cdq009c___pain_in_neck,cdq009d___pain_in_upper_sternum,cdq009e___pain_in_lower_sternum,cdq009f___pain_in_left_chest,...,rxqseen___medicine_container_seen_by_interviewer,rxddays___number_of_days_taken_medicine,rxdrsc1___icd_10_cm_code_1,rxdrsc2___icd_10_cm_code_2,rxdrsc3___icd_10_cm_code_3,rxdrsd1___icd_10_cm_code_1_description,rxdrsd2___icd_10_cm_code_2_description,rxdrsd3___icd_10_cm_code_3_description,rxdcount___number_of_prescription_medicines_taken,slq300___usual_sleep_time_on_weekdays_or_workdays,slq310___usual_wake_time_on_weekdays_or_workdays,sld012___sleep_hours___weekdays_or_workdays,slq320___usual_sleep_time_on_weekends,slq330___usual_wake_time_on_weekends,sld013___sleep_hours___weekends,slq030___how_often_do_you_snore?,slq040___how_often_do_you_snort_or_stop_breathing,slq050___ever_told_doctor_had_trouble_sleeping?,smq020___smoked_at_least_100_cigarettes_in_life,smd030___age_started_smoking_cigarettes_regularly,smq040___do_you_now_smoke_cigarettes?,smq050q___how_long_since_quit_smoking_cigarettes,smq050u___unit_of_measure_(day/week/month/year),smd057___#_cigarettes_smoked_per_day_when_quit,smq078___how_soon_after_waking_do_you_smoke,smd641___#_days_smoked_cigs_during_past_30_days,smd650___avg_#_cigarettes/day_during_past_30_days,smd100fl___cigarette_filter_type,smd100mn___cigarette_menthol_indicator,smq670___tried_to_quit_smoking,smq621___cigarettes_smoked_in_entire_life,smd630___age_first_smoked_whole_cigarette,smaquex2___questionnaire_mode_flag,whd010___current_self_reported_height_(inches),whd020___current_self_reported_weight_(pounds),whq030___how_do_you_consider_your_weight,"whq040___like_to_weigh_more,_less_or_same",whd050___self_reported_weight___1_yr_ago_(pounds),whq060___weight_change_intentional,whq070___tried_to_lose_weight_in_past_year,whd080a___ate_less_to_lose_weight,whd080b___switched_to_foods_with_lower_calories,whd080c___ate_less_fat_to_lose_weight,whd080d___exercised_to_lose_weight,whd080e___skipped_meals,whd080f___ate_diet_foods_or_products,whd080g___used_a_liquid_diet_formula,whd080h___joined_a_weight_loss_program,whd080i___took_prescription_diet_pills,whd080j___took_non_rx_suppl._to_lose_weight,whd080k___took_laxatives_or_vomited,whd080m___drank_a_lot_of_water,whd080n___followed_a_special_diet,whd080o___ate_fewer_carbohydrates,whd080p___started_to_smoke_or_began_to_smoke_again,"whd080q___ate_more_fruits,_vegetables,_salads",whd080r___changed_eating_habits,"whd080s___ate_less_sugar,_candy,_sweets",whd080t___ate_less_junk_food_or_fast_food,whd080u___had_weight_loss_surgery_to_lose_weight,whd080l___other,whq225___times_lost_10_lbs_or_more_to_lose_weight,whd110___self_reported_weight_10_yrs_ago_(pounds),whd120___self_reported_weight_age_25_(pounds),whd130___self_reported_height___age_25_(inches),whd140___self_reported_greatest_weight_(pounds),whq150___age_when_heaviest_weight,ocd150___type_of_work_done_last_week,ocq180___hours_worked_last_week_in_total_all_jobs,ocq210___usually_work_35_or_more_hours_per_week,ocq670___overall_work_schedule_past_3_months,ocd383___main_reason_did_not_work_last_week,SEQN.1,medication_1,medication_2,medication_3,medication_4,medication_5,medication_6,medication_7,medication_8,medication_9,medication_10,medication_11,medication_12,medication_13,medication_14,medication_15,medication_16,medication_17,medication_18,medication_19,medication_20,medication_21,medication_22,med_count,fatigue_binary,cluster,nan_count,nan_group
0,109266,29.0,5.00,8.154968e+03,7825.646112,2.0,168.0,Female,Non-Hispanic Asian,College graduate or above,Never married,Not pregnant,Born in Mexico,1698.0,52.58,217.69,73.81,12.07,1.65,1.6,283.0,300.0,6.64,160.2,97.1,37.8,117.9,126.1,99.0,99.0,99.0,56.0,55.0,52.0,68.0,66.0,66.0,277.0,6.4,1.0,10.0,15.6,NaN,NaN,1.0,2.0,2.0,2.0,16.0,51.0,NaN,NaN,195.0,56.0,NaN,11.6,50.0,424.0,12.0,3.7,15.28,0.63,8.0,15.0,14.0,8.0,74.0,0.5,3.8,1.0,10.0,1.0,0.0,NaN,NaN,NaN,2.0,0.0,2.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22:00,05:30,7.5,23:00,07:00,8.0,1.0,0.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,64.0,210.0,1.0,2.0,200.0,NaN,1.0,NaN,11.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.0,30.0,NaN,NaN,NaN,44.0,NaN,46.0,NaN,NaN,2.0,NaN,210.0,NaN,218.0,28.0,1.0,40.0,NaN,1.0,NaN,109266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,172,151-200
1,109267,21.0,5.00,5.397605e-79,26379.991724,1.0,156.0,Female,Other Hispanic,Some college / AA,Never married,Cannot determine,Born in Mexico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,00:00,08:00,8.0,03:00,11:00,8.0,0.0,0.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,63.0,130.0,3.0,1.0,125.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,148.0,19.0,1.0,40.0,NaN,1.0,NaN,109267,99999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,201,201-250
2,109268,18.0,1.66,5.397605e-79,19639.221008,1.0,155.0,Female,Non-Hispanic White,NaN,NaN,NaN,Born in 50 US states or DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,61.0,Z79.3,NaN,NaN,Long term (current) use of hormonal contraceptives,NaN,NaN,1.0,22:00,06:30,8.5,23:00,07:00,8.0,0.0,0.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,65.0,120.0,3.0,3.0,120.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,135.0,11.0,4.0,NaN,NaN,NaN,2.0,109268,ETHINYL ESTRADIOL; NORGESTIMATE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,216,201-250
3,109271,49.0,NaN,8.658733e+03,8481.589837,1.0,167.0,Male,Non-Hispanic White,9-11th grade,Never married,NaN,Born in 50 US states or DC,2310.0,110.62,207.54,113.77,14.04,5.67,1.1,486.0,411.0,18.77,182.3,98.8,29.7,120.4,108.2,102.0,108.0,111.0,65.0,68.0,68.0,73.0,71.0,70.0,303.0,5.5,1.0,10.0,10.9,1.0,1.0,1.0,2.0,1.0,2.0,10.0,26.0,103.0,16.96,147.0,33.0,84.0,196.0,64.0,284.0,23.0,NaN,7.50,0.78,8.0,8.0,14.0,12.0,88.0,0.5,3.8,1.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2920.0,L40,NaN,NaN,Psoriasis,NaN,NaN,3.0,23:00,09:00,10.0,23:00,12:00,13.0,0.0,0.0,1.0,1.0,18.0,1.0,NaN,NaN,NaN,2.0,30.0,20.0,NaN,NaN,1.0,NaN,NaN,1.0,72.0,222.0,3.0,3.0,180.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,280.0,350.0,NaN,350.0,24.0,4.0,NaN,NaN,NaN,4.0,109271,ADALIMUMAB,LEVETIRACETAM,SIMVASTATIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,3,166,151-200
4,109273,36.0,0.83,2.216360e+04,20171.847767,1.0,155.0,Male,Non-Hispanic White,Some college / AA,Never married,NaN,Born in 50 US states or DC,1403.0,56.73,265.59,13.70,8.85,8.75,0.0,426.0,120.0,3.80,184.2,74.3,21.9,86.8,94.5,116.0,110.0,115.0,68.0,66.0,68.0,71.0,70.0,70.0,222.0,2.7,1.0,10.0,25.9,1.0,NaN,NaN,2.0,2.0,2.0,9.0,29.0,NaN,NaN,164.0,42.0,NaN,313.0,210.0,295.0,71.0,NaN,4.05,0.92,11.0,35.0,27.0,19.0,70.0,0.6,4.6,1.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,7.0,K08.8,NaN,NaN,Other specified disorders of teeth and supporting structures,NaN,NaN,3.0,08:00,14:35,6.5,21:00,05:00,8.0,0.0,0.0,1.0,1.0,18.0,1.0,NaN,NaN,NaN,1.0,30.0,15.0,1.0,1.0,1.0,NaN,NaN,1.0,72.0,165.0,2.0,1.0,155.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,150.0,155.0,NaN,300.0,16.0,1.0,28.0,2.0,2.0,NaN,109273,ACETAMINOPHEN; HYDROCODONE,FAMOTIDINE,PENICILLIN V POTASSIUM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,3,172,151-200

In [23]:
output_path = Path("../data/processed/nhanes_merged_adults_cleaned.csv")
df_clean.to_csv(output_path, index=False)
print(f"Gespeichert unter: {output_path}")

Gespeichert unter: ..\data\processed\nhanes_merged_adults_cleaned.csv

## Domain Mapping

In [26]:
from pathlib import Path
import pandas as pd
import numpy as np
import re

BASE_PATH = Path("../data/processed")

SOURCE_FILES = {
    "demographics": BASE_PATH / "demo_all_adults.csv",
    "dietary": BASE_PATH / "dietary_clean.csv",
    "examination": BASE_PATH / "examination_clean.csv",
    "laboratory": BASE_PATH / "laboratory_clean.csv",
    "questionnaire": BASE_PATH / "merged_questionnaire.csv",
}

In [27]:
def normalize_colname(col):
    col = str(col).strip().lower()
    col = re.sub(r"[^a-z0-9]+", "_", col)
    col = re.sub(r"_+", "_", col).strip("_")
    return col

In [28]:
catalog_rows = []

for domain, path in SOURCE_FILES.items():
    cols = pd.read_csv(path, nrows=0).columns.tolist()
    
    for col in cols:
        catalog_rows.append({
            "source_domain": domain,
            "source_file": path.name,
            "source_column": col,
            "source_column_norm": normalize_colname(col)
        })

source_catalog = pd.DataFrame(catalog_rows)

display(source_catalog.head())
print("Anzahl Katalog-Zeilen:", len(source_catalog))

  source_domain          source_file source_column source_column_norm
0  demographics  demo_all_adults.csv          SEQN               seqn
1  demographics  demo_all_adults.csv      RIAGENDR           riagendr
2  demographics  demo_all_adults.csv      RIDAGEYR           ridageyr
3  demographics  demo_all_adults.csv      RIDRETH3           ridreth3
4  demographics  demo_all_adults.csv      RIDRETH1           ridreth1

Anzahl Katalog-Zeilen: 375

In [29]:
duplicate_source_cols = (
    source_catalog.groupby("source_column_norm")
    .agg(
        n_sources=("source_file", "nunique"),
        source_files=("source_file", lambda x: " | ".join(sorted(set(x)))),
        domains=("source_domain", lambda x: " | ".join(sorted(set(x))))
    )
    .reset_index()
)

duplicates_only = duplicate_source_cols[duplicate_source_cols["n_sources"] > 1]
display(duplicates_only.head(20))

,source_column_norm,n_sources,source_files,domains
294,seqn,5,demo_all_adults.csv | dietary_clean.csv | examination_clean.csv | laboratory_clean.csv | merged_questionnaire.csv,demographics | dietary | examination | laboratory | questionnaire

In [30]:
def dataset_overview(dataframe):
    overview = pd.DataFrame({
        "column": dataframe.columns,
        "dtype": dataframe.dtypes.astype(str).values,
        "missing_n": dataframe.isna().sum().values,
        "missing_pct": (dataframe.isna().mean().values * 100).round(2),
        "n_unique": dataframe.nunique(dropna=True).values
    })
    return overview.sort_values("missing_pct", ascending=False)

overview_clean = dataset_overview(df_clean)
display(overview_clean.head(30))

,column,dtype,missing_n,missing_pct,n_unique
167,mcq151___age_in_years_at_first_menstrual_period,float64,7437,100.00,0
295,smd630___age_first_smoked_whole_cigarette,float64,7437,100.00,0
294,smq621___cigarettes_smoked_in_entire_life,float64,7437,100.00,0
166,mcq149___menstrual_periods_started_yet?,float64,7437,100.00,0
358,medication_22,str,7435,99.97,2
357,medication_21,str,7435,99.97,2
356,medication_20,str,7434,99.96,3
355,medication_19,str,7432,99.93,5
203,mcq230c___what_kind_of_cancer_third_mention,float64,7432,99.93,4
189,mcq510b___liver_condition_non_alcoholic_fatty_liver,float64,7431,99.92,1
354,medication_18,str,7430,99.91,7
100,cdq009g___pain_in_left_arm,float64,7426,99.85,1
96,cdq009c___pain_in_neck,float64,7425,99.84,1
353,medication_17,str,7425,99.84,12
192,mcq510e___liver_condition_autoimmune,float64,7424,99.83,1
94,cdq009a___pain_in_right_arm,float64,7423,99.81,1
352,medication_16,str,7419,99.76,18
190,mcq510c___liver_condition_alcoholic_liver_disease,float64,7415,99.70,1
233,rhq020___age_range_at_first_menstrual_period,float64,7413,99.68,5
323,whd080u___had_weight_loss_surgery_to_lose_weight,float64,7412,99.66,1
351,medication_15,str,7412,99.66,23
202,mcq230b___what_kind_of_cancer_second_mention,float64,7408,99.61,15
237,rhq070___age_range_at_last_menstrual_period,float64,7408,99.61,8
350,medication_14,str,7402,99.53,26
349,medication_13,str,7394,99.42,30
95,cdq009b___pain_in_right_chest,float64,7393,99.41,1
257,rhq542b___hormone_patches_used,float64,7386,99.31,1
318,whd080p___started_to_smoke_or_began_to_smoke_again,float64,7385,99.30,1
98,cdq009e___pain_in_lower_sternum,float64,7380,99.23,1
191,mcq510d___liver_condition_hepatitis,float64,7378,99.21,1

In [31]:
overview["column_norm"] = overview["column"].apply(normalize_colname)

source_lookup = (
    source_catalog.groupby("source_column_norm")
    .agg(
        source_domain=("source_domain", lambda x: " | ".join(sorted(set(x)))),
        source_file=("source_file", lambda x: " | ".join(sorted(set(x)))),
        source_column=("source_column", lambda x: " | ".join(sorted(set(x))))
    )
    .reset_index()
)

overview = overview.merge(
    source_lookup,
    left_on="column_norm",
    right_on="source_column_norm",
    how="left"
)

overview["domain"] = overview["source_domain"]
overview["mapping_method"] = np.where(
    overview["domain"].notna(),
    "exact_header_match",
    pd.NA
)

display(overview.head(20))

,column,dtype,missing_n,missing_pct,n_unique,column_norm,source_column_norm_x,source_domain_x,source_file_x,source_column_x,domain,mapping_method,missing_bucket,source_column_norm_y,source_domain_y,source_file_y,source_column_y,source_column_norm,source_domain,source_file,source_column
0,SEQN,int64,0,0.00,7437,seqn,seqn,demographics | dietary | examination | laboratory | questionnaire,demo_all_adults.csv | dietary_clean.csv | examination_clean.csv | laboratory_clean.csv | merged_questionnaire.csv,SEQN,demographics | dietary | examination | laboratory | questionnaire,exact_header_match,0-5%,seqn,demographics | dietary | examination | laboratory | questionnaire,demo_all_adults.csv | dietary_clean.csv | examination_clean.csv | laboratory_clean.csv | merged_questionnaire.csv,SEQN,seqn,demographics | dietary | examination | laboratory | questionnaire,demo_all_adults.csv | dietary_clean.csv | examination_clean.csv | laboratory_clean.csv | merged_questionnaire.csv,SEQN
1,RIAGENDR,float64,0,0.00,2,riagendr,riagendr,demographics,demo_all_adults.csv,RIAGENDR,demographics,exact_header_match,0-5%,riagendr,demographics,demo_all_adults.csv,RIAGENDR,riagendr,demographics,demo_all_adults.csv,RIAGENDR
2,RIDAGEYR,float64,0,0.00,48,ridageyr,ridageyr,demographics,demo_all_adults.csv,RIDAGEYR,demographics,exact_header_match,0-5%,ridageyr,demographics,demo_all_adults.csv,RIDAGEYR,ridageyr,demographics,demo_all_adults.csv,RIDAGEYR
3,RIDRETH3,float64,0,0.00,6,ridreth3,ridreth3,demographics,demo_all_adults.csv,RIDRETH3,demographics,exact_header_match,0-5%,ridreth3,demographics,demo_all_adults.csv,RIDRETH3,ridreth3,demographics,demo_all_adults.csv,RIDRETH3
4,RIDRETH1,float64,0,0.00,5,ridreth1,ridreth1,demographics,demo_all_adults.csv,RIDRETH1,demographics,exact_header_match,0-5%,ridreth1,demographics,demo_all_adults.csv,RIDRETH1,ridreth1,demographics,demo_all_adults.csv,RIDRETH1
5,RIDEXPRG,float64,5563,74.80,3,ridexprg,ridexprg,demographics,demo_all_adults.csv,RIDEXPRG,demographics,exact_header_match,50-80%,ridexprg,demographics,demo_all_adults.csv,RIDEXPRG,ridexprg,demographics,demo_all_adults.csv,RIDEXPRG
6,DMDEDUC2,float64,461,6.20,7,dmdeduc2,dmdeduc2,demographics,demo_all_adults.csv,DMDEDUC2,demographics,exact_header_match,5-20%,dmdeduc2,demographics,demo_all_adults.csv,DMDEDUC2,dmdeduc2,demographics,demo_all_adults.csv,DMDEDUC2
7,DMDMARTZ,float64,461,6.20,4,dmdmartz,dmdmartz,demographics,demo_all_adults.csv,DMDMARTZ,demographics,exact_header_match,5-20%,dmdmartz,demographics,demo_all_adults.csv,DMDMARTZ,dmdmartz,demographics,demo_all_adults.csv,DMDMARTZ
8,DMDBORN4,float64,0,0.00,4,dmdborn4,dmdborn4,demographics,demo_all_adults.csv,DMDBORN4,demographics,exact_header_match,0-5%,dmdborn4,demographics,demo_all_adults.csv,DMDBORN4,dmdborn4,demographics,demo_all_adults.csv,DMDBORN4
9,INDFMPIR,float64,1118,15.03,460,indfmpir,indfmpir,demographics,demo_all_adults.csv,INDFMPIR,demographics,exact_header_match,5-20%,indfmpir,demographics,demo_all_adults.csv,INDFMPIR,indfmpir,demographics,demo_all_adults.csv,INDFMPIR
10,WTMECPRP,float64,0,0.00,6477,wtmecprp,wtmecprp,demographics,demo_all_adults.csv,WTMECPRP,demographics,exact_header_match,0-5%,wtmecprp,demographics,demo_all_adults.csv,WTMECPRP,wtmecprp,demographics,demo_all_adults.csv,WTMECPRP
11,WTINTPRP,float64,0,0.00,6907,wtintprp,wtintprp,demographics,demo_all_adults.csv,WTINTPRP,demographics,exact_header_match,0-5%,wtintprp,demographics,demo_all_adults.csv,WTINTPRP,wtintprp,demographics,demo_all_adults.csv,WTINTPRP
12,SDMVPSU,float64,0,0.00,3,sdmvpsu,sdmvpsu,demographics,demo_all_adults.csv,SDMVPSU,demographics,exact_header_match,0-5%,sdmvpsu,demographics,demo_all_adults.csv,SDMVPSU,sdmvpsu,demographics,demo_all_adults.csv,SDMVPSU
13,SDMVSTRA,float64,0,0.00,24,sdmvstra,sdmvstra,demographics,demo_all_adults.csv,SDMVSTRA,demographics,exact_header_match,0-5%,sdmvstra,demographics,demo_all_adults.csv,SDMVSTRA,sdmvstra,demographics,demo_all_adults.csv,SDMVSTRA
14,gender,str,0,0.00,2,gender,gender,demographics,demo_all_adults.csv,gender,demographics,exact_header_match,0-5%,gender,demographics,demo_all_adults.csv,gender,gender,demographics,demo_all_adults.csv,gender
15,ethnicity,str,0,0.00,6,ethnicity,ethnicity,demographics,demo_all_adults.csv,ethnicity,demographics,exact_header_match,0-5%,ethnicity,demographics,demo_all_adults.csv,ethnicity,ethnicity,demographics,demo_all_adults.csv,ethnicity
16,education,str,461,6.20,7,education,education,demographics,demo_all_adults.csv,education,demographics,exact_header_match,5-20%,education,demographics,demo_all_adults.csv,education,education,demographics,demo_all_adults.csv,education
17,marital_status,str,461,6.20,4,marital_status,marital_status,demographics,demo_all_adults.csv,marital_status,demographics,exact_header_match,5-20%,marital_status,demographics,demo_all_adults.csv,marital_status,marital_status,demographics,demo_all_adults.csv,marital_status
18,pregnancy_status,str,5563,74.80,3,pregnancy_status,pregnancy_status,demographics,demo_all_adults.csv,pregnancy_status,demographics,exact_header_match,50-80%,pregnancy_status,demographics,demo_all_adults.csv,pregnancy_status,pregnancy_status,demographics,demo_all_adults.csv,pregnancy_status
19,country_of_birth,str,0,0.00,4,country_of_birth,country_of_birth,demographics,demo_all_adults.csv,country_of_birth,demographics,exact_header_match,0-5%,country_of_birth,demographics,demo_all_adults.csv,country_of_birth,country_of_birth,demographics,demo_all_adults.csv,country_of_birth

In [32]:
overview.to_csv("03_overview_with_domain_mapping.csv", index=False)
print("Saved: 03_overview_with_domain_mapping.csv")

Saved: 03_overview_with_domain_mapping.csv

### doubles:

In [33]:
demographic_cols = overview[
    overview["domain"].str.contains("demographics", na=False)
]

display(demographic_cols)

,column,dtype,missing_n,missing_pct,n_unique,column_norm,source_column_norm_x,source_domain_x,source_file_x,source_column_x,domain,mapping_method,missing_bucket,source_column_norm_y,source_domain_y,source_file_y,source_column_y,source_column_norm,source_domain,source_file,source_column
0,SEQN,int64,0,0.00,7437,seqn,seqn,demographics | dietary | examination | laboratory | questionnaire,demo_all_adults.csv | dietary_clean.csv | examination_clean.csv | laboratory_clean.csv | merged_questionnaire.csv,SEQN,demographics | dietary | examination | laboratory | questionnaire,exact_header_match,0-5%,seqn,demographics | dietary | examination | laboratory | questionnaire,demo_all_adults.csv | dietary_clean.csv | examination_clean.csv | laboratory_clean.csv | merged_questionnaire.csv,SEQN,seqn,demographics | dietary | examination | laboratory | questionnaire,demo_all_adults.csv | dietary_clean.csv | examination_clean.csv | laboratory_clean.csv | merged_questionnaire.csv,SEQN
1,RIAGENDR,float64,0,0.00,2,riagendr,riagendr,demographics,demo_all_adults.csv,RIAGENDR,demographics,exact_header_match,0-5%,riagendr,demographics,demo_all_adults.csv,RIAGENDR,riagendr,demographics,demo_all_adults.csv,RIAGENDR
2,RIDAGEYR,float64,0,0.00,48,ridageyr,ridageyr,demographics,demo_all_adults.csv,RIDAGEYR,demographics,exact_header_match,0-5%,ridageyr,demographics,demo_all_adults.csv,RIDAGEYR,ridageyr,demographics,demo_all_adults.csv,RIDAGEYR
3,RIDRETH3,float64,0,0.00,6,ridreth3,ridreth3,demographics,demo_all_adults.csv,RIDRETH3,demographics,exact_header_match,0-5%,ridreth3,demographics,demo_all_adults.csv,RIDRETH3,ridreth3,demographics,demo_all_adults.csv,RIDRETH3
4,RIDRETH1,float64,0,0.00,5,ridreth1,ridreth1,demographics,demo_all_adults.csv,RIDRETH1,demographics,exact_header_match,0-5%,ridreth1,demographics,demo_all_adults.csv,RIDRETH1,ridreth1,demographics,demo_all_adults.csv,RIDRETH1
5,RIDEXPRG,float64,5563,74.80,3,ridexprg,ridexprg,demographics,demo_all_adults.csv,RIDEXPRG,demographics,exact_header_match,50-80%,ridexprg,demographics,demo_all_adults.csv,RIDEXPRG,ridexprg,demographics,demo_all_adults.csv,RIDEXPRG
6,DMDEDUC2,float64,461,6.20,7,dmdeduc2,dmdeduc2,demographics,demo_all_adults.csv,DMDEDUC2,demographics,exact_header_match,5-20%,dmdeduc2,demographics,demo_all_adults.csv,DMDEDUC2,dmdeduc2,demographics,demo_all_adults.csv,DMDEDUC2
7,DMDMARTZ,float64,461,6.20,4,dmdmartz,dmdmartz,demographics,demo_all_adults.csv,DMDMARTZ,demographics,exact_header_match,5-20%,dmdmartz,demographics,demo_all_adults.csv,DMDMARTZ,dmdmartz,demographics,demo_all_adults.csv,DMDMARTZ
8,DMDBORN4,float64,0,0.00,4,dmdborn4,dmdborn4,demographics,demo_all_adults.csv,DMDBORN4,demographics,exact_header_match,0-5%,dmdborn4,demographics,demo_all_adults.csv,DMDBORN4,dmdborn4,demographics,demo_all_adults.csv,DMDBORN4
9,INDFMPIR,float64,1118,15.03,460,indfmpir,indfmpir,demographics,demo_all_adults.csv,INDFMPIR,demographics,exact_header_match,5-20%,indfmpir,demographics,demo_all_adults.csv,INDFMPIR,indfmpir,demographics,demo_all_adults.csv,INDFMPIR
10,WTMECPRP,float64,0,0.00,6477,wtmecprp,wtmecprp,demographics,demo_all_adults.csv,WTMECPRP,demographics,exact_header_match,0-5%,wtmecprp,demographics,demo_all_adults.csv,WTMECPRP,wtmecprp,demographics,demo_all_adults.csv,WTMECPRP
11,WTINTPRP,float64,0,0.00,6907,wtintprp,wtintprp,demographics,demo_all_adults.csv,WTINTPRP,demographics,exact_header_match,0-5%,wtintprp,demographics,demo_all_adults.csv,WTINTPRP,wtintprp,demographics,demo_all_adults.csv,WTINTPRP
12,SDMVPSU,float64,0,0.00,3,sdmvpsu,sdmvpsu,demographics,demo_all_adults.csv,SDMVPSU,demographics,exact_header_match,0-5%,sdmvpsu,demographics,demo_all_adults.csv,SDMVPSU,sdmvpsu,demographics,demo_all_adults.csv,SDMVPSU
13,SDMVSTRA,float64,0,0.00,24,sdmvstra,sdmvstra,demographics,demo_all_adults.csv,SDMVSTRA,demographics,exact_header_match,0-5%,sdmvstra,demographics,demo_all_adults.csv,SDMVSTRA,sdmvstra,demographics,demo_all_adults.csv,SDMVSTRA
14,gender,str,0,0.00,2,gender,gender,demographics,demo_all_adults.csv,gender,demographics,exact_header_match,0-5%,gender,demographics,demo_all_adults.csv,gender,gender,demographics,demo_all_adults.csv,gender
15,ethnicity,str,0,0.00,6,ethnicity,ethnicity,demographics,demo_all_adults.csv,ethnicity,demographics,exact_header_match,0-5%,ethnicity,demographics,demo_all_adults.csv,ethnicity,ethnicity,demographics,demo_all_adults.csv,ethnicity
16,education,str,461,6.20,7,education,education,demographics,demo_all_adults.csv,education,demographics,exact_header_match,5-20%,education,demographics,demo_all_adults.csv,education,education,demographics,demo_all_adults.csv,education
17,marital_status,str,461,6.20,4,marital_status,marital_status,demographics,demo_all_adults.csv,marital_status,demographics,exact_header_match,5-20%,marital_status,demographics,demo_all_adults.csv,marital_status,marital_status,demographics,demo_all_adults.csv,marital_status
18,pregnancy_status,str,5563,74.80,3,pregnancy_status,pregnancy_status,demographics,demo_all_adults.csv,pregnancy_status,demographics,exact_header_match,50-80%,pregnancy_status,demographics,demo_all_adults.csv,pregnancy_status,pregnancy_status,demographics,demo_all_adults.csv,pregnancy_status
19,country_of_birth,str,0,0.00,4,country_of_birth,country_of_birth,demographics,demo_all_adults.csv,country_of_birth,demographics,exact_header_match,0-5%,country_of_birth,demographics,demo_all_adults.csv,country_of_birth,country_of_birth,demographics,demo_all_adults.csv,country_of_birth

## Missingness Audit

In [34]:
high_missing = overview.sort_values("missing_pct", ascending=False)
display(high_missing.head(50))

,column,dtype,missing_n,missing_pct,n_unique,column_norm,source_column_norm_x,source_domain_x,source_file_x,source_column_x,domain,mapping_method,missing_bucket,source_column_norm_y,source_domain_y,source_file_y,source_column_y,source_column_norm,source_domain,source_file,source_column
301,smq621___cigarettes_smoked_in_entire_life,float64,7437,100.00,0,smq621_cigarettes_smoked_in_entire_life,smq621_cigarettes_smoked_in_entire_life,questionnaire,merged_questionnaire.csv,smq621___cigarettes_smoked_in_entire_life,questionnaire,exact_header_match,95-100%,smq621_cigarettes_smoked_in_entire_life,questionnaire,merged_questionnaire.csv,smq621___cigarettes_smoked_in_entire_life,smq621_cigarettes_smoked_in_entire_life,questionnaire,merged_questionnaire.csv,smq621___cigarettes_smoked_in_entire_life
302,smd630___age_first_smoked_whole_cigarette,float64,7437,100.00,0,smd630_age_first_smoked_whole_cigarette,smd630_age_first_smoked_whole_cigarette,questionnaire,merged_questionnaire.csv,smd630___age_first_smoked_whole_cigarette,questionnaire,exact_header_match,95-100%,smd630_age_first_smoked_whole_cigarette,questionnaire,merged_questionnaire.csv,smd630___age_first_smoked_whole_cigarette,smd630_age_first_smoked_whole_cigarette,questionnaire,merged_questionnaire.csv,smd630___age_first_smoked_whole_cigarette
174,mcq151___age_in_years_at_first_menstrual_period,float64,7437,100.00,0,mcq151_age_in_years_at_first_menstrual_period,mcq151_age_in_years_at_first_menstrual_period,questionnaire,merged_questionnaire.csv,mcq151___age_in_years_at_first_menstrual_period,questionnaire,exact_header_match,95-100%,mcq151_age_in_years_at_first_menstrual_period,questionnaire,merged_questionnaire.csv,mcq151___age_in_years_at_first_menstrual_period,mcq151_age_in_years_at_first_menstrual_period,questionnaire,merged_questionnaire.csv,mcq151___age_in_years_at_first_menstrual_period
173,mcq149___menstrual_periods_started_yet?,float64,7437,100.00,0,mcq149_menstrual_periods_started_yet,mcq149_menstrual_periods_started_yet,questionnaire,merged_questionnaire.csv,mcq149___menstrual_periods_started_yet?,questionnaire,exact_header_match,95-100%,mcq149_menstrual_periods_started_yet,questionnaire,merged_questionnaire.csv,mcq149___menstrual_periods_started_yet?,mcq149_menstrual_periods_started_yet,questionnaire,merged_questionnaire.csv,mcq149___menstrual_periods_started_yet?
365,medication_22,str,7435,99.97,2,medication_22,medication_22,questionnaire,merged_questionnaire.csv,medication_22,questionnaire,exact_header_match,95-100%,medication_22,questionnaire,merged_questionnaire.csv,medication_22,medication_22,questionnaire,merged_questionnaire.csv,medication_22
364,medication_21,str,7435,99.97,2,medication_21,medication_21,questionnaire,merged_questionnaire.csv,medication_21,questionnaire,exact_header_match,95-100%,medication_21,questionnaire,merged_questionnaire.csv,medication_21,medication_21,questionnaire,merged_questionnaire.csv,medication_21
363,medication_20,str,7434,99.96,3,medication_20,medication_20,questionnaire,merged_questionnaire.csv,medication_20,questionnaire,exact_header_match,95-100%,medication_20,questionnaire,merged_questionnaire.csv,medication_20,medication_20,questionnaire,merged_questionnaire.csv,medication_20
210,mcq230c___what_kind_of_cancer_third_mention,float64,7432,99.93,4,mcq230c_what_kind_of_cancer_third_mention,mcq230c_what_kind_of_cancer_third_mention,questionnaire,merged_questionnaire.csv,mcq230c___what_kind_of_cancer_third_mention,questionnaire,exact_header_match,95-100%,mcq230c_what_kind_of_cancer_third_mention,questionnaire,merged_questionnaire.csv,mcq230c___what_kind_of_cancer_third_mention,mcq230c_what_kind_of_cancer_third_mention,questionnaire,merged_questionnaire.csv,mcq230c___what_kind_of_cancer_third_mention
362,medication_19,str,7432,99.93,5,medication_19,medication_19,questionnaire,merged_questionnaire.csv,medication_19,questionnaire,exact_header_match,95-100%,medication_19,questionnaire,merged_questionnaire.csv,medication_19,medication_19,questionnaire,merged_questionnaire.csv,medication_19
196,mcq510b___liver_condition_non_alcoholic_fatty_liver,float64,7431,99.92,1,mcq510b_liver_condition_non_alcoholic_fatty_liver,mcq510b_liver_condition_non_alcoholic_fatty_liver,questionnaire,merged_questionnaire.csv,mcq510b___liver_condition_non_alcoholic_fatty_liver,questionnaire,exact_header_match,95-100%,mcq510b_liver_condition_non_alcoholic_fatty_liver,questionnaire,merged_questionnaire.csv,mcq510b___liver_condition_non_alcoholic_fatty_liver,mcq510b_liver_condition_non_alcoholic_fatty_liver,questionnaire,merged_questionnaire.csv,mcq510b___liver_condition_non_alcoholic_fatty_liver
361,medication_18,str,7430,99.91,7,medication_18,medication_18,questionnaire,merged_questionnaire.csv,medication_18,questionnaire,exact_header_match,95-100%,medication_18,questionnaire,merged_questionnaire.csv,medication_18,medication_18,questionnaire,merged_questionnaire.csv,medication_18
107,cdq009g___pain_in_left_arm,float64,7426,99.85,1,cdq009g_pain_in_left_arm,cdq009g_pain_in_left_arm,questionnaire,merged_questionnaire.csv,cdq009g___pain_in_left_arm,questionnaire,exact_header_match,95-100%,cdq009g_pain_in_left_arm,questionnaire,merged_questionnaire.csv,cdq009g___pain_in_left_arm,cdq009g_pain_in_left_arm,questionnaire,merged_questionnaire.csv,cdq009g___pain_in_left_arm
360,medication_17,str,7425,99.84,12,medication_17,medication_17,questionnaire,merged_questionnaire.csv,medication_17,questionnaire,exact_header_match,95-100%,medication_17,questionnaire,merged_questionnaire.csv,medication_17,medication_17,questionnaire,merged_questionnaire.csv,medication_17
103,cdq009c___pain_in_neck,float64,7425,99.84,1,cdq009c_pain_in_neck,cdq009c_pain_in_neck,questionnaire,merged_questionnaire.csv,cdq009c___pain_in_neck,questionnaire,exact_header_match,95-100%,cdq009c_pain_in_neck,questionnaire,merged_questionnaire.csv,cdq009c___pain_in_neck,cdq009c_pain_in_neck,questionnaire,merged_questionnaire.csv,cdq009c___pain_in_neck
199,mcq510e___liver_condition_autoimmune,float64,7424,99.83,1,mcq510e_liver_condition_autoimmune,mcq510e_liver_condition_autoimmune,questionnaire,merged_questionnaire.csv,mcq510e___liver_condition_autoimmune,questionnaire,exact_header_match,95-100%,mcq510e_liver_condition_autoimmune,questionnaire,merged_questionnaire.csv,mcq510e___liver_condition_autoimmune,mcq510e_liver_condition_autoimmune,questionnaire,merged_questionnaire.csv,mcq510e___liver_condition_autoimmune
101,cdq009a___pain_in_right_arm,float64,7423,99.81,1,cdq009a_pain_in_right_arm,cdq009a_pain_in_right_arm,questionnaire,merged_questionnaire.csv,cdq009a___pain_in_right_arm,questionnaire,exact_header_match,95-100%,cdq009a_pain_in_right_arm,questionnaire,merged_questionnaire.csv,cdq009a___pain_in_right_arm,cdq009a_pain_in_right_arm,questionnaire,merged_questionnaire.csv,cdq009a___pain_in_right_arm
359,medication_16,str,7419,99.76,18,medication_16,medication_16,questionnaire,merged_questionnaire.csv,medication_16,questionnaire,exact_header_match,95-100%,medication_16,questionnaire,merged_questionnaire.csv,medication_16,medication_16,questionnaire,merged_questionnaire.csv,medication_16
197,mcq510c___liver_condition_alcoholic_liver_disease,float64,7415,99.70,1,mcq510c_liver_condition_alcoholic_liver_disease,mcq510c_liver_condition_alcoholic_liver_disease,questionnaire,merged_questionnaire.csv,mcq510c___liver_condition_alcoholic_liver_disease,questionnaire,exact_header_match,95-100%,mcq510c_liver_condition_alcoholic_liver_disease,questionnaire,merged_questionnaire.csv,mcq510c___liver_condition_alcoholic_liver_disease,mcq510c_liver_condition_alcoholic_liver_disease,questionnaire,merged_questionnaire.csv,mcq510c___liver_condition_alcoholic_liver_disease
240,rhq020___age_range_at_first_menstrual_period,float64,7413,99.68,5,rhq020_age_range_at_first_menstrual_period,rhq020_age_range_at_first_menstrual_period,questionnaire,merged_questionnaire.csv,rhq020___age_range_at_first_menstrual_period,questionnaire,exact_header_match,95-100%,rhq020_age_range_at_first_menstrual_period,questionnaire,merged_questionnaire.csv,rhq020___age_range_at_first_menstrual_period,rhq020_age_range_at_first_menstrual_period,questionnaire,merged_questionnaire.csv,rhq020___age_range_at_first_menstrual_period
330,whd080u___had_weight_loss_surgery_to_lose_weight,float64,7412,99.66,1,whd080u_had_weight_loss_surgery_to_lose_weight,whd080u_had_weight_loss_surgery_to_lose_weight,questionnaire,merged_questionnaire.csv,whd080u___had_weight_loss_surgery_to_lose_weight,questionnaire,exact_header_match,95-100%,whd080u_had_weight_loss_surgery_to_lose_weight,questionnaire,merged_questionnaire.csv,whd080u___had_weight_loss_surgery_to_lose_weight,whd080u_had_weight_loss_surgery_to_lose_weight,questionnaire,merged_questionnaire.csv,whd080u___had_weight_loss_surgery_to_lose_weight
358,medication_15,str,7412,99.66,23,medication_15,medication_15,questionnaire,merged_questionnaire.csv,medication_15,questionnaire,exact_header_match,95-100%,medication_15,questionnaire,merged_questionnaire.csv,medication_15,medication_15,questionnaire,merged_questionnaire.csv,medication_15
209,mcq230b___what_kind_of_cancer_second_mention,float64,7408,99.61,15,mcq230b_what_kind_of_cancer_second_mention,mcq230b_what_kind_of_cancer_second_mention,questionnaire,merged_questionnaire.csv,mcq230b___what_kind_of_cancer_second_mention,questionnaire,exact_header_match,95-100%,mcq230b_what_kind_of_cancer_second_mention,questionnaire,merged_questionnaire.csv,mcq230b___what_kind_of_cancer_second_mention,mcq230b_what_kind_of_cancer_second_mention,questionnaire,merged_questionnaire.csv,mcq230b___what_kind_of_cancer_second_mention
244,rhq070___age_range_at_last_menstrual_period,float64,7408,99.61,8,rhq070_age_range_at_last_menstrual_period,rhq070_age_range_at_last_menstrual_period,questionnaire,merged_questionnaire.csv,rhq070___age_range_at_last_menstrual_period,questionnaire,exact_header_match,95-100%,rhq070_age_range_at_last_menstrual_period,questionnaire,merged_questionnaire.csv,rhq070___age_range_at_last_menstrual_period,rhq070_age_range_at_last_menstrual_period,questionnaire,merged_questionnaire.csv,rhq070___age_range_at_last_menstrual_period
357,medication_14,str,7402,99.53,26,medication_14,medication_14,questionnaire,merged_questionnaire.csv,medication_14,questionnaire,exact_header_match,95-100%,medication_14,questionnaire,merged_questionnaire.csv,medication_14,medication_14,questionnaire,merged_questionnaire.csv,medication_14
356,medication_13,str,7394,99.42,30,medication_13,medication_13,questionnaire,merged_questionnaire.csv,medication_13,questionnaire,exact_header_match,95-100%,medication_13,questionnaire,merged_questionnaire.csv,medication_13,medication_13,questionnaire,merged_questionnaire.csv,medication_13
102,cdq009b___pain_in_right_chest,float64,7393,99.41,1,cdq009b_pain_in_right_chest,cdq009b_pain_in_right_chest,questionnaire,merged_questionnaire.csv,cdq009b___pain_in_right_chest,questionnaire,exact_header_match,95-100%,cdq009b_pain_in_right_chest,questionnaire,merged_questionnaire.csv,cdq009b___pain_in_right_chest,cdq009b_pain_in_right_chest,questionnaire,merged_questionnaire.csv,cdq009b___pain_in_right_chest
264,rhq542b___hormone_patches_used,float64,7386,99.31,1,rhq542b_hormone_patches_used,rhq542b_hormone_patches_used,questionnaire,merged_questionnaire.csv,rhq542b___hormone_patches_used,questionnaire,exact_header_match,95-100%,rhq542b_hormone_patches_used,questionnaire,merged_questionnaire.csv,rhq542b___hormone_patches_used,rhq542b_hormone_patches_used,questionnaire,merged_questionnaire.csv,rhq542b___hormone_patches_used
325,whd080p___started_to_smoke_or_began_to_smoke_again,float64,7385,99.30,1,whd080p_started_to_smoke_or_began_to_smoke_again,whd080p_started_to_smoke_or_began_to_smoke_again,questionnaire,merged_questionnaire.csv,whd080p___started_to_smoke_or_began_to_smoke_again,questionnaire,exact_header_match,95-100%,whd080p_started_to_smoke_or_began_to_smoke_again,questionnaire,merged_questionnaire.csv,whd080p___started_to_smoke_or_began_to_smoke_again,whd080p_started_to_smoke_or_began_to_smoke_again,questionnaire,merged_questionnaire.csv,whd080p___started_to_smoke_or_began_to_smoke_again
105,cdq009e___pain_in_lower_sternum,float64,7380,99.23,1,cdq009e_pain_in_lower_sternum,cdq009e_pain_in_lower_sternum,questionnaire,merged_questionnaire.csv,cdq009e___pain_in_lower_sternum,questionnaire,exact_header_match,95-100%,cdq009e_pain_in_lower_sternum,questionnaire,merged_questionnaire.csv,cdq009e___pain_in_lower_sternum,cdq009e_pain_in_lower_sternum,questionnaire,merged_questionnaire.csv,cdq009e___pain_in_lower_sternum
198,mcq510d___liver_condition_hepatitis,float64,7378,99.21,1,mcq510d_liver_condition_hepatitis,mcq510d_liver_condition_hepatitis,questionnaire,merged_questionnaire.csv,mcq510d___liver_condition_hepatitis,questionnaire,exact_header_match,95-100%,mcq510d_liver_condition_hepatitis,questionnaire,merged_questionnaire.csv,mcq510d___liver_condition_hepatitis,mcq510d_liver_condition_hepatitis,questionnaire,merged_questionnaire.csv,mcq510d___liver_condition_hepatitis
331,whd080l___other,float64,7377,99.19,1,whd080l_other,whd080l_other,questionnaire,merged_questionnaire.csv,whd080l___other,questionnaire,exact_header_match,95-100%,whd080l_other,questionnaire,merged_questionnaire.csv,whd080l___other,whd080l_other,questionnaire,merged_questionnaire.csv,whd080l___other
275,rxdrsc3___icd_10_cm_code_3,str,7374,99.15,29,rxdrsc3_icd_10_cm_code_3,rxdrsc3_icd_10_cm_code_3,questionnaire,merged_questionnaire.csv,rxdrsc3___icd_10_cm_code_3,questionnaire,exact_header_match,95-100%,rxdrsc3_icd_10_cm_code_3,questionnaire,merged_questionnaire.csv,rxdrsc3___icd_10_cm_code_3,rxdrsc3_icd_10_cm_code_3,questionnaire,merged_questionnaire.csv,rxdrsc3___icd_10_cm_code_3
278,rxdrsd3___icd_10_cm_code_3_description,str,7374,99.15,29,rxdrsd3_icd_10_cm_code_3_description,rxdrsd3_icd_10_cm_code_3_description,questionnaire,merged_questionnaire.csv,rxdrsd3___icd_10_cm_code_3_description,questionnaire,exact_header_match,95-100%,rxdrsd3_icd_10_cm_code_3_description,questionnaire,merged_questionnaire.csv,rxdrsd3___icd_10_cm_code_3_description,rxdrsd3_icd_10_cm_code_3_description,questionnaire,merged_questionnaire.csv,rxdrsd3___icd_10_cm_code_3_description
321,whd080k___took_laxatives_or_vomited,float64,7369,99.09,1,whd080k_took_laxatives_or_vomited,whd080k_took_laxatives_or_vomited,questionnaire,merged_questionnaire.csv,whd080k___took_laxatives_or_vomited,questionnaire,exact_header_match,95-100%,whd080k_took_laxatives_or_vomited,questionnaire,merged_questionnaire.csv,whd080k___took_laxatives_or_vomited,whd080k_took_laxatives_or_vomited,questionnaire,merged_questionnaire.csv,whd080k___took_laxatives_or_vomited
200,mcq510f___liver_condition_other,float64,7364,99.02,1,mcq510f_liver_condition_other,mcq510f_liver_condition_other,questionnaire,merged_questionnaire.csv,mcq510f___liver_condition_other,questionnaire,exact_header_match,95-100%,mcq510f_liver_condition_other,questionnaire,merged_questionnaire.csv,mcq510f___liver_condition_other,mcq510f_liver_condition_other,questionnaire,merged_questionnaire.csv,mcq510f___liver_condition_other
139,heq020___ever_prescribed_meds_treat_hepatitis_b?,float64,7364,99.02,3,heq020_ever_prescribed_meds_treat_hepatitis_b,heq020_ever_prescribed_meds_treat_hepatitis_b,questionnaire,merged_questionnaire.csv,heq020___ever_prescribed_meds_treat_hepatitis_b?,questionnaire,exact_header_match,95-100%,heq020_ever_prescribed_meds_treat_hepatitis_b,questionnaire,merged_questionnaire.csv,heq020___ever_prescribed_meds_treat_hepatitis_b?,heq020_ever_prescribed_meds_treat_hepatitis_b,questionnaire,merged_questionnaire.csv,heq020___ever_prescribed_meds_treat_hepatitis_b?
355,medication_12,str,7362,98.99,46,medication_12,medication_12,questionnaire,merged_questionnaire.csv,medication_12,questionnaire,exact_header_match,95-100%,medication_12,questionnaire,merged_questionnaire.csv,medication_12,medication_12,questionnaire,merged_questionnaire.csv,medication_12
106,cdq009f___pain_in_left_chest,float64,7343,98.74,1,cdq009f_pain_in_left_chest,cdq009f_pain_in_left_chest,questionnaire,merged_questionnaire.csv,cdq009f___pain_in_left_chest,questionnaire,exact_header_match,95-100%,cdq009f_pain_in_left_chest,questionnaire,merged_questionnaire.csv,cdq009f___pain_in_left_chest,cdq009f_pain_in_left_chest,questionnaire,merged_questionnaire.csv,cdq009f___pain_in_left_chest
354,medication_11,str,7334,98.62,49,medication_11,medication_11,questionnaire,merged_questionnaire.csv,medication_11,questionnaire,exact_header_match,95-100%,medication_11,questionnaire,merged_questionnaire.csv,medication_11,medication_11,questionnaire,merged_questionnaire.csv,medication_11
265,rhq542c___hormone_cream/suppository/injection_used,float64,7330,98.56,1,rhq542c_hormone_cream_suppository_injection_used,rhq542c_hormone_cream_suppository_injection_used,questionnaire,merged_questionnaire.csv,rhq542c___hormone_cream/suppository/injection_used,questionnaire,exact_header_match,95-100%,rhq542c_hormone_cream_suppository_injection_used,questionnaire,merged_questionnaire.csv,rhq542c___hormone_cream/suppository/injection_used,rhq542c_hormone_cream_suppository_injection_used,questionnaire,merged_questionnaire.csv,rhq542c___hormone_cream/suppository/injection_used
182,mcd180d___age_when_told_you_had_angina,float64,7328,98.53,40,mcd180d_age_when_told_you_had_angina,mcd180d_age_when_told_you_had_angina,questionnaire,merged_questionnaire.csv,mcd180d___age_when_told_you_had_angina,questionnaire,exact_header_match,95-100%,mcd180d_age_when_told_you_had_angina,questionnaire,merged_questionnaire.csv,mcd180d___age_when_told_you_had_angina,mcd180d_age_when_told_you_had_angina,questionnaire,merged_questionnaire.csv,mcd180d___age_when_told_you_had_angina
141,heq040___ever_prescribed_meds_treat_hepatitis_c?,float64,7309,98.28,3,heq040_ever_prescribed_meds_treat_hepatitis_c,heq040_ever_prescribed_meds_treat_hepatitis_c,questionnaire,merged_questionnaire.csv,heq040___ever_prescribed_meds_treat_hepatitis_c?,questionnaire,exact_header_match,95-100%,heq040_ever_prescribed_meds_treat_hepatitis_c,questionnaire,merged_questionnaire.csv,heq040___ever_prescribed_meds_treat_hepatitis_c?,heq040_ever_prescribed_meds_treat_hepatitis_c,questionnaire,merged_questionnaire.csv,heq040___ever_prescribed_meds_treat_hepatitis_c?
319,whd080i___took_prescription_diet_pills,float64,7305,98.23,1,whd080i_took_prescription_diet_pills,whd080i_took_prescription_diet_pills,questionnaire,merged_questionnaire.csv,whd080i___took_prescription_diet_pills,questionnaire,exact_header_match,95-100%,whd080i_took_prescription_diet_pills,questionnaire,merged_questionnaire.csv,whd080i___took_prescription_diet_pills,whd080i_took_prescription_diet_pills,questionnaire,merged_questionnaire.csv,whd080i___took_prescription_diet_pills
104,cdq009d___pain_in_upper_sternum,float64,7305,98.23,1,cdq009d_pain_in_upper_sternum,cdq009d_pain_in_upper_sternum,questionnaire,merged_questionnaire.csv,cdq009d___pain_in_upper_sternum,questionnaire,exact_header_match,95-100%,cdq009d_pain_in_upper_sternum,questionnaire,merged_questionnaire.csv,cdq009d___pain_in_upper_sternum,cdq009d_pain_in_upper_sternum,questionnaire,merged_questionnaire.csv,cdq009d___pain_in_upper_sternum
178,mcd180b___age_when_told_you_had_chf,float64,7288,98.00,44,mcd180b_age_when_told_you_had_chf,mcd180b_age_when_told_you_had_chf,questionnaire,merged_questionnaire.csv,mcd180b___age_when_told_you_had_chf,questionnaire,exact_header_match,95-100%,mcd180b_age_when_told_you_had_chf,questionnaire,merged_questionnaire.csv,mcd180b___age_when_told_you_had_chf,mcd180b_age_when_told_you_had_chf,questionnaire,merged_questionnaire.csv,mcd180b___age_when_told_you_had_chf

In [35]:
bins = [0, 5, 20, 50, 80, 95, 100]
labels = ["0-5%", "5-20%", "20-50%", "50-80%", "80-95%", "95-100%"]

overview["missing_bucket"] = pd.cut(
    overview["missing_pct"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

display(overview["missing_bucket"].value_counts().sort_index())

missing_bucket
0-5%       69
5-20%      79
20-50%     17
50-80%     70
80-95%     64
95-100%    72
Name: count, dtype: int64