In [83]:
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
import re
import numpy as np
import pandas as pd

from scipy.stats import chi2_contingency, pointbiserialr

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance
from sklearn.dummy import DummyClassifier

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 180)

In [84]:
DATA_PATH = Path("../data/processed/nhanes_merged_adults_final.csv")
OUTPUT_DIR = Path("../data/processed/model_outputs_prediabetes")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

TARGET = "prediabetes"
RANDOM_STATE = 42
TEST_SIZE = 0.20

print("DATA_PATH:", DATA_PATH.resolve())
print("OUTPUT_DIR:", OUTPUT_DIR.resolve())

DATA_PATH: C:\Users\Philipp\AIBootcamp\halfFull\data\processed\nhanes_merged_adults_final.csv
OUTPUT_DIR: C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes

In [85]:
[c for c in df.columns if "age" in c.lower() or "gender" in c.lower() or "sex" in c.lower()]

['age_years',
 'gender',
 'bpd035___age_told_had_hypertension',
 'did040___age_when_first_told_you_had_diabetes',
 'kiq005___how_often_have_urinary_leakage?',
 'kiq050___how_much_did_urine_leakage_bother_you?',
 'mcq025___age_when_first_had_asthma',
 'mcq151___age_in_years_at_first_menstrual_period',
 'mcd180b___age_when_told_you_had_chf',
 'mcd180c___age_when_told_you_had_chd',
 'mcd180d___age_when_told_you_had_angina',
 'mcd180e___age_when_told_you_had_heart_attack',
 'mcd180f___age_when_told_you_had_a_stroke',
 'mcd180m___age_when_told_you_had_thyroid_problem',
 'mcd180l___age_when_told_you_had_liver_condition',
 'mcq570___age_when_1st_had_gallbladder_surgery?',
 'rhq010___age_when_first_menstrual_period_occurred',
 'rhq020___age_range_at_first_menstrual_period',
 'rhq060___age_at_last_menstrual_period',
 'rhq070___age_range_at_last_menstrual_period',
 'rhd180___age_at_first_live_birth',
 'rhd190___age_at_last_live_birth',
 'rhq332___age_when_both_ovaries_removed',
 'smd030___age_started_smoking_cigarettes_regularly',
 'smd630___age_first_smoked_whole_cigarette',
 'whd120___self_reported_weight_age_25_(pounds)',
 'whd130___self_reported_height___age_25_(inches)',
 'whq150___age_when_heaviest_weight']

In [86]:
df = pd.read_csv(DATA_PATH, low_memory=False)

print("Shape:", df.shape)
print("First 10 columns:")
print(df.columns[:10].tolist())

assert TARGET in df.columns, f"{TARGET} not found in dataframe."

print(df[TARGET].value_counts(dropna=False).sort_index())
print()
print("Target prevalence:")
print(df[TARGET].value_counts(normalize=True, dropna=False).sort_index().round(4))

Shape: (7437, 878)
First 10 columns:
['SEQN', 'age_years', 'income_poverty_ratio', 'mec_exam_weight', 'interview_weight', 'survey_psu', 'survey_stratum', 'gender', 'ethnicity', 'education']
prediabetes
0    6755
1     682
Name: count, dtype: int64

Target prevalence:
prediabetes
0    0.9083
1    0.0917
Name: proportion, dtype: float64

# Sleeping Features

In [87]:
SLEEP_COLS = [
    "sld012___sleep_hours___weekdays_or_workdays",
    "sld013___sleep_hours___weekends",
    "slq300___usual_sleep_time_on_weekdays_or_workdays",
    "slq310___usual_wake_time_on_weekdays_or_workdays",
    "slq320___usual_sleep_time_on_weekends",
    "slq330___usual_wake_time_on_weekends",
    "slq030___how_often_do_you_snore?",
]

sleep_df = df[SLEEP_COLS].copy()
sleep_df.head()

,sld012___sleep_hours___weekdays_or_workdays,sld013___sleep_hours___weekends,slq300___usual_sleep_time_on_weekdays_or_workdays,slq310___usual_wake_time_on_weekdays_or_workdays,slq320___usual_sleep_time_on_weekends,slq330___usual_wake_time_on_weekends,slq030___how_often_do_you_snore?
0,7.5,8.0,22:00,05:30,23:00,07:00,1.0
1,8.0,8.0,00:00,08:00,03:00,11:00,0.0
2,8.5,8.0,22:00,06:30,23:00,07:00,0.0
3,10.0,13.0,23:00,09:00,23:00,12:00,0.0
4,6.5,8.0,08:00,14:35,21:00,05:00,0.0

In [88]:
sleep_overview = pd.DataFrame({
    "feature": sleep_df.columns,
    "dtype": sleep_df.dtypes.astype(str).values,
    "missing_pct": (sleep_df.isna().mean() * 100).round(2).values,
    "n_unique": [sleep_df[c].nunique(dropna=True) for c in sleep_df.columns]
}).sort_values("missing_pct", ascending=False)

sleep_overview

                                             feature    dtype  missing_pct  n_unique
1                    sld013___sleep_hours___weekends  float64         0.86        24
0        sld012___sleep_hours___weekdays_or_workdays  float64         0.71        24
2  slq300___usual_sleep_time_on_weekdays_or_workdays      str         0.65        65
3   slq310___usual_wake_time_on_weekdays_or_workdays      str         0.62       113
4              slq320___usual_sleep_time_on_weekends      str         0.59        59
5               slq330___usual_wake_time_on_weekends      str         0.58        70
6                   slq030___how_often_do_you_snore?  float64         0.00         6

In [89]:
def get_example_values(series, n=10):
    vals = series.dropna().unique()[:n]
    return list(vals)

sleep_examples = pd.DataFrame({
    "feature": sleep_df.columns,
    "example_values": [get_example_values(sleep_df[c], n=10) for c in sleep_df.columns]
})

sleep_examples

                                             feature                                     example_values
0        sld012___sleep_hours___weekdays_or_workdays  [7.5, 8.0, 8.5, 10.0, 6.5, 9.5, 11.0, 4.5, 7.0...
1                    sld013___sleep_hours___weekends  [8.0, 13.0, 10.0, 9.0, 4.5, 6.5, 7.0, 14.0, 11...
2  slq300___usual_sleep_time_on_weekdays_or_workdays  [22:00, 00:00, 23:00, 08:00, 01:00, 21:00, 18:...
3   slq310___usual_wake_time_on_weekdays_or_workdays  [05:30, 08:00, 06:30, 09:00, 14:35, 10:30, 06:...
4              slq320___usual_sleep_time_on_weekends  [23:00, 03:00, 21:00, 22:00, 00:00, 02:00, 01:...
5               slq330___usual_wake_time_on_weekends  [07:00, 11:00, 12:00, 05:00, 08:00, 09:00, 01:...
6                   slq030___how_often_do_you_snore?                     [1.0, 0.0, 2.0, 3.0, 9.0, 7.0]

In [90]:
for col in [
    "sld012___sleep_hours___weekdays_or_workdays",
    "sld013___sleep_hours___weekends",
]:
    print("\n" + "=" * 80)
    print(col)
    print(sleep_df[col].value_counts(dropna=False).sort_index().head(50))

================================================================================
sld012___sleep_hours___weekdays_or_workdays
sld012___sleep_hours___weekdays_or_workdays
2.0       38
3.0       51
3.5       32
4.0      148
4.5       67
5.0      294
5.5      182
6.0      647
6.5      508
7.0     1283
7.5      723
8.0     1328
8.5      476
9.0      790
9.5      180
10.0     314
10.5      58
11.0     151
11.5      17
12.0      55
12.5       3
13.0      19
13.5       3
14.0      17
NaN       53
Name: count, dtype: int64

================================================================================
sld013___sleep_hours___weekends
sld013___sleep_hours___weekends
2.0       19
3.0       29
3.5       19
4.0       85
4.5       39
5.0      215
5.5       70
6.0      436
6.5      190
7.0      867
7.5      349
8.0     1391
8.5      433
9.0     1359
9.5      259
10.0     800
10.5     100
11.0     391
11.5      32
12.0     158
12.5      18
13.0      66
13.5       4
14.0      44
NaN       64
Name: count, dtype: int64

In [91]:
sleep_df[[
    "sld012___sleep_hours___weekdays_or_workdays",
    "sld013___sleep_hours___weekends",
]].describe()

       sld012___sleep_hours___weekdays_or_workdays  sld013___sleep_hours___weekends
count                                  7384.000000                      7373.000000
mean                                      7.531352                         8.351078
std                                       1.664477                         1.813858
min                                       2.000000                         2.000000
25%                                       6.500000                         7.000000
50%                                       7.500000                         8.000000
75%                                       8.500000                         9.500000
max                                      14.000000                        14.000000

In [92]:
sleep_duration_compare = pd.DataFrame({
    "weekday_sleep_hours": sleep_df["sld012___sleep_hours___weekdays_or_workdays"],
    "weekend_sleep_hours": sleep_df["sld013___sleep_hours___weekends"],
})

sleep_duration_compare["weekend_minus_weekday"] = (
    sleep_duration_compare["weekend_sleep_hours"] - sleep_duration_compare["weekday_sleep_hours"]
)

sleep_duration_compare.describe()

       weekday_sleep_hours  weekend_sleep_hours  weekend_minus_weekday
count          7384.000000          7373.000000            7354.000000
mean              7.531352             8.351078               0.820914
std               1.664477             1.813858               1.736213
min               2.000000             2.000000              -9.000000
25%               6.500000             7.000000               0.000000
50%               7.500000             8.000000               0.500000
75%               8.500000             9.500000               2.000000
max              14.000000            14.000000              10.000000

In [93]:
time_cols = [
    "slq300___usual_sleep_time_on_weekdays_or_workdays",
    "slq310___usual_wake_time_on_weekdays_or_workdays",
    "slq320___usual_sleep_time_on_weekends",
    "slq330___usual_wake_time_on_weekends",
]

for col in time_cols:
    print("\n" + "=" * 80)
    print(col)
    print(sleep_df[col].value_counts(dropna=False).head(30))

================================================================================
slq300___usual_sleep_time_on_weekdays_or_workdays
slq300___usual_sleep_time_on_weekdays_or_workdays
23:00    1507
22:00    1446
00:00     959
21:00     669
22:30     473
01:00     396
23:30     308
02:00     281
21:30     275
20:00     208
03:00     129
20:30      80
00:30      74
04:00      61
NaN        48
99999      46
01:30      43
19:00      38
08:00      37
09:00      35
05:00      32
10:00      29
02:30      26
06:00      25
18:00      21
19:30      20
07:00      19
08:30      12
11:00      12
12:00      11
Name: count, dtype: int64

================================================================================
slq310___usual_wake_time_on_weekdays_or_workdays
slq310___usual_wake_time_on_weekdays_or_workdays
06:00    1277
07:00     957
05:00     842
06:30     576
08:00     537
05:30     483
09:00     323
04:00     297
07:30     266
10:00     237
04:30     226
08:30     110
03:00     106
11:00     105
12:00      91
05:45      74
06:15      61
06:45      58
03:30      57
09:30      49
NaN        46
05:15      38
15:00      37
02:00      35
13:00      34
14:00      34
04:45      33
10:30      28
99999      26
16:00      25
Name: count, dtype: int64

================================================================================
slq320___usual_sleep_time_on_weekends
slq320___usual_sleep_time_on_weekends
00:00    1529
23:00    1452
22:00    1067
01:00     710
02:00     520
21:00     405
23:30     291
03:00     275
22:30     262
21:30     129
20:00     118
00:30     115
04:00     112
05:00      58
01:30      55
99999      48
NaN        44
02:30      34
20:30      33
19:00      21
06:00      20
18:00      13
19:30      11
03:30      10
07:00       8
12:00       8
10:00       8
08:00       7
09:00       6
04:30       6
Name: count, dtype: int64

================================================================================
slq330___usual_wake_time_on_weekends
slq330___usual_wake_time_on_weekends
08:00    1280
07:00    1198
09:00     984
06:00     741
10:00     683
05:00     347
11:00     298
07:30     298
06:30     237
12:00     236
08:30     197
04:00     121
05:30     119
09:30     116
13:00      79
10:30      59
04:30      58
14:00      52
NaN        43
03:00      42
99999      34
15:00      22
11:30      15
06:45      14
16:00      14
02:00      13
03:30      10
02:30       8
18:00       8
01:00       7
Name: count, dtype: int64

In [94]:
import re

def is_hhmm(x):
    if pd.isna(x):
        return True
    x = str(x).strip()
    return bool(re.match(r"^\d{1,2}:\d{2}$", x))

time_format_check = pd.DataFrame({
    "feature": time_cols,
    "invalid_format_n": [sleep_df[~sleep_df[c].apply(is_hhmm)][c].notna().sum() for c in time_cols],
    "invalid_examples": [
        sleep_df.loc[~sleep_df[c].apply(is_hhmm), c].dropna().astype(str).unique()[:10].tolist()
        for c in time_cols
    ]
})

time_format_check

                                             feature  invalid_format_n invalid_examples
0  slq300___usual_sleep_time_on_weekdays_or_workdays                48   [99999, 77777]
1   slq310___usual_wake_time_on_weekdays_or_workdays                26          [99999]
2              slq320___usual_sleep_time_on_weekends                49   [99999, 77777]
3               slq330___usual_wake_time_on_weekends                36   [99999, 77777]

In [95]:
import numpy as np

# -------------------------
# Clean invalid NHANES codes
# -------------------------

TIME_COLS = [
    "slq300___usual_sleep_time_on_weekdays_or_workdays",
    "slq310___usual_wake_time_on_weekdays_or_workdays",
    "slq320___usual_sleep_time_on_weekends",
    "slq330___usual_wake_time_on_weekends",
]

for col in TIME_COLS:
    df[col] = df[col].replace(["77777", "99999", 77777, 99999], np.nan)

# -------------------------
# Convert HH:MM → minutes
# -------------------------

def hhmm_to_minutes(x):

    if pd.isna(x):
        return np.nan

    try:
        h, m = str(x).split(":")
        return int(h)*60 + int(m)
    except:
        return np.nan


df["weekday_bedtime_min"] = df[
    "slq300___usual_sleep_time_on_weekdays_or_workdays"
].apply(hhmm_to_minutes)

df["weekday_waketime_min"] = df[
    "slq310___usual_wake_time_on_weekdays_or_workdays"
].apply(hhmm_to_minutes)


# -------------------------
# Circular encoding
# -------------------------

def circular_encode(series, period=1440):

    radians = 2 * np.pi * series / period

    return np.sin(radians), np.cos(radians)


df["sin_weekday_bedtime"], df["cos_weekday_bedtime"] = circular_encode(
    df["weekday_bedtime_min"]
)

df["sin_weekday_wake"], df["cos_weekday_wake"] = circular_encode(
    df["weekday_waketime_min"]
)


# -------------------------
# Sleep duration
# -------------------------

df["sleep_hours_weekday"] = df[
    "sld012___sleep_hours___weekdays_or_workdays"
]

df["sleep_hours_weekend"] = df[
    "sld013___sleep_hours___weekends"
]


# -------------------------
# Social jetlag
# -------------------------

df["social_jetlag"] = (
    df["sleep_hours_weekend"] -
    df["sleep_hours_weekday"]
)

# Broad Model

In [96]:
overview = pd.DataFrame({
    "feature": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "missing_pct": df.isna().mean().values * 100,
    "n_unique": [df[c].nunique(dropna=True) for c in df.columns]
}).sort_values(["missing_pct", "n_unique"], ascending=[False, True])

overview.head(30)

                                               feature    dtype  missing_pct  n_unique
166            mcq149___menstrual_periods_started_yet?  float64   100.000000         0
167    mcq151___age_in_years_at_first_menstrual_period  float64   100.000000         0
294          smq621___cigarettes_smoked_in_entire_life  float64   100.000000         0
295          smd630___age_first_smoked_whole_cigarette  float64   100.000000         0
434                     LBXIGG_cytomegalovirus_cmv_igg  float64   100.000000         0
435                     LBXIGM_cytomegalovirus_cmv_igm  float64   100.000000         0
436            LBXIGGA_cytomegalovirus_cmv_igg_avidity  float64   100.000000         0
357                                      medication_21      str    99.973107         2
358                                      medication_22      str    99.973107         2
356                                      medication_20      str    99.959661         3
203        mcq230c___what_kind_of_cancer_third_mention  float64    99.932769         4
355                                      medication_19      str    99.932769         5
189  mcq510b___liver_condition_non_alcoholic_fatty_...  float64    99.919322         1
354                                      medication_18      str    99.905876         7
100                         cdq009g___pain_in_left_arm  float64    99.852091         1
96                              cdq009c___pain_in_neck  float64    99.838645         1
353                                      medication_17      str    99.838645        12
192               mcq510e___liver_condition_autoimmune  float64    99.825198         1
94                         cdq009a___pain_in_right_arm  float64    99.811752         1
352                                      medication_16      str    99.757967        18
190  mcq510c___liver_condition_alcoholic_liver_disease  float64    99.704182         1
233       rhq020___age_range_at_first_menstrual_period  float64    99.677289         5
323   whd080u___had_weight_loss_surgery_to_lose_weight  float64    99.663843         1
351                                      medication_15      str    99.663843        23
237        rhq070___age_range_at_last_menstrual_period  float64    99.610058         8
202       mcq230b___what_kind_of_cancer_second_mention  float64    99.610058        15
684               URDTIME3_minutes_b_w_urine_2_urine_3  float64    99.610058        25
682        URXVOL3_the_volume_of_urine_collection_3_ml  float64    99.610058        26
683                  URDFLOW3_urine_3_flow_rate_ml_min  float64    99.610058        29
350                                      medication_14      str    99.529380        26

In [97]:
LEAKAGE_COLS = [
    TARGET,
    "diabetes",
    "diq010___doctor_told_you_have_diabetes",
    "diq160___ever_told_you_have_prediabetes",
    "rxd_disease_list",
]

QUESTIONNAIRE_PREFIXES = (
    "slq", "sld", "dpq", "paq", "huq", "mcq", "bpq", "kiq", "cdq", "smq", "alq",
    "whq", "rhq"
)

ALWAYS_INCLUDE_COLS = [
    "age_years",
    "gender",
    "med_count"
    "fasting_glucose_mg_dl",
    "triglycerides_mg_dl",
    "hdl_cholesterol_mg_dl",
    "total_cholesterol_mg_dl",
    "uacr_mg_g",

]

EXCLUDE_PATTERNS = [
    r"^seqn$",
    r"cluster",
    r"stratum",
    r"weight",
    r"sample_weight",
    r"survey_",
    r"^rxd",
    r"medication",
    r"drug",
    r"icd",
    r"diagnosis",
    r"lab",
    r"exam",
    r"fasting",
    r"liver_",
    r"bmi$",
    r"waist",
    r"hip",
    r"height",
    r"weight_kg",
    r"cholesterol",
    r"creatin",
    r"ferritin",
    r"vitamin",
    r"iron",
    r"protein",
    r"carbs",
    r"fat$",
    r"calories",
    r"pulse_",
    r"fatigue_binary",
    r"fatigue_score",
    r"glucose",
    r"insulin",
    r"hba1c",
    r"a1c",
    r"glyco",
]

MANUAL_DROP_COLS = [
    # bei Bedarf später ergänzen
]

In [98]:
def has_allowed_prefix(col: str, prefixes=QUESTIONNAIRE_PREFIXES) -> bool:
    col_low = col.lower()
    return col_low.startswith(prefixes)

def matches_any_pattern(col: str, patterns) -> bool:
    col_low = col.lower()
    return any(re.search(p, col_low) for p in patterns)

def is_binary_series(s: pd.Series) -> bool:
    vals = set(pd.Series(s.dropna()).unique())
    return vals.issubset({0, 1}) and len(vals) <= 2

def get_example_values(s: pd.Series, n=5):
    vals = s.dropna().unique()[:n]
    return list(vals)

def cramers_v(x: pd.Series, y: pd.Series) -> float:
    table = pd.crosstab(x, y)
    if table.shape[0] < 2 or table.shape[1] < 2:
        return np.nan
    chi2 = chi2_contingency(table)[0]
    n = table.values.sum()
    r, k = table.shape
    denom = min(k - 1, r - 1)
    if denom == 0 or n == 0:
        return np.nan
    return np.sqrt((chi2 / n) / denom)

def safe_pointbiserial(x: pd.Series, y: pd.Series):
    valid = x.notna() & y.notna()
    if valid.sum() < 30:
        return np.nan, np.nan
    try:
        r, p = pointbiserialr(x[valid], y[valid])
        return r, p
    except Exception:
        return np.nan, np.nan

def infer_feature_type(series: pd.Series) -> str:
    if pd.api.types.is_numeric_dtype(series):
        nunique = series.nunique(dropna=True)
        if nunique <= 10:
            return "categorical"
        return "numeric"
    return "categorical"

In [99]:
candidate_cols = []

for col in df.columns:
    if col == TARGET:
        continue
    if col in LEAKAGE_COLS:
        continue
    if col in MANUAL_DROP_COLS:
        continue
    if matches_any_pattern(col, EXCLUDE_PATTERNS):
        continue

    if col in ALWAYS_INCLUDE_COLS:
        candidate_cols.append(col)
        continue

    if not has_allowed_prefix(col):
        continue

    candidate_cols.append(col)

print("Number of initial candidate questionnaire features:", len(candidate_cols))
print(candidate_cols[:80])

Number of initial candidate questionnaire features: 142
['age_years', 'gender', 'triglycerides_mg_dl', 'uacr_mg_g', 'alq111___ever_had_a_drink_of_any_kind_of_alcohol', 'alq121___past_12_mo_how_often_drink_alcoholic_bev', 'alq130___avg_#_alcoholic_drinks/day___past_12_mos', 'alq142___#_days_have_4_or_5_drinks/past_12_mos', 'alq270___#_times_4_5_drinks_in_2hrs/past_12_mos', 'alq280___#_times_8+_drinks_in_1_day/past_12_mos', 'alq290___#_times_12+_drinks_in_1_day/past_12_mos', 'alq151___ever_have_4/5_or_more_drinks_every_day?', 'alq170___past_30_days_#_times_4_5_drinks_on_an_oc', 'bpq020___ever_told_you_had_high_blood_pressure', 'bpq030___told_had_high_blood_pressure___2+_times', 'bpq040a___taking_prescription_for_hypertension', 'bpq050a___now_taking_prescribed_medicine_for_hbp', 'bpq100d___now_taking_prescribed_medicine', 'cdq001___sp_ever_had_pain_or_discomfort_in_chest', 'cdq002___sp_get_it_walking_uphill_or_in_a_hurry', 'cdq003___during_an_ordinary_pace_on_level_ground', 'cdq004___if_so_does_sp_continue_or_slow_down', 'cdq005___does_standing_relieve_pain/discomfort', 'cdq006___how_soon_is_the_pain_relieved', 'cdq009a___pain_in_right_arm', 'cdq009b___pain_in_right_chest', 'cdq009c___pain_in_neck', 'cdq009d___pain_in_upper_sternum', 'cdq009e___pain_in_lower_sternum', 'cdq009f___pain_in_left_chest', 'cdq009g___pain_in_left_arm', 'cdq008___severe_pain_in_chest_more_than_half_hour', 'cdq010___shortness_of_breath_on_stairs/inclines', 'dpq040___feeling_tired_or_having_little_energy', 'huq010___general_health_condition', 'huq030___routine_place_to_go_for_healthcare', 'huq051___#times_receive_healthcare_over_past_year', 'huq071___overnight_hospital_patient_in_last_year', 'huq090___seen_mental_health_professional/past_yr', 'kiq022___ever_told_you_had_weak/failing_kidneys?', 'kiq025___received_dialysis_in_past_12_months?', 'kiq026___ever_had_kidney_stones?', 'kiq029___pass_kidney_stone_in_past_12_months?', 'kiq005___how_often_have_urinary_leakage?', 'kiq010___how_much_urine_lose_each_time?', 'kiq042___leak_urine_during_physical_activities?', 'kiq430___how_frequently_does_this_occur?', 'kiq044___urinated_before_reaching_the_toilet?', 'kiq450___how_frequently_does_this_occur?', 'kiq046___leak_urine_during_nonphysical_activities', 'kiq470___how_frequently_does_this_occur?', 'kiq050___how_much_did_urine_leakage_bother_you?', 'kiq052___how_much_were_daily_activities_affected?', 'kiq480___how_many_times_urinate_in_night?', 'mcq010___ever_been_told_you_have_asthma', 'mcq025___age_when_first_had_asthma', 'mcq035___still_have_asthma', 'mcq040___had_asthma_attack_in_past_year', 'mcq050___emergency_care_visit_for_asthma/past_yr', 'mcq053___taking_treatment_for_anemia/past_3_mos', 'mcq092___ever_receive_blood_transfusion', 'mcq149___menstrual_periods_started_yet?', 'mcq151___age_in_years_at_first_menstrual_period', 'mcq160a___ever_told_you_had_arthritis', 'mcq195___which_type_of_arthritis_was_it?', 'mcq160b___ever_told_you_had_congestive_heart_failure', 'mcq160c___ever_told_you_had_coronary_heart_disease', 'mcq160d___ever_told_you_had_angina', 'mcq160e___ever_told_you_had_heart_attack', 'mcq160f___ever_told_you_had_stroke', 'mcq160m___ever_told_you_had_thyroid_problem', 'mcq170m___still_have_thyroid_problem', 'mcq160p___ever_told_you_had_copd_emphysema', 'mcq520___abdominal_pain_during_past_12_months?', 'mcq530___where_was_the_most_uncomfortable_pain', 'mcq540___ever_seen_a_dr_about_this_pain', 'mcq550___has_dr_ever_said_you_have_gallstones', 'mcq560___ever_had_gallbladder_surgery?', 'mcq570___age_when_1st_had_gallbladder_surgery?', 'mcq220___ever_told_you_had_cancer_or_malignancy']

In [101]:
audit_rows = []

for col in candidate_cols:
    s = df[col]
    audit_rows.append({
        "feature": col,
        "dtype": str(s.dtype),
        "missing_pct": round(s.isna().mean() * 100, 2),
        "n_unique": s.nunique(dropna=True),
        "example_values": str(get_example_values(s, n=5)),
        "is_binary_like": is_binary_series(s),
        "keep_for_model": True,
        "drop_reason": ""
    })

audit_df = pd.DataFrame(audit_rows).sort_values(
    ["missing_pct", "n_unique", "feature"],
    ascending=[False, True, True]
)

audit_df.head(100)

,feature,dtype,missing_pct,n_unique,example_values,is_binary_like,keep_for_model,drop_reason
61,mcq149___menstrual_periods_started_yet?,float64,100.00,0,[],True,True,
62,mcq151___age_in_years_at_first_menstrual_period,float64,100.00,0,[],True,True,
140,smq621___cigarettes_smoked_in_entire_life,float64,100.00,0,[],True,True,
82,mcq230c___what_kind_of_cancer_third_mention,float64,99.93,4,"[np.float64(20.0), np.float64(23.0), np.float6...",False,True,
30,cdq009g___pain_in_left_arm,float64,99.85,1,[np.float64(7.0)],False,True,
26,cdq009c___pain_in_neck,float64,99.84,1,[np.float64(3.0)],False,True,
24,cdq009a___pain_in_right_arm,float64,99.81,1,[np.float64(1.0)],True,True,
103,rhq020___age_range_at_first_menstrual_period,float64,99.68,5,"[np.float64(9.0), np.float64(3.0), np.float64(...",False,True,
106,rhq070___age_range_at_last_menstrual_period,float64,99.61,8,"[np.float64(99.0), np.float64(3.0), np.float64...",False,True,
81,mcq230b___what_kind_of_cancer_second_mention,float64,99.61,15,"[np.float64(37.0), np.float64(16.0), np.float6...",False,True,
25,cdq009b___pain_in_right_chest,float64,99.41,1,[np.float64(2.0)],False,True,
121,rhq542b___hormone_patches_used,float64,99.31,1,[np.float64(11.0)],False,True,
28,cdq009e___pain_in_lower_sternum,float64,99.23,1,[np.float64(5.0)],False,True,
29,cdq009f___pain_in_left_chest,float64,98.74,1,[np.float64(6.0)],False,True,
122,rhq542c___hormone_cream/suppository/injection_...,float64,98.56,1,[np.float64(12.0)],False,True,
27,cdq009d___pain_in_upper_sternum,float64,98.23,1,[np.float64(4.0)],False,True,
40,kiq025___received_dialysis_in_past_12_months?,float64,97.50,2,"[np.float64(2.0), np.float64(1.0)]",False,True,
120,rhq542a___hormone_pills_used,float64,97.03,1,[np.float64(10.0)],False,True,
123,rhq554___use_hormone_pills_w/estrogen_only,float64,97.03,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
124,rhq570___used_estrogen/progestin_combo_pills,float64,97.03,3,"[np.float64(2.0), np.float64(9.0), np.float64(...",False,True,
116,rhq200___now_breastfeeding_a_child?,float64,96.84,2,"[np.float64(2.0), np.float64(1.0)]",False,True,
115,rhq197___how_many_months_ago_have_baby?,float64,96.81,24,"[np.float64(16.0), np.float64(19.0), np.float6...",False,True,
118,rhq332___age_when_both_ovaries_removed,float64,96.72,41,"[np.float64(53.0), np.float64(45.0), np.float6...",False,True,
23,cdq006___how_soon_is_the_pain_relieved,float64,96.18,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
22,cdq005___does_standing_relieve_pain/discomfort,float64,95.37,3,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
21,cdq004___if_so_does_sp_continue_or_slow_down,float64,94.82,2,"[np.float64(1.0), np.float64(2.0)]",False,True,
50,kiq470___how_frequently_does_this_occur?,float64,94.63,4,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
20,cdq003___during_an_ordinary_pace_on_level_ground,float64,94.55,2,"[np.float64(2.0), np.float64(1.0)]",False,True,
80,mcq230a___what_kind_of_cancer_first_mention,float64,94.54,28,"[np.float64(14.0), np.float64(30.0), np.float6...",False,True,
78,mcq570___age_when_1st_had_gallbladder_surgery?,float64,92.15,51,"[np.float64(35.0), np.float64(31.0), np.float6...",False,True,
42,kiq029___pass_kidney_stone_in_past_12_months?,float64,91.93,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
71,mcq170m___still_have_thyroid_problem,float64,91.42,3,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
58,mcq050___emergency_care_visit_for_asthma/past_yr,float64,90.13,2,"[np.float64(2.0), np.float64(1.0)]",False,True,
57,mcq040___had_asthma_attack_in_past_year,float64,90.13,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
10,alq290___#_times_12+_drinks_in_1_day/past_12_mos,float64,88.14,12,"[np.float64(0.0), np.float64(8.0), np.float64(...",False,True,
138,smq078___how_soon_after_waking_do_you_smoke,float64,85.16,8,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
31,cdq008___severe_pain_in_chest_more_than_half_hour,float64,83.81,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
19,cdq002___sp_get_it_walking_uphill_or_in_a_hurry,float64,83.81,4,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
56,mcq035___still_have_asthma,float64,83.19,4,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
55,mcq025___age_when_first_had_asthma,float64,83.19,64,"[np.float64(9.0), np.float64(52.0), np.float64...",False,True,
48,kiq450___how_frequently_does_this_occur?,float64,82.73,5,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
137,smq050u___unit_of_measure_(day/week/month/year),float64,82.37,4,"[np.float64(3.0), np.float64(4.0), np.float64(...",False,True,
136,smq050q___how_long_since_quit_smoking_cigarettes,float64,82.32,50,"[np.float64(8.0), np.float64(1.0), np.float64(...",False,True,
105,rhq060___age_at_last_menstrual_period,float64,81.34,44,"[np.float64(50.0), np.float64(52.0), np.float6...",False,True,
46,kiq430___how_frequently_does_this_occur?,float64,81.05,5,"[np.float64(1.0), np.float64(3.0), np.float64(...",False,True,
17,bpq100d___now_taking_prescribed_medicine,float64,80.99,3,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
139,smq670___tried_to_quit_smoking,float64,80.26,2,"[np.float64(1.0), np.float64(2.0)]",False,True,
75,mcq540___ever_seen_a_dr_about_this_pain,float64,79.39,3,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
74,mcq530___where_was_the_most_uncomfortable_pain,float64,79.39,4,"[np.float64(3.0), np.float64(2.0), np.float64(...",False,True,
64,mcq195___which_type_of_arthritis_was_it?,float64,79.14,6,"[np.float64(3.0), np.float64(4.0), np.float64(...",False,True,
44,kiq010___how_much_urine_lose_each_time?,float64,75.50,4,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
16,bpq050a___now_taking_prescribed_medicine_for_hbp,float64,74.94,2,"[np.float64(1.0), np.float64(2.0)]",False,True,
97,paq640___number_of_days_walk_or_bicycle,float64,74.33,8,"[np.float64(4.0), np.float64(5.0), np.float64(...",False,True,
93,paq610___number_of_days_vigorous_work,float64,72.00,8,"[np.float64(5.0), np.float64(3.0), np.float64(...",False,True,
14,bpq030___told_had_high_blood_pressure___2+_times,float64,71.36,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
15,bpq040a___taking_prescription_for_hypertension,float64,71.36,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
99,paq655___days_vigorous_recreational_activities,float64,70.20,8,"[np.float64(5.0), np.float64(6.0), np.float64(...",False,True,
51,kiq050___how_much_did_urine_leakage_bother_you?,float64,69.97,5,"[np.float64(3.0), np.float64(1.0), np.float64(...",False,True,
52,kiq052___how_much_were_daily_activities_affected?,float64,69.97,5,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
8,alq270___#_times_4_5_drinks_in_2hrs/past_12_mos,float64,69.32,13,"[np.float64(0.0), np.float64(10.0), np.float64...",False,True,
9,alq280___#_times_8+_drinks_in_1_day/past_12_mos,float64,69.32,13,"[np.float64(0.0), np.float64(10.0), np.float64...",False,True,
114,rhq172___any_babies_weigh_9_lbs_or_more?,float64,67.47,4,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
113,rhq171___how_many_deliveries_live_birth_result?,float64,67.47,7,"[np.float64(4.0), np.float64(3.0), np.float64(...",False,True,
112,"rhq162___during_pregnancy,_told_you_have_diabetes",float64,65.35,5,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
111,rhq160___how_many_times_have_been_pregnant?,float64,65.34,12,"[np.float64(5.0), np.float64(6.0), np.float64(...",False,True,
135,smq040___do_you_now_smoke_cigarettes?,float64,62.58,3,"[np.float64(1.0), np.float64(3.0), np.float64(...",False,True,
107,rhq074___tried_for_a_year_to_become_pregnant?,float64,61.87,4,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
108,rhq076___seen_a_dr_b/c_unable_to_become_pregnant?,float64,61.87,4,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
109,rhq078___ever_treated_for_a_pelvic_infection/pid?,float64,61.87,4,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
117,rhq305___had_both_ovaries_removed?,float64,57.82,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
101,paq670___days_moderate_recreational_activities,float64,57.70,8,"[np.float64(4.0), np.float64(5.0), np.float64(...",False,True,
119,rhq540___ever_use_female_hormones?,float64,57.59,4,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
110,rhq131___ever_been_pregnant?,float64,57.56,4,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
2,triglycerides_mg_dl,float64,57.31,336,"[np.float64(84.0), np.float64(192.0), np.float...",False,True,
104,rhq031___had_regular_periods_in_past_12_months,float64,55.08,4,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
102,rhq010___age_when_first_menstrual_period_occurred,float64,55.06,18,"[np.float64(13.0), np.float64(9.0), np.float64...",False,True,
95,paq625___number_of_days_moderate_work,float64,54.20,8,"[np.float64(5.0), np.float64(2.0), np.float64(...",False,True,
18,cdq001___sp_ever_had_pain_or_discomfort_in_chest,float64,43.83,3,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
32,cdq010___shortness_of_breath_on_stairs/inclines,float64,43.83,3,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
12,alq170___past_30_days_#_times_4_5_drinks_on_an_oc,float64,35.35,23,"[np.float64(0.0), np.float64(30.0), np.float64...",False,True,
7,alq142___#_days_have_4_or_5_drinks/past_12_mos,float64,34.89,13,"[np.float64(0.0), np.float64(4.0), np.float64(...",False,True,
6,alq130___avg_#_alcoholic_drinks/day___past_12_mos,float64,34.89,15,"[np.float64(1.0), np.float64(6.0), np.float64(...",False,True,
11,alq151___ever_have_4/5_or_more_drinks_every_day?,float64,21.69,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
5,alq121___past_12_mo_how_often_drink_alcoholic_bev,float64,21.68,13,"[np.float64(10.0), np.float64(0.0), np.float64...",False,True,
49,kiq046___leak_urine_during_nonphysical_activities,float64,18.14,4,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
53,kiq480___how_many_times_urinate_in_night?,float64,18.14,8,"[np.float64(0.0), np.float64(2.0), np.float64(...",False,True,
47,kiq044___urinated_before_reaching_the_toilet?,float64,18.13,4,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
45,kiq042___leak_urine_during_physical_activities?,float64,18.11,4,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
43,kiq005___how_often_have_urinary_leakage?,float64,18.10,7,"[np.float64(1.0), np.float64(2.0), np.float64(...",False,True,
33,dpq040___feeling_tired_or_having_little_energy,float64,13.03,6,"[np.float64(0.0), np.float64(2.0), np.float64(...",False,True,
4,alq111___ever_had_a_drink_of_any_kind_of_alcohol,float64,12.75,2,"[np.float64(1.0), np.float64(2.0)]",False,True,
3,uacr_mg_g,float64,8.82,2352,"[np.float64(15.28), np.float64(7.5), np.float6...",False,True,
39,kiq022___ever_told_you_had_weak/failing_kidneys?,float64,6.20,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
41,kiq026___ever_had_kidney_stones?,float64,6.20,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
63,mcq160a___ever_told_you_had_arthritis,float64,6.20,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
65,mcq160b___ever_told_you_had_congestive_heart_f...,float64,6.20,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
66,mcq160c___ever_told_you_had_coronary_heart_dis...,float64,6.20,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
67,mcq160d___ever_told_you_had_angina,float64,6.20,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
68,mcq160e___ever_told_you_had_heart_attack,float64,6.20,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,
69,mcq160f___ever_told_you_had_stroke,float64,6.20,3,"[np.float64(2.0), np.float64(1.0), np.float64(...",False,True,

In [102]:
MAX_MISSING_PCT = 60.0
MIN_NON_NULL = 500
MIN_VARIANCE_UNIQUE = 2

filtered_audit_df = audit_df.copy()

filtered_audit_df.loc[filtered_audit_df["missing_pct"] > MAX_MISSING_PCT, "keep_for_model"] = False
filtered_audit_df.loc[filtered_audit_df["missing_pct"] > MAX_MISSING_PCT, "drop_reason"] = "too_missing"

for idx, row in filtered_audit_df.iterrows():
    col = row["feature"]
    non_null = df[col].notna().sum()
    if non_null < MIN_NON_NULL:
        filtered_audit_df.at[idx, "keep_for_model"] = False
        filtered_audit_df.at[idx, "drop_reason"] = "too_few_non_null"
    elif row["n_unique"] < MIN_VARIANCE_UNIQUE:
        filtered_audit_df.at[idx, "keep_for_model"] = False
        filtered_audit_df.at[idx, "drop_reason"] = "constant_or_near_constant"

filtered_audit_df["keep_for_model"].value_counts()

keep_for_model
True     73
False    69
Name: count, dtype: int64

In [103]:
MANUAL_DROP_AFTER_AUDIT = [
    # Beispiele, je nach Audit:
    # "huq051___#times_receive_healthcare_over_past_year",
    # "mcq366b___doctor_told_to_increase_exercise",
    # "mcq366c___doctor_told_to_reduce_salt",
    # "mcq366d___doctor_told_to_reduce_fat_in_diet",
]

filtered_audit_df.loc[
    filtered_audit_df["feature"].isin(MANUAL_DROP_AFTER_AUDIT),
    ["keep_for_model", "drop_reason"]
] = [False, "manual_drop"]

final_features = filtered_audit_df.loc[filtered_audit_df["keep_for_model"], "feature"].tolist()

print("Final feature count:", len(final_features))
print(final_features[:80])

Final feature count: 73
['rhq305___had_both_ovaries_removed?', 'paq670___days_moderate_recreational_activities', 'rhq540___ever_use_female_hormones?', 'rhq131___ever_been_pregnant?', 'triglycerides_mg_dl', 'rhq031___had_regular_periods_in_past_12_months', 'rhq010___age_when_first_menstrual_period_occurred', 'paq625___number_of_days_moderate_work', 'cdq001___sp_ever_had_pain_or_discomfort_in_chest', 'cdq010___shortness_of_breath_on_stairs/inclines', 'alq170___past_30_days_#_times_4_5_drinks_on_an_oc', 'alq142___#_days_have_4_or_5_drinks/past_12_mos', 'alq130___avg_#_alcoholic_drinks/day___past_12_mos', 'alq151___ever_have_4/5_or_more_drinks_every_day?', 'alq121___past_12_mo_how_often_drink_alcoholic_bev', 'kiq046___leak_urine_during_nonphysical_activities', 'kiq480___how_many_times_urinate_in_night?', 'kiq044___urinated_before_reaching_the_toilet?', 'kiq042___leak_urine_during_physical_activities?', 'kiq005___how_often_have_urinary_leakage?', 'dpq040___feeling_tired_or_having_little_energy', 'alq111___ever_had_a_drink_of_any_kind_of_alcohol', 'uacr_mg_g', 'kiq022___ever_told_you_had_weak/failing_kidneys?', 'kiq026___ever_had_kidney_stones?', 'mcq160a___ever_told_you_had_arthritis', 'mcq160b___ever_told_you_had_congestive_heart_failure', 'mcq160c___ever_told_you_had_coronary_heart_disease', 'mcq160d___ever_told_you_had_angina', 'mcq160e___ever_told_you_had_heart_attack', 'mcq160f___ever_told_you_had_stroke', 'mcq160p___ever_told_you_had_copd_emphysema', 'mcq220___ever_told_you_had_cancer_or_malignancy', 'mcq300a___close_relative_had_heart_attack', 'mcq300c___close_relative_had_diabetes', 'mcq520___abdominal_pain_during_past_12_months?', 'mcq550___has_dr_ever_said_you_have_gallstones', 'mcq560___ever_had_gallbladder_surgery?', 'mcq160m___ever_told_you_had_thyroid_problem', 'slq300___usual_sleep_time_on_weekdays_or_workdays', 'slq320___usual_sleep_time_on_weekends', 'slq330___usual_wake_time_on_weekends', 'slq310___usual_wake_time_on_weekdays_or_workdays', 'sld013___sleep_hours___weekends', 'sld012___sleep_hours___weekdays_or_workdays', 'gender', 'paq650___vigorous_recreational_activities', 'paq665___moderate_recreational_activities', 'bpq020___ever_told_you_had_high_blood_pressure', 'huq071___overnight_hospital_patient_in_last_year', 'huq090___seen_mental_health_professional/past_yr', 'mcq010___ever_been_told_you_have_asthma', 'mcq053___taking_treatment_for_anemia/past_3_mos', 'mcq092___ever_receive_blood_transfusion', 'mcq300b___close_relative_had_asthma', 'mcq366b___doctor_told_to_increase_exercise', 'mcq366c___doctor_told_to_reduce_salt', 'mcq366d___doctor_told_to_reduce_fat_in_diet', 'mcq371b___doing_increasing_exercise', 'mcq371c___doing_reducing_salt', 'paq620___moderate_work_activity', 'paq635___walk_or_bicycle', 'mcq371d___doing_reducing_fat_in_diet', 'paq605___vigorous_work_activity', 'slq050___ever_told_doctor_had_trouble_sleeping?', 'smq020___smoked_at_least_100_cigarettes_in_life', 'whq040___like_to_weigh_more,_less_or_same', 'huq030___routine_place_to_go_for_healthcare', 'slq030___how_often_do_you_snore?', 'slq040___how_often_do_you_snort_or_stop_breathing', 'huq010___general_health_condition', 'huq051___#times_receive_healthcare_over_past_year', 'age_years']

In [104]:
final_audit_path = OUTPUT_DIR / "prediabetes_feature_audit_final.csv"
filtered_audit_df.to_csv(final_audit_path, index=False)
print("Saved:", final_audit_path.resolve())

Saved: C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes\prediabetes_feature_audit_final.csv

In [105]:
model_df = df[[TARGET] + final_features].copy()

print("Model dataframe shape:", model_df.shape)
print("Target missing:", model_df[TARGET].isna().sum())

X = model_df[final_features].copy()
y = model_df[TARGET].copy()

mask = y.notna()
X = X.loc[mask].copy()
y = y.loc[mask].astype(int).copy()

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=TEST_SIZE,
    stratify=y,
    random_state=RANDOM_STATE
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)
print("Train target distribution:")
print(y_train.value_counts(normalize=True).round(4))

Model dataframe shape: (7437, 74)
Target missing: 0
Train shape: (5949, 73)
Test shape: (1488, 73)
Train target distribution:
prediabetes
0    0.9082
1    0.0918
Name: proportion, dtype: float64

In [106]:
univariate_rows = []

for col in final_features:
    s = X_train[col]
    feature_type = infer_feature_type(s)

    row = {
        "feature": col,
        "feature_type": feature_type,
        "missing_pct_train": round(s.isna().mean() * 100, 2),
        "n_unique_train": s.nunique(dropna=True),
        "association_metric": None,
        "association_value": np.nan,
        "abs_association": np.nan,
        "p_value": np.nan,
        "n_train_non_null": int(s.notna().sum())
    }

    if feature_type == "categorical":
        valid = s.notna() & y_train.notna()
        if valid.sum() >= 30:
            try:
                cv = cramers_v(s[valid], y_train[valid])
                table = pd.crosstab(s[valid], y_train[valid])
                p_val = chi2_contingency(table)[1] if table.shape[0] > 1 and table.shape[1] > 1 else np.nan
                row["association_metric"] = "cramers_v"
                row["association_value"] = cv
                row["abs_association"] = abs(cv) if pd.notna(cv) else np.nan
                row["p_value"] = p_val
            except Exception:
                pass
    else:
        r, p = safe_pointbiserial(s, y_train)
        row["association_metric"] = "pointbiserial"
        row["association_value"] = r
        row["abs_association"] = abs(r) if pd.notna(r) else np.nan
        row["p_value"] = p

    univariate_rows.append(row)

univariate_df = pd.DataFrame(univariate_rows).sort_values(
    ["abs_association", "p_value"],
    ascending=[False, True]
)

univariate_df.head(50)

,feature,feature_type,missing_pct_train,n_unique_train,association_metric,association_value,abs_association,p_value,n_train_non_null
55,mcq366b___doctor_told_to_increase_exercise,categorical,0.00,3,cramers_v,0.175833,0.175833,1.150146e-40,5949
57,mcq366d___doctor_told_to_reduce_fat_in_diet,categorical,0.00,3,cramers_v,0.167165,0.167165,7.969839e-37,5949
56,mcq366c___doctor_told_to_reduce_salt,categorical,0.00,3,cramers_v,0.144598,0.144598,9.775706e-28,5949
42,slq310___usual_wake_time_on_weekdays_or_workdays,categorical,0.99,104,cramers_v,0.135698,0.135698,3.372277e-01,5890
72,age_years,numeric,0.00,48,pointbiserial,0.117479,0.117479,9.836045e-20,5949
41,slq330___usual_wake_time_on_weekends,categorical,1.13,65,cramers_v,0.115545,0.115545,1.045548e-01,5882
48,bpq020___ever_told_you_had_high_blood_pressure,categorical,0.00,3,cramers_v,0.107724,0.107724,1.021255e-15,5949
39,slq300___usual_sleep_time_on_weekdays_or_workdays,categorical,1.36,62,cramers_v,0.106239,0.106239,3.013050e-01,5868
66,"whq040___like_to_weigh_more,_less_or_same",categorical,0.00,4,cramers_v,0.102125,0.102125,2.148577e-13,5949
40,slq320___usual_sleep_time_on_weekends,categorical,1.33,53,cramers_v,0.100735,0.100735,2.196416e-01,5870
5,rhq031___had_regular_periods_in_past_12_months,categorical,54.78,3,cramers_v,0.091793,0.091793,1.197115e-05,2690
68,slq030___how_often_do_you_snore?,categorical,0.00,6,cramers_v,0.091155,0.091155,1.811455e-09,5949
62,mcq371d___doing_reducing_fat_in_diet,categorical,0.00,4,cramers_v,0.089815,0.089815,2.140991e-10,5949
59,mcq371c___doing_reducing_salt,categorical,0.00,3,cramers_v,0.089013,0.089013,5.816321e-11,5949
70,huq010___general_health_condition,categorical,0.00,7,cramers_v,0.087525,0.087525,3.599919e-08,5949
64,slq050___ever_told_doctor_had_trouble_sleeping?,categorical,0.00,4,cramers_v,0.085808,0.085808,1.661935e-09,5949
38,mcq160m___ever_told_you_had_thyroid_problem,categorical,6.35,3,cramers_v,0.082948,0.082948,4.749060e-09,5571
71,huq051___#times_receive_healthcare_over_past_year,categorical,0.00,10,cramers_v,0.079613,0.079613,1.968292e-05,5949
34,mcq300c___close_relative_had_diabetes,categorical,6.35,3,cramers_v,0.079418,0.079418,2.343901e-08,5571
25,mcq160a___ever_told_you_had_arthritis,categorical,6.35,3,cramers_v,0.073626,0.073626,2.769288e-07,5571
69,slq040___how_often_do_you_snort_or_stop_breathing,categorical,0.00,6,cramers_v,0.072250,0.072250,9.139623e-06,5949
18,kiq042___leak_urine_during_physical_activities?,categorical,18.12,4,cramers_v,0.070079,0.070079,2.593616e-05,4871
9,cdq010___shortness_of_breath_on_stairs/inclines,categorical,43.92,3,cramers_v,0.069729,0.069729,3.005318e-04,3336
36,mcq550___has_dr_ever_said_you_have_gallstones,categorical,6.35,3,cramers_v,0.067121,0.067121,3.547808e-06,5571
67,huq030___routine_place_to_go_for_healthcare,categorical,0.00,5,cramers_v,0.066208,0.066208,3.052731e-05,5949
37,mcq560___ever_had_gallbladder_surgery?,categorical,6.35,3,cramers_v,0.062820,0.062820,1.682713e-05,5571
1,paq670___days_moderate_recreational_activities,categorical,57.61,8,cramers_v,0.062153,0.062153,2.036523e-01,2522
19,kiq005___how_often_have_urinary_leakage?,categorical,18.10,7,cramers_v,0.061439,0.061439,5.326282e-03,4872
20,dpq040___feeling_tired_or_having_little_energy,categorical,12.93,6,cramers_v,0.061242,0.061242,1.599212e-03,5180
8,cdq001___sp_ever_had_pain_or_discomfort_in_chest,categorical,43.92,3,cramers_v,0.059182,0.059182,2.902353e-03,3336
3,rhq131___ever_been_pregnant?,categorical,57.37,3,cramers_v,0.056630,0.056630,1.713878e-02,2536
2,rhq540___ever_use_female_hormones?,categorical,57.39,4,cramers_v,0.053702,0.053702,6.262824e-02,2535
4,triglycerides_mg_dl,numeric,56.80,316,pointbiserial,0.052870,0.052870,7.344000e-03,2570
32,mcq220___ever_told_you_had_cancer_or_malignancy,categorical,6.35,3,cramers_v,0.052512,0.052512,4.615037e-04,5571
17,kiq044___urinated_before_reaching_the_toilet?,categorical,18.14,4,cramers_v,0.051428,0.051428,4.902608e-03,4870
61,paq635___walk_or_bicycle,categorical,0.00,3,cramers_v,0.048666,0.048666,8.720114e-04,5949
35,mcq520___abdominal_pain_during_past_12_months?,categorical,6.35,3,cramers_v,0.048545,0.048545,1.409845e-03,5571
58,mcq371b___doing_increasing_exercise,categorical,0.00,3,cramers_v,0.047289,0.047289,1.291702e-03,5949
16,kiq480___how_many_times_urinate_in_night?,categorical,18.15,8,cramers_v,0.044273,0.044273,2.159261e-01,4869
7,paq625___number_of_days_moderate_work,categorical,54.23,8,cramers_v,0.042735,0.042735,6.632526e-01,2723
53,mcq092___ever_receive_blood_transfusion,categorical,0.00,3,cramers_v,0.042395,0.042395,4.765897e-03,5949
0,rhq305___had_both_ovaries_removed?,categorical,57.66,3,cramers_v,0.039768,0.039768,1.364432e-01,2519
46,paq650___vigorous_recreational_activities,categorical,0.00,2,cramers_v,0.039632,0.039632,2.236881e-03,5949
45,gender,categorical,0.00,2,cramers_v,0.039392,0.039392,2.379264e-03,5949
24,kiq026___ever_had_kidney_stones?,categorical,6.35,3,cramers_v,0.038042,0.038042,1.775333e-02,5571
31,mcq160p___ever_told_you_had_copd_emphysema,categorical,6.35,3,cramers_v,0.033196,0.033196,4.644228e-02,5571
52,mcq053___taking_treatment_for_anemia/past_3_mos,categorical,0.00,3,cramers_v,0.032825,0.032825,4.055770e-02,5949
29,mcq160e___ever_told_you_had_heart_attack,categorical,6.35,3,cramers_v,0.032662,0.032662,5.121993e-02,5571
30,mcq160f___ever_told_you_had_stroke,categorical,6.35,3,cramers_v,0.030368,0.030368,7.661873e-02,5571
44,sld012___sleep_hours___weekdays_or_workdays,numeric,0.71,24,pointbiserial,-0.029591,0.029591,2.294756e-02,5907

In [107]:
univariate_path = OUTPUT_DIR / "prediabetes_univariate_ranking.csv"
univariate_df.to_csv(univariate_path, index=False)
print("Saved:", univariate_path.resolve())

Saved: C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes\prediabetes_univariate_ranking.csv

In [108]:
numeric_features = []
categorical_features = []

for col in final_features:
    if infer_feature_type(X_train[col]) == "numeric":
        numeric_features.append(col)
    else:
        categorical_features.append(col)

print("Numeric features:", len(numeric_features))
print("Categorical features:", len(categorical_features))

Numeric features: 10
Categorical features: 63

In [109]:
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features),
    ],
    remainder="drop"
)

In [110]:
baseline_model = DummyClassifier(strategy="most_frequent")

baseline_model.fit(X_train, y_train)
baseline_pred = baseline_model.predict(X_test)

print("Baseline precision:", precision_score(y_test, baseline_pred, zero_division=0))
print("Baseline recall:", recall_score(y_test, baseline_pred, zero_division=0))
print("Baseline f1:", f1_score(y_test, baseline_pred, zero_division=0))

Baseline precision: 0.0
Baseline recall: 0.0
Baseline f1: 0.0

In [111]:
logreg_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        random_state=RANDOM_STATE
    ))
])

rf_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(
        n_estimators=400,
        max_depth=None,
        min_samples_leaf=5,
        class_weight="balanced_subsample",
        random_state=RANDOM_STATE,
        n_jobs=-1
    ))
])

In [112]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
scoring = {
    "roc_auc": "roc_auc",
    "avg_precision": "average_precision",
    "f1": "f1",
    "precision": "precision",
    "recall": "recall"
}

logreg_cv = cross_validate(logreg_pipeline, X_train, y_train, cv=cv, scoring=scoring, n_jobs=-1)
rf_cv = cross_validate(rf_pipeline, X_train, y_train, cv=cv, scoring=scoring, n_jobs=-1)

cv_summary = pd.DataFrame({
    "model": ["logreg", "random_forest"],
    "roc_auc_mean": [logreg_cv["test_roc_auc"].mean(), rf_cv["test_roc_auc"].mean()],
    "avg_precision_mean": [logreg_cv["test_avg_precision"].mean(), rf_cv["test_avg_precision"].mean()],
    "f1_mean": [logreg_cv["test_f1"].mean(), rf_cv["test_f1"].mean()],
    "precision_mean": [logreg_cv["test_precision"].mean(), rf_cv["test_precision"].mean()],
    "recall_mean": [logreg_cv["test_recall"].mean(), rf_cv["test_recall"].mean()],
}).sort_values("avg_precision_mean", ascending=False)

cv_summary

           model  roc_auc_mean  avg_precision_mean   f1_mean  precision_mean  recall_mean
1  random_forest      0.711788            0.174493  0.057200        0.217939     0.032961
0         logreg      0.679641            0.167917  0.247861        0.159787     0.553161

In [113]:
best_pipeline = logreg_pipeline
best_model_name = "logreg"

best_pipeline.fit(X_train, y_train)

test_proba = best_pipeline.predict_proba(X_test)[:, 1]
test_pred = (test_proba >= 0.50).astype(int)

print("Best model:", best_model_name)
print("ROC-AUC:", round(roc_auc_score(y_test, test_proba), 4))
print("Average Precision:", round(average_precision_score(y_test, test_proba), 4))
print("Precision:", round(precision_score(y_test, test_pred, zero_division=0), 4))
print("Recall:", round(recall_score(y_test, test_pred, zero_division=0), 4))
print("F1:", round(f1_score(y_test, test_pred, zero_division=0), 4))
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test, test_pred))
print()
print(classification_report(y_test, test_pred, zero_division=0))

Best model: logreg
ROC-AUC: 0.6977
Average Precision: 0.1844
Precision: 0.1626
Recall: 0.5809
F1: 0.254

Confusion Matrix:
[[945 407]
 [ 57  79]]

              precision    recall  f1-score   support

           0       0.94      0.70      0.80      1352
           1       0.16      0.58      0.25       136

    accuracy                           0.69      1488
   macro avg       0.55      0.64      0.53      1488
weighted avg       0.87      0.69      0.75      1488

In [114]:
perm = permutation_importance(
    best_pipeline,
    X_test,
    y_test,
    n_repeats=20,
    random_state=RANDOM_STATE,
    scoring="average_precision",
    n_jobs=-1
)

perm_df = pd.DataFrame({
    "feature": X_test.columns,
    "importance_mean": perm.importances_mean,
    "importance_std": perm.importances_std
}).sort_values("importance_mean", ascending=False)

perm_df.head(30)

                                              feature  importance_mean  importance_std
55         mcq366b___doctor_told_to_increase_exercise         0.018912        0.009156
42   slq310___usual_wake_time_on_weekdays_or_workdays         0.007564        0.006615
57        mcq366d___doctor_told_to_reduce_fat_in_diet         0.006646        0.006201
68                   slq030___how_often_do_you_snore?         0.005544        0.003937
1      paq670___days_moderate_recreational_activities         0.005272        0.002569
72                                          age_years         0.004701        0.005483
38        mcq160m___ever_told_you_had_thyroid_problem         0.003269        0.006093
20     dpq040___feeling_tired_or_having_little_energy         0.003217        0.004423
40              slq320___usual_sleep_time_on_weekends         0.003099        0.007359
12  alq130___avg_#_alcoholic_drinks/day___past_12_mos         0.002891        0.002925
39  slq300___usual_sleep_time_on_weekdays_or_workdays         0.002842        0.009627
47          paq665___moderate_recreational_activities         0.002599        0.005238
16          kiq480___how_many_times_urinate_in_night?         0.002249        0.002955
51            mcq010___ever_been_told_you_have_asthma         0.002202        0.002750
31         mcq160p___ever_told_you_had_copd_emphysema         0.002045        0.000869
22                                          uacr_mg_g         0.002029        0.002824
56               mcq366c___doctor_told_to_reduce_salt         0.001928        0.002787
17      kiq044___urinated_before_reaching_the_toilet?         0.001915        0.001839
2                  rhq540___ever_use_female_hormones?         0.001556        0.002036
54                mcq300b___close_relative_had_asthma         0.001416        0.001105
64    slq050___ever_told_doctor_had_trouble_sleeping?         0.000984        0.002976
11     alq142___#_days_have_4_or_5_drinks/past_12_mos         0.000956        0.001036
8    cdq001___sp_ever_had_pain_or_discomfort_in_chest         0.000950        0.003760
13   alq151___ever_have_4/5_or_more_drinks_every_day?         0.000853        0.001157
66          whq040___like_to_weigh_more,_less_or_same         0.000843        0.004650
27  mcq160c___ever_told_you_had_coronary_heart_dis...         0.000817        0.001480
15  kiq046___leak_urine_during_nonphysical_activities         0.000807        0.000860
28                 mcq160d___ever_told_you_had_angina         0.000723        0.002145
44        sld012___sleep_hours___weekdays_or_workdays         0.000633        0.002626
48     bpq020___ever_told_you_had_high_blood_pressure         0.000612        0.001159

# Prediabetes-focused only run
This section restricts the feature space to prediabetes-relevant and quiz-eligible variables only.

### Purpose
Compare a broad questionnaire model (Set 1) against a prediabetes-focused model (Set 2).

### Principle
We intentionally exclude:
- direct target / diabetes leakage
- doctor-feedback / post-hoc intervention variables
- healthcare utilization proxies
- broad morbidity proxies that are not practical for a quiz

We keep only:
- plausible symptom proxies
- lifestyle / activity signals
- sleep / circadian signals
- family risk / related cardiometabolic context
- a few subjective weight / fatigue signals

In [126]:
PREDIABETES_FOCUSED_FEATURES = [
    # Urination / possible glucose-related symptom proxies
    "kiq480___how_many_times_urinate_in_night?",
    "kiq044___urinated_before_reaching_the_toilet?",
    "kiq046___leak_urine_during_nonphysical_activities",
    "kiq005___how_often_have_urinary_leakage?",

    # Fatigue / subjective symptom burden
    "dpq040___feeling_tired_or_having_little_energy",

    # Activity / sedentary risk proxies
    "paq650___vigorous_recreational_activities",
    "paq665___moderate_recreational_activities",
    "paq670___days_moderate_recreational_activities",
    "paq605___vigorous_work_activity",
    "paq625___number_of_days_moderate_work",

    # Sleep / circadian pattern
    "slq030___how_often_do_you_snore?",
    "sleep_hours_weekday",
    "sleep_hours_weekend",
    "social_jetlag",
    "sin_weekday_bedtime",
    "cos_weekday_bedtime",
    "sin_weekday_wake",
    "cos_weekday_wake",
    

    # Weight / body perception proxy
    "whq040___like_to_weigh_more,_less_or_same",

    # Related cardiometabolic context
    "bpq020___ever_told_you_had_high_blood_pressure",
    "mcq300c___close_relative_had_diabetes",

    # Lifestyle / alcohol
    "alq111___ever_had_a_drink_of_any_kind_of_alcohol",
    "alq121___past_12_mo_how_often_drink_alcoholic_bev",
    "alq130___avg_#_alcoholic_drinks/day___past_12_mos",
    "alq142___#_days_have_4_or_5_drinks/past_12_mos",
    "alq170___past_30_days_#_times_4_5_drinks_on_an_oc",

    # Age & Gender
    "age_years",
    "gender"

    # Meds & Labs
    "med_count",
    "fasting_glucose_mg_dl"
]

prediabetes_focused_available = [c for c in PREDIABETES_FOCUSED_FEATURES if c in df.columns]
prediabetes_focused_missing = [c for c in PREDIABETES_FOCUSED_FEATURES if c not in df.columns]

print("Available prediabetes-focused features:", len(prediabetes_focused_available))
print(prediabetes_focused_available)
print()
print("Missing requested features:", len(prediabetes_focused_missing))
print(prediabetes_focused_missing)

Available prediabetes-focused features: 28
['kiq480___how_many_times_urinate_in_night?', 'kiq044___urinated_before_reaching_the_toilet?', 'kiq046___leak_urine_during_nonphysical_activities', 'kiq005___how_often_have_urinary_leakage?', 'dpq040___feeling_tired_or_having_little_energy', 'paq650___vigorous_recreational_activities', 'paq665___moderate_recreational_activities', 'paq670___days_moderate_recreational_activities', 'paq605___vigorous_work_activity', 'paq625___number_of_days_moderate_work', 'slq030___how_often_do_you_snore?', 'sleep_hours_weekday', 'sleep_hours_weekend', 'social_jetlag', 'sin_weekday_bedtime', 'cos_weekday_bedtime', 'sin_weekday_wake', 'cos_weekday_wake', 'whq040___like_to_weigh_more,_less_or_same', 'bpq020___ever_told_you_had_high_blood_pressure', 'mcq300c___close_relative_had_diabetes', 'alq111___ever_had_a_drink_of_any_kind_of_alcohol', 'alq121___past_12_mo_how_often_drink_alcoholic_bev', 'alq130___avg_#_alcoholic_drinks/day___past_12_mos', 'alq142___#_days_have_4_or_5_drinks/past_12_mos', 'alq170___past_30_days_#_times_4_5_drinks_on_an_oc', 'age_years', 'fasting_glucose_mg_dl']

Missing requested features: 1
['gendermed_count']

In [127]:
prediabetes_focus_audit_rows = []

for col in prediabetes_focused_available:
    s = df[col]
    prediabetes_focus_audit_rows.append({
        "feature": col,
        "dtype": str(s.dtype),
        "missing_pct": round(s.isna().mean() * 100, 2),
        "n_unique": s.nunique(dropna=True),
        "example_values": str(get_example_values(s, n=5)),
        "is_binary_like": is_binary_series(s),
    })

prediabetes_focus_audit_df = pd.DataFrame(prediabetes_focus_audit_rows).sort_values(
    ["missing_pct", "n_unique", "feature"],
    ascending=[False, True, True]
)

prediabetes_focus_audit_df

                                              feature    dtype  missing_pct  n_unique                                     example_values  is_binary_like
7      paq670___days_moderate_recreational_activities  float64        57.70         8  [np.float64(4.0), np.float64(5.0), np.float64(...           False
27                              fasting_glucose_mg_dl  float64        56.56       219  [np.float64(103.0), np.float64(92.0), np.float...           False
9               paq625___number_of_days_moderate_work  float64        54.20         8  [np.float64(5.0), np.float64(2.0), np.float64(...           False
25  alq170___past_30_days_#_times_4_5_drinks_on_an_oc  float64        35.35        23  [np.float64(0.0), np.float64(30.0), np.float64...           False
24     alq142___#_days_have_4_or_5_drinks/past_12_mos  float64        34.89        13  [np.float64(0.0), np.float64(4.0), np.float64(...           False
23  alq130___avg_#_alcoholic_drinks/day___past_12_mos  float64        34.89        15  [np.float64(1.0), np.float64(6.0), np.float64(...           False
22  alq121___past_12_mo_how_often_drink_alcoholic_bev  float64        21.68        13  [np.float64(10.0), np.float64(0.0), np.float64...           False
2   kiq046___leak_urine_during_nonphysical_activities  float64        18.14         4  [np.float64(2.0), np.float64(1.0), np.float64(...           False
0           kiq480___how_many_times_urinate_in_night?  float64        18.14         8  [np.float64(0.0), np.float64(2.0), np.float64(...           False
1       kiq044___urinated_before_reaching_the_toilet?  float64        18.13         4  [np.float64(2.0), np.float64(1.0), np.float64(...           False
3            kiq005___how_often_have_urinary_leakage?  float64        18.10         7  [np.float64(1.0), np.float64(2.0), np.float64(...           False
4      dpq040___feeling_tired_or_having_little_energy  float64        13.03         6  [np.float64(0.0), np.float64(2.0), np.float64(...           False
21   alq111___ever_had_a_drink_of_any_kind_of_alcohol  float64        12.75         2                 [np.float64(1.0), np.float64(2.0)]           False
20              mcq300c___close_relative_had_diabetes  float64         6.20         3  [np.float64(1.0), np.float64(2.0), np.float64(...           False
14                                sin_weekday_bedtime  float64         1.29        57  [np.float64(-0.5000000000000004), np.float64(0...           False
15                                cos_weekday_bedtime  float64         1.29        59  [np.float64(0.8660254037844384), np.float64(1....           False
13                                      social_jetlag  float64         1.12        35  [np.float64(0.5), np.float64(0.0), np.float64(...           False
16                                   sin_weekday_wake  float64         0.97        94  [np.float64(0.9914448613738104), np.float64(0....           False
17                                   cos_weekday_wake  float64         0.97       109  [np.float64(0.1305261922200517), np.float64(-0...           False
12                                sleep_hours_weekend  float64         0.86        24  [np.float64(8.0), np.float64(13.0), np.float64...           False
11                                sleep_hours_weekday  float64         0.71        24  [np.float64(7.5), np.float64(8.0), np.float64(...           False
5           paq650___vigorous_recreational_activities  float64         0.00         2                 [np.float64(1.0), np.float64(2.0)]           False
6           paq665___moderate_recreational_activities  float64         0.00         2                 [np.float64(1.0), np.float64(2.0)]           False
19     bpq020___ever_told_you_had_high_blood_pressure  float64         0.00         3  [np.float64(2.0), np.float64(1.0), np.float64(...           False
8                     paq605___vigorous_work_activity  float64         0.00         4  [np.float64(2.0), np.float64(1.0), np.float64(...           False
18          whq040___like_to_weigh_more,_less_or_same  float64         0.00         4  [np.float64(2.0), np.float64(1.0), np.float64(...           False
10                   slq030___how_often_do_you_snore?  float64         0.00         6  [np.float64(1.0), np.float64(0.0), np.float64(...           False
26                                          age_years  float64         0.00        48  [np.float64(29.0), np.float64(21.0), np.float6...           False

In [128]:
PREDIABETES_FOCUS_MANUAL_DROP = [
    "alq111___ever_had_a_drink_of_any_kind_of_alcohol",
    "alq121___past_12_mo_how_often_drink_alcoholic_bev",
    "alq142___#_days_have_4_or_5_drinks/past_12_mos",
    "kiq005___how_often_have_urinary_leakage",
    "kiq044___urinated_before_reaching_the_toilet",
    "kiq046___leak_urine_during_nonphysical_activities",
]

PREDIABETES_FOCUS_MAX_MISSING_PCT = 60.0

prediabetes_focused_final_features = [
    c for c in prediabetes_focused_available
    if c not in PREDIABETES_FOCUS_MANUAL_DROP
    and df[c].isna().mean() * 100 <= PREDIABETES_FOCUS_MAX_MISSING_PCT
]

print("Final prediabetes-focused features:", len(prediabetes_focused_final_features))
print(prediabetes_focused_final_features)

Final prediabetes-focused features: 24
['kiq480___how_many_times_urinate_in_night?', 'kiq044___urinated_before_reaching_the_toilet?', 'kiq005___how_often_have_urinary_leakage?', 'dpq040___feeling_tired_or_having_little_energy', 'paq650___vigorous_recreational_activities', 'paq665___moderate_recreational_activities', 'paq670___days_moderate_recreational_activities', 'paq605___vigorous_work_activity', 'paq625___number_of_days_moderate_work', 'slq030___how_often_do_you_snore?', 'sleep_hours_weekday', 'sleep_hours_weekend', 'social_jetlag', 'sin_weekday_bedtime', 'cos_weekday_bedtime', 'sin_weekday_wake', 'cos_weekday_wake', 'whq040___like_to_weigh_more,_less_or_same', 'bpq020___ever_told_you_had_high_blood_pressure', 'mcq300c___close_relative_had_diabetes', 'alq130___avg_#_alcoholic_drinks/day___past_12_mos', 'alq170___past_30_days_#_times_4_5_drinks_on_an_oc', 'age_years', 'fasting_glucose_mg_dl']

In [129]:
prediabetes_focus_df = df[[TARGET] + prediabetes_focused_final_features].copy()

mask = prediabetes_focus_df[TARGET].notna()
X_pf = prediabetes_focus_df.loc[mask, prediabetes_focused_final_features].copy()
y_pf = prediabetes_focus_df.loc[mask, TARGET].astype(int).copy()

X_train_pf, X_test_pf, y_train_pf, y_test_pf = train_test_split(
    X_pf, y_pf,
    test_size=TEST_SIZE,
    stratify=y_pf,
    random_state=RANDOM_STATE
)

print("Prediabetes-focused train shape:", X_train_pf.shape)
print("Prediabetes-focused test shape:", X_test_pf.shape)
print("Train target distribution:")
print(y_train_pf.value_counts(normalize=True).round(4))

Prediabetes-focused train shape: (5949, 24)
Prediabetes-focused test shape: (1488, 24)
Train target distribution:
prediabetes
0    0.9082
1    0.0918
Name: proportion, dtype: float64

In [130]:
pf_univariate_rows = []

for col in prediabetes_focused_final_features:
    s = X_train_pf[col]
    feature_type = infer_feature_type(s)

    row = {
        "feature": col,
        "feature_type": feature_type,
        "missing_pct_train": round(s.isna().mean() * 100, 2),
        "n_unique_train": s.nunique(dropna=True),
        "association_metric": None,
        "association_value": np.nan,
        "abs_association": np.nan,
        "p_value": np.nan,
        "n_train_non_null": int(s.notna().sum())
    }

    if feature_type == "categorical":
        valid = s.notna() & y_train_pf.notna()
        if valid.sum() >= 30:
            try:
                cv = cramers_v(s[valid], y_train_pf[valid])
                table = pd.crosstab(s[valid], y_train_pf[valid])
                p_val = chi2_contingency(table)[1] if table.shape[0] > 1 and table.shape[1] > 1 else np.nan
                row["association_metric"] = "cramers_v"
                row["association_value"] = cv
                row["abs_association"] = abs(cv) if pd.notna(cv) else np.nan
                row["p_value"] = p_val
            except Exception:
                pass
    else:
        r, p = safe_pointbiserial(s, y_train_pf)
        row["association_metric"] = "pointbiserial"
        row["association_value"] = r
        row["abs_association"] = abs(r) if pd.notna(r) else np.nan
        row["p_value"] = p

    pf_univariate_rows.append(row)

pf_univariate_df = pd.DataFrame(pf_univariate_rows).sort_values(
    ["abs_association", "p_value"],
    ascending=[False, True]
)

pf_univariate_df

,feature,feature_type,missing_pct_train,n_unique_train,association_metric,association_value,abs_association,p_value,n_train_non_null
22,age_years,numeric,0.00,48,pointbiserial,0.117479,0.117479,9.836045e-20,5949
18,bpq020___ever_told_you_had_high_blood_pressure,categorical,0.00,3,cramers_v,0.107724,0.107724,1.021255e-15,5949
17,"whq040___like_to_weigh_more,_less_or_same",categorical,0.00,4,cramers_v,0.102125,0.102125,2.148577e-13,5949
9,slq030___how_often_do_you_snore?,categorical,0.00,6,cramers_v,0.091155,0.091155,1.811455e-09,5949
19,mcq300c___close_relative_had_diabetes,categorical,6.35,3,cramers_v,0.079418,0.079418,2.343901e-08,5571
6,paq670___days_moderate_recreational_activities,categorical,57.61,8,cramers_v,0.062153,0.062153,2.036523e-01,2522
2,kiq005___how_often_have_urinary_leakage?,categorical,18.10,7,cramers_v,0.061439,0.061439,5.326282e-03,4872
3,dpq040___feeling_tired_or_having_little_energy,categorical,12.93,6,cramers_v,0.061242,0.061242,1.599212e-03,5180
1,kiq044___urinated_before_reaching_the_toilet?,categorical,18.14,4,cramers_v,0.051428,0.051428,4.902608e-03,4870
0,kiq480___how_many_times_urinate_in_night?,categorical,18.15,8,cramers_v,0.044273,0.044273,2.159261e-01,4869
8,paq625___number_of_days_moderate_work,categorical,54.23,8,cramers_v,0.042735,0.042735,6.632526e-01,2723
4,paq650___vigorous_recreational_activities,categorical,0.00,2,cramers_v,0.039632,0.039632,2.236881e-03,5949
10,sleep_hours_weekday,numeric,0.71,24,pointbiserial,-0.029591,0.029591,2.294756e-02,5907
21,alq170___past_30_days_#_times_4_5_drinks_on_an_oc,numeric,35.38,22,pointbiserial,-0.025931,0.025931,1.079551e-01,3844
5,paq665___moderate_recreational_activities,categorical,0.00,2,cramers_v,0.021243,0.021243,1.013299e-01,5949
16,cos_weekday_wake,numeric,0.99,101,pointbiserial,0.019611,0.019611,1.323525e-01,5890
7,paq605___vigorous_work_activity,categorical,0.00,4,cramers_v,0.018275,0.018275,5.751454e-01,5949
11,sleep_hours_weekend,numeric,0.91,24,pointbiserial,-0.016076,0.016076,2.171741e-01,5895
20,alq130___avg_#_alcoholic_drinks/day___past_12_mos,numeric,34.95,15,pointbiserial,-0.014432,0.014432,3.694201e-01,3870
12,social_jetlag,numeric,1.14,35,pointbiserial,0.013579,0.013579,2.977964e-01,5881
23,fasting_glucose_mg_dl,numeric,55.99,202,pointbiserial,0.012777,0.012777,5.134653e-01,2618
14,cos_weekday_bedtime,numeric,1.36,58,pointbiserial,0.012238,0.012238,3.485854e-01,5868
15,sin_weekday_wake,numeric,0.99,89,pointbiserial,0.005016,0.005016,7.003245e-01,5890
13,sin_weekday_bedtime,numeric,1.36,56,pointbiserial,0.003281,0.003281,8.015755e-01,5868

In [131]:
numeric_features_pf = []
categorical_features_pf = []

for col in prediabetes_focused_final_features:
    if infer_feature_type(X_train_pf[col]) == "numeric":
        numeric_features_pf.append(col)
    else:
        categorical_features_pf.append(col)

print("Prediabetes-focused numeric features:", numeric_features_pf)
print()
print("Prediabetes-focused categorical features:", categorical_features_pf)

Prediabetes-focused numeric features: ['sleep_hours_weekday', 'sleep_hours_weekend', 'social_jetlag', 'sin_weekday_bedtime', 'cos_weekday_bedtime', 'sin_weekday_wake', 'cos_weekday_wake', 'alq130___avg_#_alcoholic_drinks/day___past_12_mos', 'alq170___past_30_days_#_times_4_5_drinks_on_an_oc', 'age_years', 'fasting_glucose_mg_dl']

Prediabetes-focused categorical features: ['kiq480___how_many_times_urinate_in_night?', 'kiq044___urinated_before_reaching_the_toilet?', 'kiq005___how_often_have_urinary_leakage?', 'dpq040___feeling_tired_or_having_little_energy', 'paq650___vigorous_recreational_activities', 'paq665___moderate_recreational_activities', 'paq670___days_moderate_recreational_activities', 'paq605___vigorous_work_activity', 'paq625___number_of_days_moderate_work', 'slq030___how_often_do_you_snore?', 'whq040___like_to_weigh_more,_less_or_same', 'bpq020___ever_told_you_had_high_blood_pressure', 'mcq300c___close_relative_had_diabetes']

In [132]:
preprocessor_pf = ColumnTransformer(
    transformers=[
        ("num", Pipeline([
            ("imputer", SimpleImputer(strategy="median"))
        ]), numeric_features_pf),
        ("cat", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore"))
        ]), categorical_features_pf),
    ],
    remainder="drop"
)

In [133]:
logreg_pipeline_pf = Pipeline(steps=[
    ("preprocessor", preprocessor_pf),
    ("model", LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        random_state=RANDOM_STATE
    ))
])

rf_pipeline_pf = Pipeline(steps=[
    ("preprocessor", preprocessor_pf),
    ("model", RandomForestClassifier(
        n_estimators=400,
        min_samples_leaf=5,
        class_weight="balanced_subsample",
        random_state=RANDOM_STATE,
        n_jobs=-1
    ))
])

In [134]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
scoring = {
    "roc_auc": "roc_auc",
    "avg_precision": "average_precision",
    "f1": "f1",
    "precision": "precision",
    "recall": "recall"
}

logreg_cv_pf = cross_validate(logreg_pipeline_pf, X_train_pf, y_train_pf, cv=cv, scoring=scoring, n_jobs=-1)
rf_cv_pf = cross_validate(rf_pipeline_pf, X_train_pf, y_train_pf, cv=cv, scoring=scoring, n_jobs=-1)

cv_summary_pf = pd.DataFrame({
    "model": ["logreg_prediabetes_focused", "random_forest_prediabetes_focused"],
    "roc_auc_mean": [logreg_cv_pf["test_roc_auc"].mean(), rf_cv_pf["test_roc_auc"].mean()],
    "avg_precision_mean": [logreg_cv_pf["test_avg_precision"].mean(), rf_cv_pf["test_avg_precision"].mean()],
    "f1_mean": [logreg_cv_pf["test_f1"].mean(), rf_cv_pf["test_f1"].mean()],
    "precision_mean": [logreg_cv_pf["test_precision"].mean(), rf_cv_pf["test_precision"].mean()],
    "recall_mean": [logreg_cv_pf["test_recall"].mean(), rf_cv_pf["test_recall"].mean()],
}).sort_values("avg_precision_mean", ascending=False)

cv_summary_pf

                               model  roc_auc_mean  avg_precision_mean   f1_mean  precision_mean  recall_mean
1  random_forest_prediabetes_focused      0.674702            0.156912  0.043574        0.161962     0.025655
0         logreg_prediabetes_focused      0.666762            0.151010  0.231264        0.142142     0.621001

In [135]:
# Choose the practically better model after inspection of cv_summary_pf.
# Defaulting to logistic regression as a robust starting point for imbalanced questionnaire data.

best_pipeline_pf = logreg_pipeline_pf
best_model_name_pf = "logreg_prediabetes_focused"

best_pipeline_pf.fit(X_train_pf, y_train_pf)

test_proba_pf = best_pipeline_pf.predict_proba(X_test_pf)[:, 1]
test_pred_pf = (test_proba_pf >= 0.50).astype(int)

print("Best prediabetes-focused model:", best_model_name_pf)
print("ROC-AUC:", round(roc_auc_score(y_test_pf, test_proba_pf), 4))
print("Average Precision:", round(average_precision_score(y_test_pf, test_proba_pf), 4))
print("Precision:", round(precision_score(y_test_pf, test_pred_pf, zero_division=0), 4))
print("Recall:", round(recall_score(y_test_pf, test_pred_pf, zero_division=0), 4))
print("F1:", round(f1_score(y_test_pf, test_pred_pf, zero_division=0), 4))
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test_pf, test_pred_pf))
print()
print(classification_report(y_test_pf, test_pred_pf, zero_division=0))

Best prediabetes-focused model: logreg_prediabetes_focused
ROC-AUC: 0.6668
Average Precision: 0.1601
Precision: 0.1433
Recall: 0.6544
F1: 0.2351

Confusion Matrix:
[[820 532]
 [ 47  89]]

              precision    recall  f1-score   support

           0       0.95      0.61      0.74      1352
           1       0.14      0.65      0.24       136

    accuracy                           0.61      1488
   macro avg       0.54      0.63      0.49      1488
weighted avg       0.87      0.61      0.69      1488

In [136]:
perm_pf = permutation_importance(
    best_pipeline_pf,
    X_test_pf,
    y_test_pf,
    n_repeats=20,
    random_state=RANDOM_STATE,
    scoring="average_precision",
    n_jobs=-1
)

perm_df_pf = pd.DataFrame({
    "feature": X_test_pf.columns,
    "importance_mean": perm_pf.importances_mean,
    "importance_std": perm_pf.importances_std
}).sort_values("importance_mean", ascending=False)

perm_df_pf

                                              feature  importance_mean  importance_std
14                                cos_weekday_bedtime         0.016089        0.003325
11                                sleep_hours_weekend         0.012824        0.004622
22                                          age_years         0.012353        0.007608
9                    slq030___how_often_do_you_snore?         0.011991        0.005513
19              mcq300c___close_relative_had_diabetes         0.010296        0.007520
3      dpq040___feeling_tired_or_having_little_energy         0.010090        0.006997
17          whq040___like_to_weigh_more,_less_or_same         0.006937        0.009648
8               paq625___number_of_days_moderate_work         0.006556        0.005115
0           kiq480___how_many_times_urinate_in_night?         0.006350        0.002289
5           paq665___moderate_recreational_activities         0.005332        0.004768
16                                   cos_weekday_wake         0.004872        0.003150
4           paq650___vigorous_recreational_activities         0.004598        0.002856
2            kiq005___how_often_have_urinary_leakage?         0.004558        0.003735
6      paq670___days_moderate_recreational_activities         0.004528        0.003722
10                                sleep_hours_weekday         0.004371        0.002384
20  alq130___avg_#_alcoholic_drinks/day___past_12_mos         0.003541        0.003414
12                                      social_jetlag         0.002811        0.008128
13                                sin_weekday_bedtime         0.001528        0.002237
21  alq170___past_30_days_#_times_4_5_drinks_on_an_oc         0.000350        0.002640
1       kiq044___urinated_before_reaching_the_toilet?         0.000332        0.000582
7                     paq605___vigorous_work_activity         0.000049        0.000263
15                                   sin_weekday_wake        -0.001358        0.006009
18     bpq020___ever_told_you_had_high_blood_pressure        -0.002192        0.005423
23                              fasting_glucose_mg_dl        -0.002277        0.001792

In [137]:
combined_df_pf = (
    pf_univariate_df.merge(perm_df_pf, on="feature", how="left")
    .merge(prediabetes_focus_audit_df[["feature", "missing_pct", "n_unique"]], on="feature", how="left")
)

combined_df_pf = combined_df_pf.sort_values(
    ["importance_mean", "abs_association"],
    ascending=[False, False]
)

combined_df_pf

,feature,feature_type,missing_pct_train,n_unique_train,association_metric,association_value,abs_association,p_value,n_train_non_null,importance_mean,importance_std,missing_pct,n_unique
21,cos_weekday_bedtime,numeric,1.36,58,pointbiserial,0.012238,0.012238,3.485854e-01,5868,0.016089,0.003325,1.29,59
17,sleep_hours_weekend,numeric,0.91,24,pointbiserial,-0.016076,0.016076,2.171741e-01,5895,0.012824,0.004622,0.86,24
0,age_years,numeric,0.00,48,pointbiserial,0.117479,0.117479,9.836045e-20,5949,0.012353,0.007608,0.00,48
3,slq030___how_often_do_you_snore?,categorical,0.00,6,cramers_v,0.091155,0.091155,1.811455e-09,5949,0.011991,0.005513,0.00,6
4,mcq300c___close_relative_had_diabetes,categorical,6.35,3,cramers_v,0.079418,0.079418,2.343901e-08,5571,0.010296,0.007520,6.20,3
7,dpq040___feeling_tired_or_having_little_energy,categorical,12.93,6,cramers_v,0.061242,0.061242,1.599212e-03,5180,0.010090,0.006997,13.03,6
2,"whq040___like_to_weigh_more,_less_or_same",categorical,0.00,4,cramers_v,0.102125,0.102125,2.148577e-13,5949,0.006937,0.009648,0.00,4
10,paq625___number_of_days_moderate_work,categorical,54.23,8,cramers_v,0.042735,0.042735,6.632526e-01,2723,0.006556,0.005115,54.20,8
9,kiq480___how_many_times_urinate_in_night?,categorical,18.15,8,cramers_v,0.044273,0.044273,2.159261e-01,4869,0.006350,0.002289,18.14,8
14,paq665___moderate_recreational_activities,categorical,0.00,2,cramers_v,0.021243,0.021243,1.013299e-01,5949,0.005332,0.004768,0.00,2
15,cos_weekday_wake,numeric,0.99,101,pointbiserial,0.019611,0.019611,1.323525e-01,5890,0.004872,0.003150,0.97,109
11,paq650___vigorous_recreational_activities,categorical,0.00,2,cramers_v,0.039632,0.039632,2.236881e-03,5949,0.004598,0.002856,0.00,2
6,kiq005___how_often_have_urinary_leakage?,categorical,18.10,7,cramers_v,0.061439,0.061439,5.326282e-03,4872,0.004558,0.003735,18.10,7
5,paq670___days_moderate_recreational_activities,categorical,57.61,8,cramers_v,0.062153,0.062153,2.036523e-01,2522,0.004528,0.003722,57.70,8
12,sleep_hours_weekday,numeric,0.71,24,pointbiserial,-0.029591,0.029591,2.294756e-02,5907,0.004371,0.002384,0.71,24
18,alq130___avg_#_alcoholic_drinks/day___past_12_mos,numeric,34.95,15,pointbiserial,-0.014432,0.014432,3.694201e-01,3870,0.003541,0.003414,34.89,15
19,social_jetlag,numeric,1.14,35,pointbiserial,0.013579,0.013579,2.977964e-01,5881,0.002811,0.008128,1.12,35
23,sin_weekday_bedtime,numeric,1.36,56,pointbiserial,0.003281,0.003281,8.015755e-01,5868,0.001528,0.002237,1.29,57
13,alq170___past_30_days_#_times_4_5_drinks_on_an_oc,numeric,35.38,22,pointbiserial,-0.025931,0.025931,1.079551e-01,3844,0.000350,0.002640,35.35,23
8,kiq044___urinated_before_reaching_the_toilet?,categorical,18.14,4,cramers_v,0.051428,0.051428,4.902608e-03,4870,0.000332,0.000582,18.13,4
16,paq605___vigorous_work_activity,categorical,0.00,4,cramers_v,0.018275,0.018275,5.751454e-01,5949,0.000049,0.000263,0.00,4
22,sin_weekday_wake,numeric,0.99,89,pointbiserial,0.005016,0.005016,7.003245e-01,5890,-0.001358,0.006009,0.97,94
1,bpq020___ever_told_you_had_high_blood_pressure,categorical,0.00,3,cramers_v,0.107724,0.107724,1.021255e-15,5949,-0.002192,0.005423,0.00,3
20,fasting_glucose_mg_dl,numeric,55.99,202,pointbiserial,0.012777,0.012777,5.134653e-01,2618,-0.002277,0.001792,56.56,219

## Threshold Tuning

In [138]:
threshold_rows = []

for t in [0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.50]:
    pred_t = (test_proba_pf >= t).astype(int)
    threshold_rows.append({
        "threshold": t,
        "precision": precision_score(y_test_pf, pred_t, zero_division=0),
        "recall": recall_score(y_test_pf, pred_t, zero_division=0),
        "f1": f1_score(y_test_pf, pred_t, zero_division=0),
        "positives_predicted": int(pred_t.sum())
    })

threshold_df_pf = pd.DataFrame(threshold_rows).sort_values("f1", ascending=False)
threshold_df_pf

   threshold  precision    recall        f1  positives_predicted
6       0.50   0.143317  0.654412  0.235139                  621
5       0.40   0.123025  0.801471  0.213307                  886
4       0.35   0.119478  0.875000  0.210247                  996
3       0.30   0.110314  0.904412  0.196643                 1115
2       0.25   0.103533  0.926471  0.186253                 1217
1       0.20   0.098248  0.948529  0.178054                 1313
0       0.15   0.095890  0.977941  0.174655                 1387

# Final 6

In [139]:
# Final compact quiz run for prediabetes
# Goal: test a very small, product-friendly feature set

PREDIABETES_FINAL_QUIZ_FEATURES = [
    "cos_weekday_bedtime",
    "sleep_hours_weekend",
    "slq030___how_often_do_you_snore?",
    "mcq300c___close_relative_had_diabetes",
    "paq650___vigorous_recreational_activities",
    "whq040___like_to_weigh_more,_less_or_same",
]

final_quiz_available = [c for c in PREDIABETES_FINAL_QUIZ_FEATURES if c in df.columns]
final_quiz_missing = [c for c in PREDIABETES_FINAL_QUIZ_FEATURES if c not in df.columns]

print("Available final quiz features:", len(final_quiz_available))
print(final_quiz_available)
print()
print("Missing requested features:", len(final_quiz_missing))
print(final_quiz_missing)

Available final quiz features: 6
['cos_weekday_bedtime', 'sleep_hours_weekend', 'slq030___how_often_do_you_snore?', 'mcq300c___close_relative_had_diabetes', 'paq650___vigorous_recreational_activities', 'whq040___like_to_weigh_more,_less_or_same']

Missing requested features: 0
[]

In [140]:
final_quiz_audit_rows = []

for col in final_quiz_available:
    s = df[col]
    final_quiz_audit_rows.append({
        "feature": col,
        "dtype": str(s.dtype),
        "missing_pct": round(s.isna().mean() * 100, 2),
        "n_unique": s.nunique(dropna=True),
        "example_values": str(get_example_values(s, n=10)),
        "is_binary_like": is_binary_series(s),
    })

final_quiz_audit_df = pd.DataFrame(final_quiz_audit_rows).sort_values(
    ["missing_pct", "n_unique", "feature"],
    ascending=[False, True, True]
)

final_quiz_audit_df

                                     feature    dtype  missing_pct  n_unique                                     example_values  is_binary_like
3      mcq300c___close_relative_had_diabetes  float64         6.20         3  [np.float64(1.0), np.float64(2.0), np.float64(...           False
0                        cos_weekday_bedtime  float64         1.29        59  [np.float64(0.8660254037844384), np.float64(1....           False
1                        sleep_hours_weekend  float64         0.86        24  [np.float64(8.0), np.float64(13.0), np.float64...           False
4  paq650___vigorous_recreational_activities  float64         0.00         2                 [np.float64(1.0), np.float64(2.0)]           False
5  whq040___like_to_weigh_more,_less_or_same  float64         0.00         4  [np.float64(2.0), np.float64(1.0), np.float64(...           False
2           slq030___how_often_do_you_snore?  float64         0.00         6  [np.float64(1.0), np.float64(0.0), np.float64(...           False

In [141]:
final_quiz_df = df[[TARGET] + final_quiz_available].copy()

mask = final_quiz_df[TARGET].notna()
X_fq = final_quiz_df.loc[mask, final_quiz_available].copy()
y_fq = final_quiz_df.loc[mask, TARGET].astype(int).copy()

X_train_fq, X_test_fq, y_train_fq, y_test_fq = train_test_split(
    X_fq, y_fq,
    test_size=TEST_SIZE,
    stratify=y_fq,
    random_state=RANDOM_STATE
)

print("Final quiz train shape:", X_train_fq.shape)
print("Final quiz test shape:", X_test_fq.shape)
print("Train target distribution:")
print(y_train_fq.value_counts(normalize=True).round(4))

Final quiz train shape: (5949, 6)
Final quiz test shape: (1488, 6)
Train target distribution:
prediabetes
0    0.9082
1    0.0918
Name: proportion, dtype: float64

In [142]:
fq_univariate_rows = []

for col in final_quiz_available:
    s = X_train_fq[col]
    feature_type = infer_feature_type(s)

    row = {
        "feature": col,
        "feature_type": feature_type,
        "missing_pct_train": round(s.isna().mean() * 100, 2),
        "n_unique_train": s.nunique(dropna=True),
        "association_metric": None,
        "association_value": np.nan,
        "abs_association": np.nan,
        "p_value": np.nan,
        "n_train_non_null": int(s.notna().sum())
    }

    if feature_type == "categorical":
        valid = s.notna() & y_train_fq.notna()
        if valid.sum() >= 30:
            try:
                cv = cramers_v(s[valid], y_train_fq[valid])
                table = pd.crosstab(s[valid], y_train_fq[valid])
                p_val = chi2_contingency(table)[1] if table.shape[0] > 1 and table.shape[1] > 1 else np.nan
                row["association_metric"] = "cramers_v"
                row["association_value"] = cv
                row["abs_association"] = abs(cv) if pd.notna(cv) else np.nan
                row["p_value"] = p_val
            except Exception:
                pass
    else:
        r, p = safe_pointbiserial(s, y_train_fq)
        row["association_metric"] = "pointbiserial"
        row["association_value"] = r
        row["abs_association"] = abs(r) if pd.notna(r) else np.nan
        row["p_value"] = p

    fq_univariate_rows.append(row)

fq_univariate_df = pd.DataFrame(fq_univariate_rows).sort_values(
    ["abs_association", "p_value"],
    ascending=[False, True]
)

fq_univariate_df

,feature,feature_type,missing_pct_train,n_unique_train,association_metric,association_value,abs_association,p_value,n_train_non_null
5,"whq040___like_to_weigh_more,_less_or_same",categorical,0.00,4,cramers_v,0.102125,0.102125,2.148577e-13,5949
2,slq030___how_often_do_you_snore?,categorical,0.00,6,cramers_v,0.091155,0.091155,1.811455e-09,5949
3,mcq300c___close_relative_had_diabetes,categorical,6.35,3,cramers_v,0.079418,0.079418,2.343901e-08,5571
4,paq650___vigorous_recreational_activities,categorical,0.00,2,cramers_v,0.039632,0.039632,2.236881e-03,5949
1,sleep_hours_weekend,numeric,0.91,24,pointbiserial,-0.016076,0.016076,2.171741e-01,5895
0,cos_weekday_bedtime,numeric,1.36,58,pointbiserial,0.012238,0.012238,3.485854e-01,5868

In [143]:
numeric_features_fq = []
categorical_features_fq = []

for col in final_quiz_available:
    if infer_feature_type(X_train_fq[col]) == "numeric":
        numeric_features_fq.append(col)
    else:
        categorical_features_fq.append(col)

print("Final quiz numeric features:", numeric_features_fq)
print()
print("Final quiz categorical features:", categorical_features_fq)

Final quiz numeric features: ['cos_weekday_bedtime', 'sleep_hours_weekend']

Final quiz categorical features: ['slq030___how_often_do_you_snore?', 'mcq300c___close_relative_had_diabetes', 'paq650___vigorous_recreational_activities', 'whq040___like_to_weigh_more,_less_or_same']

In [144]:
preprocessor_fq = ColumnTransformer(
    transformers=[
        ("num", Pipeline([
            ("imputer", SimpleImputer(strategy="median"))
        ]), numeric_features_fq),
        ("cat", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore"))
        ]), categorical_features_fq),
    ],
    remainder="drop"
)

In [145]:
baseline_model_fq = DummyClassifier(strategy="most_frequent")

baseline_model_fq.fit(X_train_fq, y_train_fq)
baseline_pred_fq = baseline_model_fq.predict(X_test_fq)

print("Baseline precision:", precision_score(y_test_fq, baseline_pred_fq, zero_division=0))
print("Baseline recall:", recall_score(y_test_fq, baseline_pred_fq, zero_division=0))
print("Baseline f1:", f1_score(y_test_fq, baseline_pred_fq, zero_division=0))

Baseline precision: 0.0
Baseline recall: 0.0
Baseline f1: 0.0

In [146]:
logreg_pipeline_fq = Pipeline(steps=[
    ("preprocessor", preprocessor_fq),
    ("model", LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        random_state=RANDOM_STATE
    ))
])

rf_pipeline_fq = Pipeline(steps=[
    ("preprocessor", preprocessor_fq),
    ("model", RandomForestClassifier(
        n_estimators=400,
        min_samples_leaf=5,
        class_weight="balanced_subsample",
        random_state=RANDOM_STATE,
        n_jobs=-1
    ))
])

In [147]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
scoring = {
    "roc_auc": "roc_auc",
    "avg_precision": "average_precision",
    "f1": "f1",
    "precision": "precision",
    "recall": "recall"
}

logreg_cv_fq = cross_validate(logreg_pipeline_fq, X_train_fq, y_train_fq, cv=cv, scoring=scoring, n_jobs=-1)
rf_cv_fq = cross_validate(rf_pipeline_fq, X_train_fq, y_train_fq, cv=cv, scoring=scoring, n_jobs=-1)

cv_summary_fq = pd.DataFrame({
    "model": ["logreg_final_quiz", "random_forest_final_quiz"],
    "roc_auc_mean": [logreg_cv_fq["test_roc_auc"].mean(), rf_cv_fq["test_roc_auc"].mean()],
    "avg_precision_mean": [logreg_cv_fq["test_avg_precision"].mean(), rf_cv_fq["test_avg_precision"].mean()],
    "f1_mean": [logreg_cv_fq["test_f1"].mean(), rf_cv_fq["test_f1"].mean()],
    "precision_mean": [logreg_cv_fq["test_precision"].mean(), rf_cv_fq["test_precision"].mean()],
    "recall_mean": [logreg_cv_fq["test_recall"].mean(), rf_cv_fq["test_recall"].mean()],
}).sort_values("avg_precision_mean", ascending=False)

cv_summary_fq

                      model  roc_auc_mean  avg_precision_mean   f1_mean  precision_mean  recall_mean
1  random_forest_final_quiz      0.627799            0.134600  0.207203        0.148374     0.344287
0         logreg_final_quiz      0.636517            0.133748  0.217063        0.130597     0.643003

In [148]:
# Default to logistic regression unless RF clearly wins in practical metrics
best_pipeline_fq = logreg_pipeline_fq
best_model_name_fq = "logreg_final_quiz"

best_pipeline_fq.fit(X_train_fq, y_train_fq)

test_proba_fq = best_pipeline_fq.predict_proba(X_test_fq)[:, 1]
test_pred_fq = (test_proba_fq >= 0.50).astype(int)

print("Best final quiz model:", best_model_name_fq)
print("ROC-AUC:", round(roc_auc_score(y_test_fq, test_proba_fq), 4))
print("Average Precision:", round(average_precision_score(y_test_fq, test_proba_fq), 4))
print("Precision:", round(precision_score(y_test_fq, test_pred_fq, zero_division=0), 4))
print("Recall:", round(recall_score(y_test_fq, test_pred_fq, zero_division=0), 4))
print("F1:", round(f1_score(y_test_fq, test_pred_fq, zero_division=0), 4))
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test_fq, test_pred_fq))
print()
print(classification_report(y_test_fq, test_pred_fq, zero_division=0))

Best final quiz model: logreg_final_quiz
ROC-AUC: 0.6543
Average Precision: 0.1474
Precision: 0.1277
Recall: 0.6618
F1: 0.214

Confusion Matrix:
[[737 615]
 [ 46  90]]

              precision    recall  f1-score   support

           0       0.94      0.55      0.69      1352
           1       0.13      0.66      0.21       136

    accuracy                           0.56      1488
   macro avg       0.53      0.60      0.45      1488
weighted avg       0.87      0.56      0.65      1488

In [149]:
perm_fq = permutation_importance(
    best_pipeline_fq,
    X_test_fq,
    y_test_fq,
    n_repeats=20,
    random_state=RANDOM_STATE,
    scoring="average_precision",
    n_jobs=-1
)

perm_df_fq = pd.DataFrame({
    "feature": X_test_fq.columns,
    "importance_mean": perm_fq.importances_mean,
    "importance_std": perm_fq.importances_std
}).sort_values("importance_mean", ascending=False)

perm_df_fq

                                     feature  importance_mean  importance_std
5  whq040___like_to_weigh_more,_less_or_same         0.016255        0.007604
3      mcq300c___close_relative_had_diabetes         0.012248        0.012377
2           slq030___how_often_do_you_snore?         0.008529        0.009650
4  paq650___vigorous_recreational_activities         0.007429        0.003629
0                        cos_weekday_bedtime         0.002749        0.003485
1                        sleep_hours_weekend        -0.011010        0.006168

In [150]:
combined_df_fq = (
    fq_univariate_df.merge(perm_df_fq, on="feature", how="left")
    .merge(final_quiz_audit_df[["feature", "missing_pct", "n_unique"]], on="feature", how="left")
)

combined_df_fq = combined_df_fq.sort_values(
    ["importance_mean", "abs_association"],
    ascending=[False, False]
)

combined_df_fq

,feature,feature_type,missing_pct_train,n_unique_train,association_metric,association_value,abs_association,p_value,n_train_non_null,importance_mean,importance_std,missing_pct,n_unique
0,"whq040___like_to_weigh_more,_less_or_same",categorical,0.00,4,cramers_v,0.102125,0.102125,2.148577e-13,5949,0.016255,0.007604,0.00,4
2,mcq300c___close_relative_had_diabetes,categorical,6.35,3,cramers_v,0.079418,0.079418,2.343901e-08,5571,0.012248,0.012377,6.20,3
1,slq030___how_often_do_you_snore?,categorical,0.00,6,cramers_v,0.091155,0.091155,1.811455e-09,5949,0.008529,0.009650,0.00,6
3,paq650___vigorous_recreational_activities,categorical,0.00,2,cramers_v,0.039632,0.039632,2.236881e-03,5949,0.007429,0.003629,0.00,2
5,cos_weekday_bedtime,numeric,1.36,58,pointbiserial,0.012238,0.012238,3.485854e-01,5868,0.002749,0.003485,1.29,59
4,sleep_hours_weekend,numeric,0.91,24,pointbiserial,-0.016076,0.016076,2.171741e-01,5895,-0.011010,0.006168,0.86,24

In [151]:
comparison_test_fq = pd.DataFrame([
    {
        "run": "set1_all_questionnaire",
        "model": best_model_name,
        "roc_auc": roc_auc_score(y_test, test_proba),
        "avg_precision": average_precision_score(y_test, test_proba),
        "precision": precision_score(y_test, test_pred, zero_division=0),
        "recall": recall_score(y_test, test_pred, zero_division=0),
        "f1": f1_score(y_test, test_pred, zero_division=0),
        "n_features": len(final_features),
    },
    {
        "run": "set2_prediabetes_focused",
        "model": best_model_name_pf,
        "roc_auc": roc_auc_score(y_test_pf, test_proba_pf),
        "avg_precision": average_precision_score(y_test_pf, test_proba_pf),
        "precision": precision_score(y_test_pf, test_pred_pf, zero_division=0),
        "recall": recall_score(y_test_pf, test_pred_pf, zero_division=0),
        "f1": f1_score(y_test_pf, test_pred_pf, zero_division=0),
        "n_features": len(prediabetes_focused_final_features),
    },
    {
        "run": "set3_final_quiz_6_features",
        "model": best_model_name_fq,
        "roc_auc": roc_auc_score(y_test_fq, test_proba_fq),
        "avg_precision": average_precision_score(y_test_fq, test_proba_fq),
        "precision": precision_score(y_test_fq, test_pred_fq, zero_division=0),
        "recall": recall_score(y_test_fq, test_pred_fq, zero_division=0),
        "f1": f1_score(y_test_fq, test_pred_fq, zero_division=0),
        "n_features": len(final_quiz_available),
    }
])

comparison_test_fq.sort_values("avg_precision", ascending=False)

                          run                       model   roc_auc  avg_precision  precision    recall        f1  n_features
0      set1_all_questionnaire                      logreg  0.697686       0.184407   0.162551  0.580882  0.254019          73
1    set2_prediabetes_focused  logreg_prediabetes_focused  0.666763       0.160069   0.143317  0.654412  0.235139          24
2  set3_final_quiz_6_features           logreg_final_quiz  0.654298       0.147373   0.127660  0.661765  0.214031           6

In [152]:
threshold_rows_fq = []

for t in [0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.50]:
    pred_t = (test_proba_fq >= t).astype(int)
    threshold_rows_fq.append({
        "threshold": t,
        "precision": precision_score(y_test_fq, pred_t, zero_division=0),
        "recall": recall_score(y_test_fq, pred_t, zero_division=0),
        "f1": f1_score(y_test_fq, pred_t, zero_division=0),
        "positives_predicted": int(pred_t.sum())
    })

threshold_df_fq = pd.DataFrame(threshold_rows_fq).sort_values("f1", ascending=False)
threshold_df_fq

   threshold  precision    recall        f1  positives_predicted
6       0.50   0.127660  0.661765  0.214031                  705
5       0.40   0.113503  0.852941  0.200345                 1022
4       0.35   0.108062  0.926471  0.193548                 1166
3       0.30   0.102482  0.941176  0.184838                 1249
2       0.25   0.097688  0.963235  0.177387                 1341
1       0.20   0.095881  0.992647  0.174870                 1408
0       0.15   0.093278  1.000000  0.170640                 1458

In [59]:
fq_audit_path = OUTPUT_DIR / "prediabetes_final_quiz_feature_audit.csv"
fq_univariate_path = OUTPUT_DIR / "prediabetes_final_quiz_univariate_ranking.csv"
fq_perm_path = OUTPUT_DIR / "prediabetes_final_quiz_permutation_importance.csv"
fq_combined_path = OUTPUT_DIR / "prediabetes_final_quiz_candidates.csv"
fq_comparison_path = OUTPUT_DIR / "prediabetes_final_quiz_vs_other_runs_comparison.csv"
fq_threshold_path = OUTPUT_DIR / "prediabetes_final_quiz_threshold_scan.csv"

final_quiz_audit_df.to_csv(fq_audit_path, index=False)
fq_univariate_df.to_csv(fq_univariate_path, index=False)
perm_df_fq.to_csv(fq_perm_path, index=False)
combined_df_fq.to_csv(fq_combined_path, index=False)
comparison_test_fq.to_csv(fq_comparison_path, index=False)
threshold_df_fq.to_csv(fq_threshold_path, index=False)

print("Saved:")
print(fq_audit_path.resolve())
print(fq_univariate_path.resolve())
print(fq_perm_path.resolve())
print(fq_combined_path.resolve())
print(fq_comparison_path.resolve())
print(fq_threshold_path.resolve())

Saved:
C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes\prediabetes_final_quiz_feature_audit.csv
C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes\prediabetes_final_quiz_univariate_ranking.csv
C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes\prediabetes_final_quiz_permutation_importance.csv
C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes\prediabetes_final_quiz_candidates.csv
C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes\prediabetes_final_quiz_vs_other_runs_comparison.csv
C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes\prediabetes_final_quiz_threshold_scan.csv

# Age & Gender