# Prediabetes Modeling Notebook (clean rebuild)

Dieses Notebook ist eine saubere, leakage-bewusste Neuauflage für dein Prediabetes-Modell.

Es enthält:
- Daten laden
- Quiz-/Demografie-/Medikamenten-/Labor-Featureblöcke
- **Screening-Modell** ohne lab-nahe Leakage-Features
- **Augmented-Modell** mit optionalen Labs
- **Logistic Regression mit Scaling + Hyperparameter-Tuning**
- saubere Evaluation auf Holdout-Testset
- Koeffizienten- und Threshold-Analyse

> Passe bei Bedarf nur `DATA_PATH`, `TARGET` und einzelne Featurelisten an.

In [32]:

import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
import re
import json
import numpy as np
import pandas as pd

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    RepeatedStratifiedKFold,
)
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
)
from sklearn.linear_model import LogisticRegression

In [33]:

# =========================
# Config
# =========================
DATA_PATH = Path("../data/processed/nhanes_merged_adults_final.csv")
OUTPUT_DIR = Path("../data/processed/model_outputs_prediabetes_rebuild")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

TARGET = "prediabetes"
RANDOM_STATE = 42
TEST_SIZE = 0.20

# Optional: wenn du nur Erwachsene ab 18 willst
MIN_AGE = 18

print("DATA_PATH:", DATA_PATH.resolve())
print("OUTPUT_DIR:", OUTPUT_DIR.resolve())
print("TARGET:", TARGET)

DATA_PATH: C:\Users\Philipp\AIBootcamp\halfFull\data\processed\nhanes_merged_adults_final.csv
OUTPUT_DIR: C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes_rebuild
TARGET: prediabetes

In [34]:

df = pd.read_csv(DATA_PATH, low_memory=False)

assert TARGET in df.columns, f"{TARGET} not found in dataframe."

if "age_years" in df.columns:
    df = df.loc[df["age_years"].fillna(-1) >= MIN_AGE].copy()

print("Shape:", df.shape)
print("Target distribution incl. NaN:")
print(df[TARGET].value_counts(dropna=False).sort_index())
print()
print("Target prevalence incl. NaN:")
print(df[TARGET].value_counts(normalize=True, dropna=False).sort_index().round(4))

Shape: (7437, 878)
Target distribution incl. NaN:
prediabetes
0    6755
1     682
Name: count, dtype: int64

Target prevalence incl. NaN:
prediabetes
0    0.9083
1    0.0917
Name: proportion, dtype: float64

In [35]:

overview = pd.DataFrame({
    "feature": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "missing_pct": (df.isna().mean().values * 100).round(2),
    "n_unique": [df[c].nunique(dropna=True) for c in df.columns],
}).sort_values(["missing_pct", "n_unique", "feature"], ascending=[False, True, True])

overview.head(30)

,feature,dtype,missing_pct,n_unique
436,LBXIGGA_cytomegalovirus_cmv_igg_avidity,float64,100.00,0
434,LBXIGG_cytomegalovirus_cmv_igg,float64,100.00,0
435,LBXIGM_cytomegalovirus_cmv_igm,float64,100.00,0
166,mcq149___menstrual_periods_started_yet?,float64,100.00,0
167,mcq151___age_in_years_at_first_menstrual_period,float64,100.00,0
295,smd630___age_first_smoked_whole_cigarette,float64,100.00,0
294,smq621___cigarettes_smoked_in_entire_life,float64,100.00,0
357,medication_21,str,99.97,2
358,medication_22,str,99.97,2
356,medication_20,str,99.96,3
203,mcq230c___what_kind_of_cancer_third_mention,float64,99.93,4
355,medication_19,str,99.93,5
189,mcq510b___liver_condition_non_alcoholic_fatty_...,float64,99.92,1
354,medication_18,str,99.91,7
100,cdq009g___pain_in_left_arm,float64,99.85,1
96,cdq009c___pain_in_neck,float64,99.84,1
353,medication_17,str,99.84,12
192,mcq510e___liver_condition_autoimmune,float64,99.83,1
94,cdq009a___pain_in_right_arm,float64,99.81,1
352,medication_16,str,99.76,18
190,mcq510c___liver_condition_alcoholic_liver_disease,float64,99.70,1
233,rhq020___age_range_at_first_menstrual_period,float64,99.68,5
323,whd080u___had_weight_loss_surgery_to_lose_weight,float64,99.66,1
351,medication_15,str,99.66,23
237,rhq070___age_range_at_last_menstrual_period,float64,99.61,8
202,mcq230b___what_kind_of_cancer_second_mention,float64,99.61,15
684,URDTIME3_minutes_b_w_urine_2_urine_3,float64,99.61,25
682,URXVOL3_the_volume_of_urine_collection_3_ml,float64,99.61,26
683,URDFLOW3_urine_3_flow_rate_ml_min,float64,99.61,29
350,medication_14,str,99.53,26

In [36]:
# %% Clean questionnaire-style special response codes
import numpy as np
import pandas as pd

# Häufige NHANES-Sondercodes für "Refused", "Don't know", etc.
SPECIAL_MISSING_CODES = {
    7, 9,
    77, 99,
    777, 999,
    7777, 9999,
    77777, 99999,
}

def replace_special_codes_with_nan(series: pd.Series) -> pd.Series:
    """
    Replaces common NHANES-style special response codes with NaN.
    Works for numeric columns; leaves other columns unchanged.
    """
    if not pd.api.types.is_numeric_dtype(series):
        return series
    return series.replace(list(SPECIAL_MISSING_CODES), np.nan)

# Optional: nur auf Fragebogen-/survey-nahe Spalten anwenden
# Passe die Präfixe bei Bedarf an dein Projekt an.
QUESTIONNAIRE_LIKE_PREFIXES = (
    "slq", "mcq", "paq", "whq", "smq", "dpq", "huq", "kiq", "hsq", "cdq"
)

questionnaire_like_cols = [
    c for c in df.columns
    if c.lower().startswith(QUESTIONNAIRE_LIKE_PREFIXES)
]

print("Questionnaire-like columns to clean:", len(questionnaire_like_cols))

df[questionnaire_like_cols] = df[questionnaire_like_cols].apply(replace_special_codes_with_nan)

print("Done. Special response codes replaced with NaN in questionnaire-like columns.")

Questionnaire-like columns to clean: 116
Done. Special response codes replaced with NaN in questionnaire-like columns.

In [37]:
# %% Sanity check for special code cleanup
sample_cols = [
    c for c in [
        "slq030___how_often_do_you_snore?",
        "mcq300c___close_relative_had_diabetes",
        "paq650___vigorous_recreational_activities",
        "whq040___like_to_weigh_more,_less_or_same",
    ]
    if c in df.columns
]

for col in sample_cols:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False).sort_index())

slq030___how_often_do_you_snore?
slq030___how_often_do_you_snore?
0.0    1934
1.0    1868
2.0    1243
3.0    1960
NaN     432
Name: count, dtype: int64

mcq300c___close_relative_had_diabetes
mcq300c___close_relative_had_diabetes
1.0    3304
2.0    3582
NaN     551
Name: count, dtype: int64

paq650___vigorous_recreational_activities
paq650___vigorous_recreational_activities
1.0    2216
2.0    5221
Name: count, dtype: int64

whq040___like_to_weigh_more,_less_or_same
whq040___like_to_weigh_more,_less_or_same
1.0     772
2.0    4697
3.0    1963
NaN       5
Name: count, dtype: int64

## 1) Featureblöcke definieren

Hier steuerst du, was in welches Modell geht.

**Wichtig:**
- `SCREENING_LAB_COLS` sollte nur Labs enthalten, die du wirklich für eine produktseitige optionale Verbesserung verwenden willst.
- **Leakage-nahe Features** wie Nüchternglukose oder HbA1c gehören **nicht** ins Screening-Modell, wenn dein Target daraus abgeleitet ist.

In [38]:

# =========================
# Leakage / Ausschlüsse
# =========================
LEAKAGE_COLS = [
    TARGET,
    "diabetes",
    "diq010___doctor_told_you_have_diabetes",
    "diq160___ever_told_you_have_prediabetes",
    "rxd_disease_list",
]

# Falls dein Target aus Glukose/HbA1c definiert wurde:
LEAKAGE_LAB_COLS = [
    "fasting_glucose_mg_dl",
    "hba1c_pct",
]

QUESTIONNAIRE_PREFIXES = (
    "slq", "sld", "dpq", "paq", "huq", "mcq", "bpq", "kiq", "cdq", "smq", "alq",
    "whq", "rhq"
)

EXCLUDE_PATTERNS = [
    r"^seqn$",
    r"cluster",
    r"stratum",
    r"weight",
    r"sample_weight",
    r"survey_",
    r"^rxd",
    r"medication_",
    r"drug",
    r"icd",
    r"diagnosis",
    r"lab",
    r"exam",
    r"liver_",
    r"fatigue_binary",
]

# Optional: harte manuelle Drops
MANUAL_DROP_COLS = [
    # "huq051___#times_receive_healthcare_over_past_year",
]

# =========================
# Blöcke
# =========================
DEMO_COLS = [
    "age_years",
    "gender",
]

MED_COLS = [
    "med_count",
]

# Optional nutzbare Check-up-nahe Labs ohne direkte Glukose-Labels
SCREENING_LAB_COLS = [
    "triglycerides_mg_dl",
    "hdl_cholesterol_mg_dl",
    "total_cholesterol_mg_dl",
    "uacr_mg_g",
]

# Optionales augmentiertes Modell mit lab-nahen Glukosemarkern
AUGMENTED_LAB_COLS = [
    "fasting_glucose_mg_dl",
    "hba1c_pct",
    "triglycerides_mg_dl",
    "hdl_cholesterol_mg_dl",
    "total_cholesterol_mg_dl",
    "uacr_mg_g",
]

# Optional: explizite Focused-Features aus deinem Quiz
FOCUSED_QUIZ_COLS = [
    "cos_weekday_bedtime",
    "sleep_hours_weekend",
    "slq030___how_often_do_you_snore?",
    "mcq300c___close_relative_had_diabetes",
    "paq650___vigorous_recreational_activities",
    "whq040___like_to_weigh_more,_less_or_same",
]

In [39]:

def has_allowed_prefix(col: str, prefixes=QUESTIONNAIRE_PREFIXES) -> bool:
    return col.lower().startswith(prefixes)

def matches_any_pattern(col: str, patterns) -> bool:
    col_low = col.lower()
    return any(re.search(p, col_low) for p in patterns)

def infer_feature_type(series: pd.Series) -> str:
    s = series.dropna()
    if s.empty:
        return "categorical"
    if pd.api.types.is_numeric_dtype(s):
        unique_vals = s.nunique(dropna=True)
        vals = set(pd.Series(s).unique())
        if vals.issubset({0, 1}) and len(vals) <= 2:
            return "categorical"
        if unique_vals <= 10:
            return "categorical"
        return "numeric"
    return "categorical"

def dedupe_keep_order(items):
    seen = set()
    out = []
    for item in items:
        if item not in seen:
            out.append(item)
            seen.add(item)
    return out

def existing_cols(cols, df):
    return [c for c in cols if c in df.columns]

def missing_cols(cols, df):
    return [c for c in cols if c not in df.columns]

In [40]:

# =========================
# Questionnaire candidate pool
# =========================
candidate_quiz_cols = []

for col in df.columns:
    if col in LEAKAGE_COLS:
        continue
    if col in MANUAL_DROP_COLS:
        continue
    if not has_allowed_prefix(col):
        continue
    if matches_any_pattern(col, EXCLUDE_PATTERNS):
        continue
    candidate_quiz_cols.append(col)

print("Questionnaire candidates:", len(candidate_quiz_cols))
print(candidate_quiz_cols[:80])

Questionnaire candidates: 142
['alq111___ever_had_a_drink_of_any_kind_of_alcohol', 'alq121___past_12_mo_how_often_drink_alcoholic_bev', 'alq130___avg_#_alcoholic_drinks/day___past_12_mos', 'alq142___#_days_have_4_or_5_drinks/past_12_mos', 'alq270___#_times_4_5_drinks_in_2hrs/past_12_mos', 'alq280___#_times_8+_drinks_in_1_day/past_12_mos', 'alq290___#_times_12+_drinks_in_1_day/past_12_mos', 'alq151___ever_have_4/5_or_more_drinks_every_day?', 'alq170___past_30_days_#_times_4_5_drinks_on_an_oc', 'bpq020___ever_told_you_had_high_blood_pressure', 'bpq030___told_had_high_blood_pressure___2+_times', 'bpq040a___taking_prescription_for_hypertension', 'bpq050a___now_taking_prescribed_medicine_for_hbp', 'bpq080___doctor_told_you___high_cholesterol_level', 'bpq060___ever_had_blood_cholesterol_checked', 'bpq070___when_blood_cholesterol_last_checked', 'bpq090d___told_to_take_prescriptn_for_cholesterol', 'bpq100d___now_taking_prescribed_medicine', 'cdq001___sp_ever_had_pain_or_discomfort_in_chest', 'cdq002___sp_get_it_walking_uphill_or_in_a_hurry', 'cdq003___during_an_ordinary_pace_on_level_ground', 'cdq004___if_so_does_sp_continue_or_slow_down', 'cdq005___does_standing_relieve_pain/discomfort', 'cdq006___how_soon_is_the_pain_relieved', 'cdq009a___pain_in_right_arm', 'cdq009b___pain_in_right_chest', 'cdq009c___pain_in_neck', 'cdq009d___pain_in_upper_sternum', 'cdq009e___pain_in_lower_sternum', 'cdq009f___pain_in_left_chest', 'cdq009g___pain_in_left_arm', 'cdq008___severe_pain_in_chest_more_than_half_hour', 'cdq010___shortness_of_breath_on_stairs/inclines', 'dpq040___feeling_tired_or_having_little_energy', 'huq010___general_health_condition', 'huq030___routine_place_to_go_for_healthcare', 'huq051___#times_receive_healthcare_over_past_year', 'huq071___overnight_hospital_patient_in_last_year', 'huq090___seen_mental_health_professional/past_yr', 'kiq022___ever_told_you_had_weak/failing_kidneys?', 'kiq025___received_dialysis_in_past_12_months?', 'kiq026___ever_had_kidney_stones?', 'kiq029___pass_kidney_stone_in_past_12_months?', 'kiq005___how_often_have_urinary_leakage?', 'kiq010___how_much_urine_lose_each_time?', 'kiq042___leak_urine_during_physical_activities?', 'kiq430___how_frequently_does_this_occur?', 'kiq044___urinated_before_reaching_the_toilet?', 'kiq450___how_frequently_does_this_occur?', 'kiq046___leak_urine_during_nonphysical_activities', 'kiq470___how_frequently_does_this_occur?', 'kiq050___how_much_did_urine_leakage_bother_you?', 'kiq052___how_much_were_daily_activities_affected?', 'kiq480___how_many_times_urinate_in_night?', 'mcq010___ever_been_told_you_have_asthma', 'mcq025___age_when_first_had_asthma', 'mcq035___still_have_asthma', 'mcq040___had_asthma_attack_in_past_year', 'mcq050___emergency_care_visit_for_asthma/past_yr', 'mcq053___taking_treatment_for_anemia/past_3_mos', 'mcq092___ever_receive_blood_transfusion', 'mcq149___menstrual_periods_started_yet?', 'mcq151___age_in_years_at_first_menstrual_period', 'mcq160a___ever_told_you_had_arthritis', 'mcq195___which_type_of_arthritis_was_it?', 'mcq160b___ever_told_you_had_congestive_heart_failure', 'mcq160c___ever_told_you_had_coronary_heart_disease', 'mcq160d___ever_told_you_had_angina', 'mcq160e___ever_told_you_had_heart_attack', 'mcq160f___ever_told_you_had_stroke', 'mcq160m___ever_told_you_had_thyroid_problem', 'mcq170m___still_have_thyroid_problem', 'mcq160p___ever_told_you_had_copd_emphysema', 'mcq520___abdominal_pain_during_past_12_months?', 'mcq530___where_was_the_most_uncomfortable_pain', 'mcq540___ever_seen_a_dr_about_this_pain', 'mcq550___has_dr_ever_said_you_have_gallstones', 'mcq560___ever_had_gallbladder_surgery?', 'mcq570___age_when_1st_had_gallbladder_surgery?', 'mcq220___ever_told_you_had_cancer_or_malignancy']

In [41]:

# Schnell-Audit
audit_df = pd.DataFrame({
    "feature": candidate_quiz_cols,
    "missing_pct": [round(df[c].isna().mean() * 100, 2) for c in candidate_quiz_cols],
    "n_unique": [df[c].nunique(dropna=True) for c in candidate_quiz_cols],
    "dtype": [str(df[c].dtype) for c in candidate_quiz_cols],
}).sort_values(["missing_pct", "n_unique", "feature"], ascending=[False, True, True])

audit_df.head(50)

,feature,missing_pct,n_unique,dtype
30,cdq009g___pain_in_left_arm,100.00,0,float64
61,mcq149___menstrual_periods_started_yet?,100.00,0,float64
62,mcq151___age_in_years_at_first_menstrual_period,100.00,0,float64
140,smq621___cigarettes_smoked_in_entire_life,100.00,0,float64
82,mcq230c___what_kind_of_cancer_third_mention,99.93,4,float64
26,cdq009c___pain_in_neck,99.84,1,float64
24,cdq009a___pain_in_right_arm,99.81,1,float64
103,rhq020___age_range_at_first_menstrual_period,99.68,5,float64
106,rhq070___age_range_at_last_menstrual_period,99.61,8,float64
81,mcq230b___what_kind_of_cancer_second_mention,99.61,15,float64
25,cdq009b___pain_in_right_chest,99.41,1,float64
121,rhq542b___hormone_patches_used,99.31,1,float64
28,cdq009e___pain_in_lower_sternum,99.23,1,float64
29,cdq009f___pain_in_left_chest,98.74,1,float64
122,rhq542c___hormone_cream/suppository/injection_...,98.56,1,float64
27,cdq009d___pain_in_upper_sternum,98.23,1,float64
40,kiq025___received_dialysis_in_past_12_months?,97.50,2,float64
120,rhq542a___hormone_pills_used,97.03,1,float64
123,rhq554___use_hormone_pills_w/estrogen_only,97.03,3,float64
124,rhq570___used_estrogen/progestin_combo_pills,97.03,3,float64
116,rhq200___now_breastfeeding_a_child?,96.84,2,float64
115,rhq197___how_many_months_ago_have_baby?,96.81,24,float64
118,rhq332___age_when_both_ovaries_removed,96.72,41,float64
23,cdq006___how_soon_is_the_pain_relieved,96.22,2,float64
22,cdq005___does_standing_relieve_pain/discomfort,95.40,2,float64
21,cdq004___if_so_does_sp_continue_or_slow_down,94.82,2,float64
80,mcq230a___what_kind_of_cancer_first_mention,94.68,26,float64
50,kiq470___how_frequently_does_this_occur?,94.63,4,float64
20,cdq003___during_an_ordinary_pace_on_level_ground,94.55,2,float64
78,mcq570___age_when_1st_had_gallbladder_surgery?,92.24,50,float64
42,kiq029___pass_kidney_stone_in_past_12_months?,92.11,2,float64
71,mcq170m___still_have_thyroid_problem,91.78,2,float64
57,mcq040___had_asthma_attack_in_past_year,90.17,2,float64
58,mcq050___emergency_care_visit_for_asthma/past_yr,90.13,2,float64
6,alq290___#_times_12+_drinks_in_1_day/past_12_mos,88.14,12,float64
138,smq078___how_soon_after_waking_do_you_smoke,85.63,6,float64
55,mcq025___age_when_first_had_asthma,84.89,61,float64
64,mcq195___which_type_of_arthritis_was_it?,84.15,4,float64
19,cdq002___sp_get_it_walking_uphill_or_in_a_hurry,83.93,3,float64
31,cdq008___severe_pain_in_chest_more_than_half_hour,83.86,2,float64
56,mcq035___still_have_asthma,83.51,2,float64
136,smq050q___how_long_since_quit_smoking_cigarettes,83.51,47,float64
48,kiq450___how_frequently_does_this_occur?,82.75,4,float64
137,smq050u___unit_of_measure_(day/week/month/year),82.37,4,float64
105,rhq060___age_at_last_menstrual_period,81.34,44,float64
97,paq640___number_of_days_walk_or_bicycle,81.08,6,float64
46,kiq430___how_frequently_does_this_occur?,81.07,4,float64
17,bpq100d___now_taking_prescribed_medicine,80.99,3,float64
139,smq670___tried_to_quit_smoking,80.26,2,float64
74,mcq530___where_was_the_most_uncomfortable_pain,79.45,3,float64

In [42]:

# =========================
# Filter-Regeln für Questionnaire-Features
# =========================
MAX_MISSING_PCT = 60.0
MIN_NON_NULL = 500
MIN_UNIQUE = 2

filtered_quiz_cols = []
drop_reasons = {}

for col in candidate_quiz_cols:
    missing_pct = df[col].isna().mean() * 100
    non_null = df[col].notna().sum()
    nunique = df[col].nunique(dropna=True)

    if missing_pct > MAX_MISSING_PCT:
        drop_reasons[col] = "too_missing"
        continue
    if non_null < MIN_NON_NULL:
        drop_reasons[col] = "too_few_non_null"
        continue
    if nunique < MIN_UNIQUE:
        drop_reasons[col] = "constant_or_near_constant"
        continue

    filtered_quiz_cols.append(col)

print("Filtered questionnaire features:", len(filtered_quiz_cols))
print("Dropped:", len(drop_reasons))
pd.Series(drop_reasons).value_counts()

Filtered questionnaire features: 71
Dropped: 71

too_missing    71
Name: count, dtype: int64

## 2) Modellvarianten bauen

Wir erzeugen vier Varianten:

1. `broad_quiz_only`
2. `broad_quiz_demo_med`
3. `focused_quiz_demo_med`
4. `focused_quiz_demo_med_augmented_labs`

So siehst du sauber, welcher Block wirklich hilft.

In [43]:

feature_sets = {
    "broad_quiz_only": dedupe_keep_order(
        existing_cols(filtered_quiz_cols, df)
    ),
    "broad_quiz_demo_med": dedupe_keep_order(
        existing_cols(filtered_quiz_cols, df)
        + existing_cols(DEMO_COLS, df)
        + existing_cols(MED_COLS, df)
    ),
    "focused_quiz_demo_med": dedupe_keep_order(
        existing_cols(FOCUSED_QUIZ_COLS, df)
        + existing_cols(DEMO_COLS, df)
        + existing_cols(MED_COLS, df)
    ),
    "focused_quiz_demo_med_screening_labs": dedupe_keep_order(
        existing_cols(FOCUSED_QUIZ_COLS, df)
        + existing_cols(DEMO_COLS, df)
        + existing_cols(MED_COLS, df)
        + existing_cols(SCREENING_LAB_COLS, df)
    ),
    "focused_quiz_demo_med_augmented_labs": dedupe_keep_order(
        existing_cols(FOCUSED_QUIZ_COLS, df)
        + existing_cols(DEMO_COLS, df)
        + existing_cols(MED_COLS, df)
        + existing_cols(AUGMENTED_LAB_COLS, df)
    ),
}

for name, cols in feature_sets.items():
    print(f"\n{name}: {len(cols)} features")
    print(cols[:25])

broad_quiz_only: 71 features
['alq111___ever_had_a_drink_of_any_kind_of_alcohol', 'alq121___past_12_mo_how_often_drink_alcoholic_bev', 'alq130___avg_#_alcoholic_drinks/day___past_12_mos', 'alq142___#_days_have_4_or_5_drinks/past_12_mos', 'alq151___ever_have_4/5_or_more_drinks_every_day?', 'alq170___past_30_days_#_times_4_5_drinks_on_an_oc', 'bpq020___ever_told_you_had_high_blood_pressure', 'bpq080___doctor_told_you___high_cholesterol_level', 'bpq060___ever_had_blood_cholesterol_checked', 'bpq070___when_blood_cholesterol_last_checked', 'bpq090d___told_to_take_prescriptn_for_cholesterol', 'cdq001___sp_ever_had_pain_or_discomfort_in_chest', 'cdq010___shortness_of_breath_on_stairs/inclines', 'dpq040___feeling_tired_or_having_little_energy', 'huq010___general_health_condition', 'huq030___routine_place_to_go_for_healthcare', 'huq051___#times_receive_healthcare_over_past_year', 'huq071___overnight_hospital_patient_in_last_year', 'huq090___seen_mental_health_professional/past_yr', 'kiq022___ever_told_you_had_weak/failing_kidneys?', 'kiq026___ever_had_kidney_stones?', 'kiq005___how_often_have_urinary_leakage?', 'kiq042___leak_urine_during_physical_activities?', 'kiq044___urinated_before_reaching_the_toilet?', 'kiq046___leak_urine_during_nonphysical_activities']

broad_quiz_demo_med: 74 features
['alq111___ever_had_a_drink_of_any_kind_of_alcohol', 'alq121___past_12_mo_how_often_drink_alcoholic_bev', 'alq130___avg_#_alcoholic_drinks/day___past_12_mos', 'alq142___#_days_have_4_or_5_drinks/past_12_mos', 'alq151___ever_have_4/5_or_more_drinks_every_day?', 'alq170___past_30_days_#_times_4_5_drinks_on_an_oc', 'bpq020___ever_told_you_had_high_blood_pressure', 'bpq080___doctor_told_you___high_cholesterol_level', 'bpq060___ever_had_blood_cholesterol_checked', 'bpq070___when_blood_cholesterol_last_checked', 'bpq090d___told_to_take_prescriptn_for_cholesterol', 'cdq001___sp_ever_had_pain_or_discomfort_in_chest', 'cdq010___shortness_of_breath_on_stairs/inclines', 'dpq040___feeling_tired_or_having_little_energy', 'huq010___general_health_condition', 'huq030___routine_place_to_go_for_healthcare', 'huq051___#times_receive_healthcare_over_past_year', 'huq071___overnight_hospital_patient_in_last_year', 'huq090___seen_mental_health_professional/past_yr', 'kiq022___ever_told_you_had_weak/failing_kidneys?', 'kiq026___ever_had_kidney_stones?', 'kiq005___how_often_have_urinary_leakage?', 'kiq042___leak_urine_during_physical_activities?', 'kiq044___urinated_before_reaching_the_toilet?', 'kiq046___leak_urine_during_nonphysical_activities']

focused_quiz_demo_med: 7 features
['slq030___how_often_do_you_snore?', 'mcq300c___close_relative_had_diabetes', 'paq650___vigorous_recreational_activities', 'whq040___like_to_weigh_more,_less_or_same', 'age_years', 'gender', 'med_count']

focused_quiz_demo_med_screening_labs: 11 features
['slq030___how_often_do_you_snore?', 'mcq300c___close_relative_had_diabetes', 'paq650___vigorous_recreational_activities', 'whq040___like_to_weigh_more,_less_or_same', 'age_years', 'gender', 'med_count', 'triglycerides_mg_dl', 'hdl_cholesterol_mg_dl', 'total_cholesterol_mg_dl', 'uacr_mg_g']

focused_quiz_demo_med_augmented_labs: 12 features
['slq030___how_often_do_you_snore?', 'mcq300c___close_relative_had_diabetes', 'paq650___vigorous_recreational_activities', 'whq040___like_to_weigh_more,_less_or_same', 'age_years', 'gender', 'med_count', 'fasting_glucose_mg_dl', 'triglycerides_mg_dl', 'hdl_cholesterol_mg_dl', 'total_cholesterol_mg_dl', 'uacr_mg_g']

In [44]:

# Transparenz: welche erwarteten Features fehlen?
expected_map = {
    "DEMO_COLS": DEMO_COLS,
    "MED_COLS": MED_COLS,
    "SCREENING_LAB_COLS": SCREENING_LAB_COLS,
    "AUGMENTED_LAB_COLS": AUGMENTED_LAB_COLS,
    "FOCUSED_QUIZ_COLS": FOCUSED_QUIZ_COLS,
}

missing_report = {
    block: missing_cols(cols, df)
    for block, cols in expected_map.items()
}

missing_report

{'DEMO_COLS': [],
 'MED_COLS': [],
 'SCREENING_LAB_COLS': [],
 'AUGMENTED_LAB_COLS': ['hba1c_pct'],
 'FOCUSED_QUIZ_COLS': ['cos_weekday_bedtime', 'sleep_hours_weekend']}

In [45]:

# =========================
# Gemeinsamer Holdout-Split für alle Modellvarianten
# =========================
base_df = df[[TARGET]].copy()
mask = base_df[TARGET].notna()
base_index = df.index[mask]

y_all = df.loc[base_index, TARGET].astype(int).copy()

train_idx, test_idx = train_test_split(
    base_index,
    test_size=TEST_SIZE,
    stratify=y_all,
    random_state=RANDOM_STATE,
)

print("Train n:", len(train_idx))
print("Test n:", len(test_idx))
print("Train prevalence:", round(df.loc[train_idx, TARGET].mean(), 4))
print("Test prevalence:", round(df.loc[test_idx, TARGET].mean(), 4))

Train n: 5949
Test n: 1488
Train prevalence: 0.0918
Test prevalence: 0.0914

In [46]:

def build_xy(df, feature_cols, target, train_idx, test_idx):
    model_df = df[[target] + feature_cols].copy()
    model_df = model_df.loc[model_df[target].notna()].copy()

    X_train = model_df.loc[train_idx, feature_cols].copy()
    X_test = model_df.loc[test_idx, feature_cols].copy()
    y_train = model_df.loc[train_idx, target].astype(int).copy()
    y_test = model_df.loc[test_idx, target].astype(int).copy()

    numeric_features = [c for c in feature_cols if infer_feature_type(X_train[c]) == "numeric"]
    categorical_features = [c for c in feature_cols if c not in numeric_features]

    return X_train, X_test, y_train, y_test, numeric_features, categorical_features

def build_logreg_preprocessor(numeric_features, categorical_features):
    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median", add_indicator=True)),
        ("scaler", StandardScaler()),
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore")),
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, numeric_features),
            ("cat", categorical_transformer, categorical_features),
        ],
        remainder="drop",
    )
    return preprocessor

def evaluate_predictions(y_true, y_proba, threshold=0.50):
    y_pred = (y_proba >= threshold).astype(int)
    return {
        "roc_auc": roc_auc_score(y_true, y_proba),
        "avg_precision": average_precision_score(y_true, y_proba),
        "precision": precision_score(y_true, y_pred, zero_division=0),
        "recall": recall_score(y_true, y_pred, zero_division=0),
        "f1": f1_score(y_true, y_pred, zero_division=0),
        "confusion_matrix": confusion_matrix(y_true, y_pred),
        "classification_report": classification_report(y_true, y_pred, zero_division=0),
    }

def run_tuned_logreg(
    X_train,
    X_test,
    y_train,
    y_test,
    numeric_features,
    categorical_features,
    model_name="logreg_tuned",
    scoring="average_precision",
):
    preprocessor = build_logreg_preprocessor(numeric_features, categorical_features)

    pipe = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("model", LogisticRegression(
            max_iter=5000,
            class_weight="balanced",
            random_state=RANDOM_STATE,
        )),
    ])

    param_grid = [
        {
            "model__solver": ["liblinear"],
            "model__penalty": ["l1", "l2"],
            "model__C": [0.01, 0.1, 1, 3, 10],
        },
        {
            "model__solver": ["saga"],
            "model__penalty": ["l1", "l2"],
            "model__C": [0.01, 0.1, 1, 3, 10],
        },
    ]

    cv = RepeatedStratifiedKFold(
        n_splits=5,
        n_repeats=2,
        random_state=RANDOM_STATE,
    )

    grid = GridSearchCV(
        estimator=pipe,
        param_grid=param_grid,
        scoring=scoring,
        cv=cv,
        n_jobs=-1,
        verbose=1,
        refit=True,
    )

    grid.fit(X_train, y_train)

    best_model = grid.best_estimator_
    y_proba = best_model.predict_proba(X_test)[:, 1]
    metrics = evaluate_predictions(y_test, y_proba, threshold=0.50)

    result = {
        "model_name": model_name,
        "best_params": grid.best_params_,
        "cv_best_score": grid.best_score_,
        "numeric_features": numeric_features,
        "categorical_features": categorical_features,
        "best_estimator": best_model,
        "y_test_proba": y_proba,
        "y_test_true": y_test.values,
        **metrics,
    }
    return result

In [47]:

all_results = {}
comparison_rows = []

for model_name, feature_cols in feature_sets.items():
    print("=" * 90)
    print(model_name)
    print("=" * 90)

    X_train, X_test, y_train, y_test, numeric_features, categorical_features = build_xy(
        df=df,
        feature_cols=feature_cols,
        target=TARGET,
        train_idx=train_idx,
        test_idx=test_idx,
    )

    print("X_train shape:", X_train.shape)
    print("X_test shape:", X_test.shape)
    print("Numeric features:", len(numeric_features))
    print("Categorical features:", len(categorical_features))

    result = run_tuned_logreg(
        X_train=X_train,
        X_test=X_test,
        y_train=y_train,
        y_test=y_test,
        numeric_features=numeric_features,
        categorical_features=categorical_features,
        model_name=model_name,
        scoring="average_precision",
    )

    all_results[model_name] = result

    comparison_rows.append({
        "run": model_name,
        "n_features": len(feature_cols),
        "cv_best_score_avg_precision": round(result["cv_best_score"], 4),
        "roc_auc": round(result["roc_auc"], 4),
        "avg_precision": round(result["avg_precision"], 4),
        "precision": round(result["precision"], 4),
        "recall": round(result["recall"], 4),
        "f1": round(result["f1"], 4),
        "best_params": json.dumps(result["best_params"]),
    })

    print("\nBest params:", result["best_params"])
    print("CV best score (avg precision):", round(result["cv_best_score"], 4))
    print("Test ROC-AUC:", round(result["roc_auc"], 4))
    print("Test Average Precision:", round(result["avg_precision"], 4))
    print("Test Precision:", round(result["precision"], 4))
    print("Test Recall:", round(result["recall"], 4))
    print("Test F1:", round(result["f1"], 4))
    print("\nConfusion Matrix:")
    print(result["confusion_matrix"])

==========================================================================================
broad_quiz_only
==========================================================================================
X_train shape: (5949, 71)
X_test shape: (1488, 71)
Numeric features: 7
Categorical features: 64
Fitting 10 folds for each of 20 candidates, totalling 200 fits

Best params: {'model__C': 0.1, 'model__penalty': 'l1', 'model__solver': 'saga'}
CV best score (avg precision): 0.1914
Test ROC-AUC: 0.7282
Test Average Precision: 0.2023
Test Precision: 0.1616
Test Recall: 0.6618
Test F1: 0.2597

Confusion Matrix:
[[885 467]
 [ 46  90]]
==========================================================================================
broad_quiz_demo_med
==========================================================================================
X_train shape: (5949, 74)
X_test shape: (1488, 74)
Numeric features: 9
Categorical features: 65
Fitting 10 folds for each of 20 candidates, totalling 200 fits

Best params: {'model__C': 0.1, 'model__penalty': 'l1', 'model__solver': 'saga'}
CV best score (avg precision): 0.2038
Test ROC-AUC: 0.7265
Test Average Precision: 0.2053
Test Precision: 0.1576
Test Recall: 0.6397
Test F1: 0.2529

Confusion Matrix:
[[887 465]
 [ 49  87]]
==========================================================================================
focused_quiz_demo_med
==========================================================================================
X_train shape: (5949, 7)
X_test shape: (1488, 7)
Numeric features: 2
Categorical features: 5
Fitting 10 folds for each of 20 candidates, totalling 200 fits

Best params: {'model__C': 3, 'model__penalty': 'l2', 'model__solver': 'saga'}
CV best score (avg precision): 0.1496
Test ROC-AUC: 0.6569
Test Average Precision: 0.1438
Test Precision: 0.1361
Test Recall: 0.6765
Test F1: 0.2266

Confusion Matrix:
[[768 584]
 [ 44  92]]
==========================================================================================
focused_quiz_demo_med_screening_labs
==========================================================================================
X_train shape: (5949, 11)
X_test shape: (1488, 11)
Numeric features: 6
Categorical features: 5
Fitting 10 folds for each of 20 candidates, totalling 200 fits

Best params: {'model__C': 0.1, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
CV best score (avg precision): 0.1507
Test ROC-AUC: 0.6704
Test Average Precision: 0.1531
Test Precision: 0.1414
Test Recall: 0.6985
Test F1: 0.2351

Confusion Matrix:
[[775 577]
 [ 41  95]]
==========================================================================================
focused_quiz_demo_med_augmented_labs
==========================================================================================
X_train shape: (5949, 12)
X_test shape: (1488, 12)
Numeric features: 7
Categorical features: 5
Fitting 10 folds for each of 20 candidates, totalling 200 fits

Best params: {'model__C': 10, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
CV best score (avg precision): 0.1521
Test ROC-AUC: 0.6666
Test Average Precision: 0.1463
Test Precision: 0.139
Test Recall: 0.6765
Test F1: 0.2306

Confusion Matrix:
[[782 570]
 [ 44  92]]

In [58]:

comparison_df = pd.DataFrame(comparison_rows).sort_values(
    ["avg_precision", "roc_auc", "recall"],
    ascending=[False, False, False],
).reset_index(drop=True)

comparison_df

,run,n_features,cv_best_score_avg_precision,roc_auc,avg_precision,precision,recall,f1,best_params
0,broad_quiz_demo_med,74,0.2038,0.7265,0.2053,0.1576,0.6397,0.2529,"{""model__C"": 0.1, ""model__penalty"": ""l1"", ""mod..."
1,broad_quiz_only,71,0.1914,0.7282,0.2023,0.1616,0.6618,0.2597,"{""model__C"": 0.1, ""model__penalty"": ""l1"", ""mod..."
2,focused_quiz_demo_med_screening_labs,11,0.1507,0.6704,0.1531,0.1414,0.6985,0.2351,"{""model__C"": 0.1, ""model__penalty"": ""l1"", ""mod..."
3,focused_quiz_demo_med_augmented_labs,12,0.1521,0.6666,0.1463,0.1390,0.6765,0.2306,"{""model__C"": 10, ""model__penalty"": ""l2"", ""mode..."
4,focused_quiz_demo_med,7,0.1496,0.6569,0.1438,0.1361,0.6765,0.2266,"{""model__C"": 3, ""model__penalty"": ""l2"", ""model..."

In [49]:

comparison_path = OUTPUT_DIR / "prediabetes_model_comparison.csv"
comparison_df.to_csv(comparison_path, index=False)
print("Saved:", comparison_path.resolve())

Saved: C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes_rebuild\prediabetes_model_comparison.csv

## 3) Bestes Modell im Detail anschauen

In [60]:
# %% Coefficients for selected model (readable version)
best_estimator = selected_result["best_estimator"]
preprocessor = best_estimator.named_steps["preprocessor"]
model = best_estimator.named_steps["model"]

feature_names = preprocessor.get_feature_names_out()

coef_df = pd.DataFrame({
    "transformed_feature": feature_names,
    "coefficient": model.coef_[0],
})
coef_df["abs_coefficient"] = coef_df["coefficient"].abs()
coef_df = coef_df.sort_values("abs_coefficient", ascending=False).reset_index(drop=True)

coef_df["pretty_feature"] = coef_df["transformed_feature"].apply(prettify_transformed_feature_name)

coef_df_pretty = coef_df[
    ["pretty_feature", "coefficient", "abs_coefficient", "transformed_feature"]
].copy()

coef_df_pretty.head(40)

,pretty_feature,coefficient,abs_coefficient,transformed_feature
0,Weight preference / perception: Would like to ...,-0.455172,0.455172,"cat__whq040___like_to_weigh_more,_less_or_same..."
1,Weight preference / perception: Would like to ...,0.441803,0.441803,"cat__whq040___like_to_weigh_more,_less_or_same..."
2,Close relative had diabetes: No,-0.435246,0.435246,cat__mcq300c___close_relative_had_diabetes_2.0
3,Age (years),0.383804,0.383804,num__age_years
4,How often do you snore?: Never,-0.308296,0.308296,cat__slq030___how_often_do_you_snore?_0.0
5,Gender: Male,-0.260220,0.260220,cat__gender_Male
6,Urine albumin-creatinine ratio (UACR),-0.172598,0.172598,num__uacr_mg_g
7,How often do you snore?: Often,0.162030,0.162030,cat__slq030___how_often_do_you_snore?_3.0
8,HDL cholesterol,-0.135955,0.135955,num__hdl_cholesterol_mg_dl
9,Total cholesterol,0.074276,0.074276,num__total_cholesterol_mg_dl
10,Total cholesterol missing,-0.047138,0.047138,num__missingindicator_total_cholesterol_mg_dl
11,How often do you snore?: Rarely,-0.025627,0.025627,cat__slq030___how_often_do_you_snore?_1.0
12,Urine albumin-creatinine ratio (UACR) missing,-0.025450,0.025450,num__missingindicator_uacr_mg_g
13,Triglycerides,0.020288,0.020288,num__triglycerides_mg_dl
14,HDL cholesterol missing,-0.011250,0.011250,num__missingindicator_hdl_cholesterol_mg_dl
15,Triglycerides missing,0.000000,0.000000,num__missingindicator_triglycerides_mg_dl
16,Medication count,0.000000,0.000000,num__med_count
17,Close relative had diabetes: Yes,0.000000,0.000000,cat__mcq300c___close_relative_had_diabetes_1.0
18,How often do you snore?: Sometimes,0.000000,0.000000,cat__slq030___how_often_do_you_snore?_2.0
19,Vigorous recreational activities: No,0.000000,0.000000,cat__paq650___vigorous_recreational_activities...
20,Vigorous recreational activities: Yes,0.000000,0.000000,cat__paq650___vigorous_recreational_activities...
21,Weight preference / perception: Would like to ...,0.000000,0.000000,"cat__whq040___like_to_weigh_more,_less_or_same..."
22,Gender: Female,0.000000,0.000000,cat__gender_Female

In [61]:
# %% Make coefficient names more readable
import re

FEATURE_LABEL_MAP = {
    "age_years": "Age (years)",
    "gender": "Gender",
    "med_count": "Medication count",
    "triglycerides_mg_dl": "Triglycerides",
    "hdl_cholesterol_mg_dl": "HDL cholesterol",
    "total_cholesterol_mg_dl": "Total cholesterol",
    "uacr_mg_g": "Urine albumin-creatinine ratio (UACR)",
    "slq030___how_often_do_you_snore?": "How often do you snore?",
    "mcq300c___close_relative_had_diabetes": "Close relative had diabetes",
    "paq650___vigorous_recreational_activities": "Vigorous recreational activities",
    "whq040___like_to_weigh_more,_less_or_same": "Weight preference / perception",
}

# Optional: Antwortcodes für einzelne wichtige Features lesbarer machen
VALUE_LABEL_MAP = {
    "mcq300c___close_relative_had_diabetes": {
        "1.0": "Yes",
        "2.0": "No",
    },
    "paq650___vigorous_recreational_activities": {
        "1.0": "Yes",
        "2.0": "No",
    },
    "gender": {
        "Male": "Male",
        "Female": "Female",
    },
    # Diese Mappings musst du ggf. an NHANES-Codierung deiner Spalten anpassen
    "slq030___how_often_do_you_snore?": {
        "0.0": "Never",
        "1.0": "Rarely",
        "2.0": "Sometimes",
        "3.0": "Often",
        "4.0": "Almost always",
    },
    "whq040___like_to_weigh_more,_less_or_same": {
        "1.0": "Would like to weigh less",
        "2.0": "Would like to weigh more",
        "3.0": "Would like to stay the same",
    },
}

def prettify_transformed_feature_name(name: str) -> str:
    # Missing indicators
    if name.startswith("num__missingindicator_"):
        raw = name.replace("num__missingindicator_", "")
        pretty_raw = FEATURE_LABEL_MAP.get(raw, raw)
        return f"{pretty_raw} missing"

    # Numeric features
    if name.startswith("num__"):
        raw = name.replace("num__", "")
        return FEATURE_LABEL_MAP.get(raw, raw)

    # Categorical one-hot features
    if name.startswith("cat__"):
        raw = name.replace("cat__", "")

        # Split feature + category at last underscore
        if "_" in raw:
            feature_part, value_part = raw.rsplit("_", 1)
            pretty_feature = FEATURE_LABEL_MAP.get(feature_part, feature_part)
            pretty_value = VALUE_LABEL_MAP.get(feature_part, {}).get(value_part, value_part)
            return f"{pretty_feature}: {pretty_value}"

        return FEATURE_LABEL_MAP.get(raw, raw)

    return name

coef_df["pretty_feature"] = coef_df["transformed_feature"].apply(prettify_transformed_feature_name)

coef_df_pretty = coef_df[
    ["pretty_feature", "coefficient", "abs_coefficient", "transformed_feature"]
].copy()

coef_df_pretty.head(30)

,pretty_feature,coefficient,abs_coefficient,transformed_feature
0,Weight preference / perception: Would like to ...,-0.455172,0.455172,"cat__whq040___like_to_weigh_more,_less_or_same..."
1,Weight preference / perception: Would like to ...,0.441803,0.441803,"cat__whq040___like_to_weigh_more,_less_or_same..."
2,Close relative had diabetes: No,-0.435246,0.435246,cat__mcq300c___close_relative_had_diabetes_2.0
3,Age (years),0.383804,0.383804,num__age_years
4,How often do you snore?: Never,-0.308296,0.308296,cat__slq030___how_often_do_you_snore?_0.0
5,Gender: Male,-0.260220,0.260220,cat__gender_Male
6,Urine albumin-creatinine ratio (UACR),-0.172598,0.172598,num__uacr_mg_g
7,How often do you snore?: Often,0.162030,0.162030,cat__slq030___how_often_do_you_snore?_3.0
8,HDL cholesterol,-0.135955,0.135955,num__hdl_cholesterol_mg_dl
9,Total cholesterol,0.074276,0.074276,num__total_cholesterol_mg_dl
10,Total cholesterol missing,-0.047138,0.047138,num__missingindicator_total_cholesterol_mg_dl
11,How often do you snore?: Rarely,-0.025627,0.025627,cat__slq030___how_often_do_you_snore?_1.0
12,Urine albumin-creatinine ratio (UACR) missing,-0.025450,0.025450,num__missingindicator_uacr_mg_g
13,Triglycerides,0.020288,0.020288,num__triglycerides_mg_dl
14,HDL cholesterol missing,-0.011250,0.011250,num__missingindicator_hdl_cholesterol_mg_dl
15,Triglycerides missing,0.000000,0.000000,num__missingindicator_triglycerides_mg_dl
16,Medication count,0.000000,0.000000,num__med_count
17,Close relative had diabetes: Yes,0.000000,0.000000,cat__mcq300c___close_relative_had_diabetes_1.0
18,How often do you snore?: Sometimes,0.000000,0.000000,cat__slq030___how_often_do_you_snore?_2.0
19,Vigorous recreational activities: No,0.000000,0.000000,cat__paq650___vigorous_recreational_activities...
20,Vigorous recreational activities: Yes,0.000000,0.000000,cat__paq650___vigorous_recreational_activities...
21,Weight preference / perception: Would like to ...,0.000000,0.000000,"cat__whq040___like_to_weigh_more,_less_or_same..."
22,Gender: Female,0.000000,0.000000,cat__gender_Female

In [52]:
best_run = "focused_quiz_demo_med_screening_labs"
best_result = all_results[best_run]

In [53]:

#best_run = comparison_df.iloc[0]["run"]
best_result = all_results[best_run]

print("Best run:", best_run)
print("Best params:", best_result["best_params"])
print("ROC-AUC:", round(best_result["roc_auc"], 4))
print("Average Precision:", round(best_result["avg_precision"], 4))
print("Precision:", round(best_result["precision"], 4))
print("Recall:", round(best_result["recall"], 4))
print("F1:", round(best_result["f1"], 4))
print()
print("Confusion Matrix:")
print(best_result["confusion_matrix"])
print()
print(best_result["classification_report"])

Best run: focused_quiz_demo_med_screening_labs
Best params: {'model__C': 0.1, 'model__penalty': 'l1', 'model__solver': 'liblinear'}
ROC-AUC: 0.6704
Average Precision: 0.1531
Precision: 0.1414
Recall: 0.6985
F1: 0.2351

Confusion Matrix:
[[775 577]
 [ 41  95]]

              precision    recall  f1-score   support

           0       0.95      0.57      0.71      1352
           1       0.14      0.70      0.24       136

    accuracy                           0.58      1488
   macro avg       0.55      0.64      0.48      1488
weighted avg       0.88      0.58      0.67      1488

In [54]:
# %% Coefficients for selected model (readable version)
best_estimator = selected_result["best_estimator"]
preprocessor = best_estimator.named_steps["preprocessor"]
model = best_estimator.named_steps["model"]

feature_names = preprocessor.get_feature_names_out()

coef_df = pd.DataFrame({
    "transformed_feature": feature_names,
    "coefficient": model.coef_[0],
})
coef_df["abs_coefficient"] = coef_df["coefficient"].abs()
coef_df = coef_df.sort_values("abs_coefficient", ascending=False).reset_index(drop=True)

coef_df["pretty_feature"] = coef_df["transformed_feature"].apply(prettify_transformed_feature_name)

coef_df_pretty = coef_df[
    ["pretty_feature", "coefficient", "abs_coefficient", "transformed_feature"]
].copy()

coef_df_pretty.head(40)

,pretty_feature,coefficient,abs_coefficient,transformed_feature
0,Weight preference / perception: Would like to ...,-0.455172,0.455172,"cat__whq040___like_to_weigh_more,_less_or_same..."
1,Weight preference / perception: Would like to ...,0.441803,0.441803,"cat__whq040___like_to_weigh_more,_less_or_same..."
2,Close relative had diabetes: No,-0.435246,0.435246,cat__mcq300c___close_relative_had_diabetes_2.0
3,Age (years),0.383804,0.383804,num__age_years
4,How often do you snore?: Never,-0.308296,0.308296,cat__slq030___how_often_do_you_snore?_0.0
5,Gender: Male,-0.260220,0.260220,cat__gender_Male
6,Urine albumin-creatinine ratio (UACR),-0.172598,0.172598,num__uacr_mg_g
7,How often do you snore?: Often,0.162030,0.162030,cat__slq030___how_often_do_you_snore?_3.0
8,HDL cholesterol,-0.135955,0.135955,num__hdl_cholesterol_mg_dl
9,Total cholesterol,0.074276,0.074276,num__total_cholesterol_mg_dl
10,Total cholesterol missing,-0.047138,0.047138,num__missingindicator_total_cholesterol_mg_dl
11,How often do you snore?: Rarely,-0.025627,0.025627,cat__slq030___how_often_do_you_snore?_1.0
12,Urine albumin-creatinine ratio (UACR) missing,-0.025450,0.025450,num__missingindicator_uacr_mg_g
13,Triglycerides,0.020288,0.020288,num__triglycerides_mg_dl
14,HDL cholesterol missing,-0.011250,0.011250,num__missingindicator_hdl_cholesterol_mg_dl
15,Triglycerides missing,0.000000,0.000000,num__missingindicator_triglycerides_mg_dl
16,Medication count,0.000000,0.000000,num__med_count
17,Close relative had diabetes: Yes,0.000000,0.000000,cat__mcq300c___close_relative_had_diabetes_1.0
18,How often do you snore?: Sometimes,0.000000,0.000000,cat__slq030___how_often_do_you_snore?_2.0
19,Vigorous recreational activities: No,0.000000,0.000000,cat__paq650___vigorous_recreational_activities...
20,Vigorous recreational activities: Yes,0.000000,0.000000,cat__paq650___vigorous_recreational_activities...
21,Weight preference / perception: Would like to ...,0.000000,0.000000,"cat__whq040___like_to_weigh_more,_less_or_same..."
22,Gender: Female,0.000000,0.000000,cat__gender_Female

In [66]:
coef_path = OUTPUT_DIR / f"{selected_run}_coefficients_pretty.csv"
coef_df_pretty.to_csv(coef_path, index=False)
print("Saved:", coef_path.resolve())

Saved: C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes_rebuild\focused_quiz_demo_med_screening_labs_coefficients_pretty.csv

## 4) Threshold-Tuning für das beste Modell

Für eure App ist oft ein niedrigerer Threshold als 0.50 sinnvoll, wenn ihr eher **möglichst viele Verdachtsfälle finden** wollt.

In [67]:

threshold_rows = []
y_true = best_result["y_test_true"]
y_proba = best_result["y_test_proba"]

for thr in np.arange(0.10, 0.91, 0.05):
    metrics = evaluate_predictions(y_true, y_proba, threshold=float(thr))
    threshold_rows.append({
        "threshold": round(float(thr), 2),
        "precision": round(metrics["precision"], 4),
        "recall": round(metrics["recall"], 4),
        "f1": round(metrics["f1"], 4),
    })

threshold_df = pd.DataFrame(threshold_rows)
threshold_df

    threshold  precision  recall      f1
0        0.10     0.0919  1.0000  0.1683
1        0.15     0.0950  1.0000  0.1736
2        0.20     0.0967  0.9779  0.1759
3        0.25     0.1012  0.9559  0.1830
4        0.30     0.1051  0.9118  0.1884
5        0.35     0.1139  0.8971  0.2022
6        0.40     0.1242  0.8676  0.2173
7        0.45     0.1313  0.7868  0.2250
8        0.50     0.1414  0.6985  0.2351
9        0.55     0.1471  0.5441  0.2316
10       0.60     0.1628  0.4118  0.2333
11       0.65     0.1610  0.2426  0.1935
12       0.70     0.1845  0.1397  0.1590
13       0.75     0.2069  0.0441  0.0727
14       0.80     0.0000  0.0000  0.0000
15       0.85     0.0000  0.0000  0.0000
16       0.90     0.0000  0.0000  0.0000

In [68]:

threshold_path = OUTPUT_DIR / f"{best_run}_threshold_scan.csv"
threshold_df.to_csv(threshold_path, index=False)
print("Saved:", threshold_path.resolve())

Saved: C:\Users\Philipp\AIBootcamp\halfFull\data\processed\model_outputs_prediabetes_rebuild\focused_quiz_demo_med_screening_labs_threshold_scan.csv

## 5) Empfohlene Interpretation

- **broad_quiz_only** zeigt dir, wie gut dein Fragebogen allein ist.
- **broad_quiz_demo_med** zeigt, ob age/gender/med_count wirklich helfen.
- **focused_quiz_demo_med** ist dein kompaktes, produktnahes Setup.
- **focused_quiz_demo_med_screening_labs** zeigt Zusatznutzen von Check-up-nahen Labs ohne direkte Glukose-Leakage.
- **focused_quiz_demo_med_augmented_labs** ist eher ein klinisch stärkeres, aber potenziell leakage-nahes Benchmark-Modell.

Für das eigentliche Produkt würde ich in der Regel **das beste nicht-leakage-nahe Modell** wählen, nicht automatisch das numerisch beste Modell.

# Saving final model

In [ ]:
# %% Save selected model package as .joblib
import joblib
from pathlib import Path

selected_run = "focused_quiz_demo_med_screening_labs"
selected_result = all_results[selected_run]

model = selected_result["best_estimator"]
threshold = 0.45
feature_names = feature_sets[selected_run]

model_package = {
    "model": model,
    "threshold": threshold,
    "features": feature_names,
    "model_name": selected_run,
    "target": "prediabetes",
}

OUTPUT_DIR = Path("../models")
OUTPUT_DIR.mkdir(exist_ok=True)

disease = "prediabetes"
joblib_path = OUTPUT_DIR / f"{disease}_{selected_run}_threshold_045.joblib"
joblib.dump(model_package, joblib_path)

print("Joblib saved to:", joblib_path.resolve())
print("Stored feature count:", len(feature_names))
print("Stored features:", feature_names)

Joblib saved to: C:\Users\Philipp\AIBootcamp\halfFull\notebooks\models\prediabetes_focused_quiz_demo_med_screening_labs_threshold_045.joblib
Stored feature count: 11
Stored features: ['slq030___how_often_do_you_snore?', 'mcq300c___close_relative_had_diabetes', 'paq650___vigorous_recreational_activities', 'whq040___like_to_weigh_more,_less_or_same', 'age_years', 'gender', 'med_count', 'triglycerides_mg_dl', 'hdl_cholesterol_mg_dl', 'total_cholesterol_mg_dl', 'uacr_mg_g']

In [ ]:
# %% Save selected model metadata as .json
import json
from datetime import datetime, timezone
from pathlib import Path

selected_run = "focused_quiz_demo_med_screening_labs"
selected_result = all_results[selected_run]
feature_names = feature_sets[selected_run]

metadata = {
    "model_name": selected_run,
    "target": "prediabetes",
    "threshold": 0.45,
    "features": feature_names,
    "n_features": len(feature_names),
    "metrics": {
        "roc_auc": float(selected_result["roc_auc"]),
        "avg_precision": float(selected_result["avg_precision"]),
        "precision": float(selected_result["precision"]),
        "recall": float(selected_result["recall"]),
        "f1": float(selected_result["f1"]),
    },
    "best_params": selected_result["best_params"],
    "created_at": datetime.now(timezone.utc).isoformat(),
    "notes": "Compact prediabetes model using quiz, demographics, medication count, and screening labs. Selected threshold = 0.45 for screening-oriented use.",
}

OUTPUT_DIR = Path("../models")
OUTPUT_DIR.mkdir(exist_ok=True)

disease = "prediabetes"
metadata_path = OUTPUT_DIR / f"{disease}_{selected_run}_threshold_045.metadata.json"

with open(metadata_path, "w", encoding="utf-8") as f:
    json.dump(metadata, f, indent=2, ensure_ascii=False)

print("Metadata JSON saved to:", metadata_path.resolve())

Metadata JSON saved to: C:\Users\Philipp\AIBootcamp\halfFull\notebooks\models\prediabetes_focused_quiz_demo_med_screening_labs_threshold_045.metadata.json

In [74]:
# %% Load saved model package and metadata
import joblib
import json

loaded_package = joblib.load(joblib_path)

with open(metadata_path, "r", encoding="utf-8") as f:
    loaded_metadata = json.load(f)

print("Loaded package keys:", loaded_package.keys())
print("Loaded threshold:", loaded_package["threshold"])
print("Loaded model name:", loaded_package["model_name"])
print("Loaded feature count:", len(loaded_package["features"]))

print("\nLoaded metadata:")
print(loaded_metadata["model_name"])
print(loaded_metadata["threshold"])
print(loaded_metadata["n_features"])

Loaded package keys: dict_keys(['model', 'threshold', 'features', 'model_name', 'target'])
Loaded threshold: 0.45
Loaded model name: focused_quiz_demo_med_screening_labs
Loaded feature count: 11

Loaded metadata:
focused_quiz_demo_med_screening_labs
0.45
11

---
## RETRAIN v2 — Normalized Data Pipeline

### Change log vs v1

| # | Change | v1 | v2 |
|---|--------|----|----|
| 1 | Data source | `nhanes_merged_adults_final.csv` (raw) | `nhanes_merged_adults_final_normalized.csv` (z-scored) |
| 2 | Scaling | `StandardScaler` in ColumnTransformer | Removed — data pre-normalized |
| 3 | Missingness | `SimpleImputer` no indicator | `SimpleImputer(median, add_indicator=True)` |
| 4 | Gender | Raw string `gender` column | `gender_female` binary (1=Female, 0=Male) |
| 5 | Evaluation | Single 80/20 split | 5-fold Stratified CV (OOF predictions) |
| 6 | Output format | Dict `{model, threshold, features}` | Plain `.joblib` pipeline |
| 7 | Threshold | Per-model 0.45 in dict | Global 0.35 via model_runner |
| 8 | Feature set | 11 hand-picked features | All 76 roadmap features → L1 selection → deduplication |
| 9 | Regularization | C not tuned (grid search) | C=0.01 (stronger, better calibrated for 9.2% prevalence) |

### Leakage removed

| Column | Reason |
|--------|--------|
| `diq160___ever_told_you_have_prediabetes` | **IS the target** (corr=-0.733) |
| `diq070___take_diabetic_pills_to_lower_blood_sugar` | corr=+0.538 — only asked to diabetics; non-NaN = confirmed diabetes |
| `diq010___doctor_told_you_have_diabetes` | Adjacent diagnosis — all prediabetes=1 have diq010=2 |
| `diq050___taking_insulin_now` | Insulin = diabetes treatment |
| `did040` … `did350` (all did_* columns) | Diabetes management follow-ups — NaN for all non-diabetics |
| `diq275`, `diq280`, `diq291`, etc. | Diabetes monitoring questions — only asked after diabetes confirmation |
| `diabetes` | Mutually exclusive derived column — all prediabetes=1 have diabetes=0 |

### Missing derived features from v1
- `cos_weekday_bedtime` — not present in normalized file (derived from raw NHANES times)
- `sleep_hours_weekend` — replaced by `sld013___sleep_hours___weekends`

### Regularization decision: C=0.01
Stronger regularization was chosen over C=1.0 because:
1. AUC **improves** (+0.003): 0.7083 → 0.7115 (better calibrated for 9.2% prevalence)
2. `mcq366d` coefficient shrinks: -0.760 → -0.607 (20% reduction)
3. `pregnancy_status_bin` coefficient shrinks: +0.832 → +0.147 (massive — was severely overfit at C=1.0)
4. All other coefficients also shrink proportionally — less variance in production

In [1]:
# ── v2 Setup ─────────────────────────────────────────────────────────────
import os, warnings, json as _json, joblib
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (roc_auc_score, average_precision_score, recall_score,
                             precision_score, f1_score, confusion_matrix)

warnings.filterwarnings('ignore')

DATA_V2       = '../data/processed/nhanes_merged_adults_final_normalized.csv'
MODEL_OUT_DIR = '../models_normalized'
TARGET_COL    = 'prediabetes'
RANDOM_STATE  = 42
CV_FOLDS      = 5
THRESHOLD     = 0.35
BEST_C        = 0.01   # chosen: reduces coefficient extremes AND improves AUC

os.makedirs(MODEL_OUT_DIR, exist_ok=True)

df = pd.read_csv(DATA_V2, low_memory=False)
df['gender_female']       = (df['gender'] == 'Female').astype(float)
df['education_ord']       = df['education'].map({'Less than 9th grade':1,'9-11th grade':2,
    'High school diploma/GED':3,'Some college / AA':4,'College graduate or above':5})
df['pregnancy_status_bin'] = df['pregnancy_status'].map({'Yes, pregnant':1.0,'Not pregnant':0.0})

print(f"Dataset: {df.shape[0]:,} rows")
print(df[TARGET_COL].value_counts(dropna=False))
print(f"Prevalence: {df[TARGET_COL].mean():.1%}")

Dataset: 7,437 rows
prediabetes
0    6755
1     682
Name: count, dtype: int64
Prevalence: 9.2%

In [2]:
# ── v2 Feature list (deduped-34, L1-selected from 76 roadmap features) ──
# Leakage removed: diq160 (target), diq070 (corr=+0.538), all diq/did diabetes-management columns
# Duplicates removed: bmi/weight_kg (r=0.91), triglycerides (r=-0.47 with hdl), sld013 (r=0.45 with sld012)
# cos_weekday_bedtime: not in normalized file
# sleep_hours_weekend: replaced by sld012___sleep_hours___weekdays_or_workdays

FEATURES_V2 = [
    # Metabolic / diet counseling  (top signal)
    'mcq366d___doctor_told_to_reduce_fat_in_diet',          # coef -0.607 | diet mgmt proxy
    'LBDLDL_ldl_cholesterol_friedewald_mg_dl',             # coef +0.257 | LDL lab
    'hdl_cholesterol_mg_dl',                               # coef -0.167 | HDL (inverse metabolic)
    'fasting_glucose_mg_dl',                               # coef -0.110 | glucose lab
    # Reproductive
    'pregnancy_status_bin',                                # coef +0.147 | gestational diabetes risk
    # Cardiovascular / hypertension
    'bpq050a___now_taking_prescribed_medicine_for_hbp',    # coef +0.159 | BP treatment
    'bpq080___doctor_told_you___high_cholesterol_level',   # coef -0.217 | lipid diagnosis
    'bpq020___ever_told_you_had_high_blood_pressure',      # coef -0.131 | hypertension
    'bpq030___told_had_high_blood_pressure___2+_times',    # coef -0.098 | persistent htn
    'mcq160b___ever_told_you_had_congestive_heart_failure',# coef +0.068 | CV comorbidity
    # Lifestyle / activity
    'smd650___avg_#_cigarettes/day_during_past_30_days',   # coef -0.227 | smoking intensity
    'paq665___moderate_recreational_activities',           # coef -0.158 | physical activity
    'paq650___vigorous_recreational_activities',           # coef +0.120 | vigorous activity
    'paq620___moderate_work_activity',                     # coef -0.092 | work activity
    'alq130___avg_#_alcoholic_drinks/day___past_12_mos',   # coef -0.102 | alcohol intake
    # Weight management
    'whq070___tried_to_lose_weight_in_past_year',          # coef -0.240 | active weight mgmt
    'whq040___like_to_weigh_more,_less_or_same',           # coef +0.061 | weight perception
    # Comorbidities
    'mcq010___ever_been_told_you_have_asthma',             # coef +0.163 | respiratory
    'mcq053___taking_treatment_for_anemia/past_3_mos',     # coef -0.155 | anemia treatment
    'mcq520___abdominal_pain_during_past_12_months?',      # coef -0.144 | GI symptom
    'cdq010___shortness_of_breath_on_stairs/inclines',     # coef -0.101 | dyspnea
    'mcq195___which_type_of_arthritis_was_it?',            # coef +0.046 | arthritis type
    # Sleep / fatigue
    'slq050___ever_told_doctor_had_trouble_sleeping?',     # coef -0.238 | health-seeking
    'sld012___sleep_hours___weekdays_or_workdays',         # coef -0.064 | sleep duration
    'dpq040___feeling_tired_or_having_little_energy',      # coef +0.063 | fatigue
    # SES / health access
    'huq010___general_health_condition',                   # coef +0.136 | self-rated health
    'huq071___overnight_hospital_patient_in_last_year',    # coef +0.037 | acute care
    'education_ord',                                       # coef +0.122 | SES
    # Kidney
    'kiq052___how_much_were_daily_activities_affected?',   # coef -0.111 | functional impact
    'kiq022___ever_told_you_had_weak/failing_kidneys?',    # coef +0.042 | kidney disease
    # Demographics + medications (always include)
    'mcq300c___close_relative_had_diabetes',               # coef -0.087 | family history
    'gender_female',                                       # coef +0.122
    'med_count',                                           # coef -0.030
    'age_years',                                           # coef +0.010
]

print(f"v2 features: {len(FEATURES_V2)}")
missing = [f for f in FEATURES_V2 if f not in df.columns]
print(f"Missing from normalized file: {missing or 'none'}")

v2 features: 34
Missing from normalized file: none

In [3]:
# ── v2 CV + OOF metrics ──────────────────────────────────────────────────
def build_pipe(C=BEST_C):
    return Pipeline([
        ('imp', SimpleImputer(strategy='median', add_indicator=True)),
        ('clf', LogisticRegression(penalty='l2', C=C, class_weight='balanced',
            max_iter=2000, solver='lbfgs', random_state=RANDOM_STATE)),
    ])

df_m = df[FEATURES_V2 + [TARGET_COL]].dropna(subset=[TARGET_COL])
X = df_m[FEATURES_V2]
y = df_m[TARGET_COL].values.astype(int)
cv = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=RANDOM_STATE)

y_oof = np.zeros(len(y))
prob_oof = np.zeros(len(y))
for tr, te in cv.split(X, y):
    p = build_pipe()
    p.fit(X.iloc[tr], y[tr])
    prob_oof[te] = p.predict_proba(X.iloc[te])[:, 1]
    y_oof[te] = y[te]

print("═"*60)
print("v2 OOF Metrics (5-fold, C=0.01, deduped-34 features)")
print("═"*60)
print(f"  AUC:           {roc_auc_score(y_oof, prob_oof):.4f}  (v1-equiv: 0.6336)")
print(f"  Avg Precision: {average_precision_score(y_oof, prob_oof):.4f}  (v1-equiv: 0.1379)")
print(f"  Prevalence:    {y_oof.mean():.1%}  ({int(y_oof.sum())} positive / {len(y_oof)} total)")

pred_default = (prob_oof >= THRESHOLD).astype(int)
tn, fp, fn, tp = confusion_matrix(y_oof, pred_default).ravel()
print(f"\n  @ threshold={THRESHOLD}:")
print(f"    Precision:  {precision_score(y_oof, pred_default, zero_division=0):.3f}")
print(f"    Recall:     {recall_score(y_oof, pred_default, zero_division=0):.3f}")
print(f"    F1:         {f1_score(y_oof, pred_default, zero_division=0):.3f}")
print(f"    Flagged:    {pred_default.sum():,} / {len(pred_default):,}  ({pred_default.mean()*100:.1f}%)")
print(f"    TP={int(tp)}  FP={int(fp)}  FN={int(fn)}  TN={int(tn)}")

════════════════════════════════════════════════════════════
v2 OOF Metrics (5-fold, C=0.01, deduped-34 features)
════════════════════════════════════════════════════════════
  AUC:           0.7115  (v1-equiv: 0.6336)
  Avg Precision: 0.1797  (v1-equiv: 0.1379)
  Prevalence:    9.2%  (682 positive / 7437 total)

  @ threshold=0.35:
    Precision:  0.127
    Recall:     0.886
    F1:         0.222
    Flagged:    4,764 / 7,437  (64.1%)
    TP=604  FP=4160  FN=78  TN=2595

In [4]:
# ── Threshold sweep ──────────────────────────────────────────────────────
print("\n── Threshold sweep (OOF predictions, C=0.01, deduped-34) ───────────")
print(f"\n  {'Threshold':>9}  {'Precision':>9}  {'Recall':>6}  {'F1':>6}  "
      f"{'Flagged%':>8}  {'TP':>4}  {'FP':>4}  {'FN':>4}")
print("  "+"-"*70)

for thr in [0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60]:
    pred = (prob_oof >= thr).astype(int)
    tn_, fp_, fn_, tp_ = confusion_matrix(y_oof, pred).ravel()
    marker = " ← global default" if thr == 0.35 else (" ← peak F1" if thr == 0.55 else "")
    print(f"  {thr:>9.2f}  "
          f"{precision_score(y_oof, pred, zero_division=0):>9.3f}  "
          f"{recall_score(y_oof, pred, zero_division=0):>6.3f}  "
          f"{f1_score(y_oof, pred, zero_division=0):>6.3f}  "
          f"{pred.mean()*100:>7.1f}%  "
          f"{int(tp_):>4d}  {int(fp_):>4d}  {int(fn_):>4d}{marker}")

print("\nNote: Prediabetes prevalence is 9.2%. High false-positive rate at low thresholds")
print("is expected with class_weight='balanced' — model is optimised for recall.")

── Threshold sweep (OOF predictions, C=0.01, deduped-34) ───────────

  Threshold  Precision  Recall      F1  Flagged%    TP    FP    FN
  ----------------------------------------------------------------------
       0.25      0.105   0.969   0.190     84.4%   661  5616    21
       0.30      0.115   0.937   0.205     74.5%   639  4904    43
       0.35      0.127   0.886   0.222     64.1%   604  4160    78 ← global default
       0.40      0.138   0.814   0.236     54.2%   555  3475   127
       0.45      0.151   0.739   0.251     44.8%   504  2825   178
       0.50      0.164   0.648   0.261     36.3%   442  2258   240
       0.55      0.178   0.545   0.268     28.1%   372  1717   310 ← peak F1
       0.60      0.190   0.447   0.267     21.6%   305  1301   377

Note: Prediabetes prevalence is 9.2%. High false-positive rate at low thresholds
is expected with class_weight='balanced' — model is optimised for recall.

In [5]:
# ── Coefficient table: C=0.01 vs removed feature impact ─────────────────
pipe_final = build_pipe(BEST_C)
pipe_final.fit(X, y)
imp_s = pipe_final.named_steps['imp']
clf_s = pipe_final.named_steps['clf']
all_names = list(FEATURES_V2) + [f'miss__{FEATURES_V2[i]}' for i in imp_s.indicator_.features_]
coef_map = dict(zip(all_names, clf_s.coef_[0]))

base_coefs = [(f, coef_map[f]) for f in FEATURES_V2]
base_coefs_sorted = sorted(base_coefs, key=lambda x: abs(x[1]), reverse=True)

print(f"\n  {'Feature':55s}  {'Coef (C=0.01)':>13}")
print("  "+"-"*72)
for name, c in base_coefs_sorted:
    note = " ← note: counterintuitive sign" if name in {
        'mcq366d___doctor_told_to_reduce_fat_in_diet',
        'bpq080___doctor_told_you___high_cholesterol_level',
        'mcq300c___close_relative_had_diabetes',
        'fasting_glucose_mg_dl',
    } else ""
    print(f"  {name:55s}  {c:>+13.4f}{note}")

  Feature                                                  Coef (C=0.01)
  ------------------------------------------------------------------------
  mcq366d___doctor_told_to_reduce_fat_in_diet                    -0.6077 ← note: counterintuitive sign
  LBDLDL_ldl_cholesterol_friedewald_mg_dl                        +0.2576
  whq070___tried_to_lose_weight_in_past_year                     -0.2403
  slq050___ever_told_doctor_had_trouble_sleeping?                -0.2380
  smd650___avg_#_cigarettes/day_during_past_30_days              -0.2269
  bpq080___doctor_told_you___high_cholesterol_level              -0.2173 ← note: counterintuitive sign
  hdl_cholesterol_mg_dl                                          -0.1667
  mcq010___ever_been_told_you_have_asthma                        +0.1629
  bpq050a___now_taking_prescribed_medicine_for_hbp               +0.1586
  paq665___moderate_recreational_activities                      -0.1578
  mcq053___taking_treatment_for_anemia/past_3_mos                -0.1549
  pregnancy_status_bin                                           +0.1475
  mcq520___abdominal_pain_during_past_12_months?                 -0.1437
  huq010___general_health_condition                              +0.1361
  bpq020___ever_told_you_had_high_blood_pressure                 -0.1317
  gender_female                                                  +0.1222
  education_ord                                                  +0.1213
  paq650___vigorous_recreational_activities                      +0.1197
  kiq052___how_much_were_daily_activities_affected?              -0.1116
  fasting_glucose_mg_dl                                          -0.1108 ← note: counterintuitive sign
  alq130___avg_#_alcoholic_drinks/day___past_12_mos              -0.1025
  cdq010___shortness_of_breath_on_stairs/inclines                -0.1015
  bpq030___told_had_high_blood_pressure___2+_times               -0.0978
  paq620___moderate_work_activity                                -0.0914
  mcq300c___close_relative_had_diabetes                          -0.0871 ← note: counterintuitive sign
  mcq160b___ever_told_you_had_congestive_heart_failure           +0.0670
  sld012___sleep_hours___weekdays_or_workdays                    -0.0642
  dpq040___feeling_tired_or_having_little_energy                 +0.0631
  whq040___like_to_weigh_more,_less_or_same                      +0.0609
  mcq195___which_type_of_arthritis_was_it?                       +0.0458
  kiq022___ever_told_you_had_weak/failing_kidneys?               +0.0419
  huq071___overnight_hospital_patient_in_last_year               +0.0362
  med_count                                                      -0.0302
  age_years                                                      +0.0101

In [6]:
# ── Save final model ─────────────────────────────────────────────────────
import json as _json
from datetime import datetime

fname     = 'prediabetes_lr_deduped34_L2_C001_v2.joblib'
mfname    = fname.replace('.joblib', '_metadata.json')

joblib.dump(pipe_final, os.path.join(MODEL_OUT_DIR, fname))

metadata = {
    'model': fname, 'version': 'v2', 'condition': 'prediabetes',
    'algorithm': f'LogisticRegression L2 C={BEST_C}',
    'data_source': 'nhanes_merged_adults_final_normalized.csv',
    'n_train': len(df_m), 'prevalence': round(float(df_m[TARGET_COL].mean()), 4),
    'features': FEATURES_V2, 'n_features': len(FEATURES_V2),
    'cv_folds': CV_FOLDS,
    'cv_auc_mean': round(float(roc_auc_score(y_oof, prob_oof)), 4),
    'cv_auc_std': round(float(np.std([
        roc_auc_score(y[te], prob_oof[te])
        for _, te in StratifiedKFold(CV_FOLDS, shuffle=True,
                                     random_state=RANDOM_STATE).split(X, y)
    ])), 4),
    'cv_avg_precision': round(float(average_precision_score(y_oof, prob_oof)), 4),
    'threshold': THRESHOLD,
    'regularization_note': (
        'C=0.01 chosen over C=1.0: reduces mcq366d coef -0.760→-0.607 (20%) '
        'and pregnancy_status_bin coef +0.832→+0.147, while AUC improves +0.003.'
    ),
    'pipeline_steps': [
        'SimpleImputer(strategy=median, add_indicator=True)',
        f'LogisticRegression(L2, class_weight=balanced, C={BEST_C})'
    ],
    'leakage_removed': [
        'diq160 (target itself)',
        'diq070 (corr=+0.538 — diabetes management)',
        'diq010 (adjacent diabetes diagnosis)',
        'diq050 (insulin = diabetes treatment)',
        'diabetes (mutually exclusive derived column)',
        'all did_* / diq_* diabetes monitoring columns',
    ],
    'changes_from_v1': [
        'Pre-normalized z-scored data',
        'No StandardScaler',
        'SimpleImputer add_indicator=True',
        'gender_female binary encoding',
        '5-fold stratified CV (OOF)',
        'No dict wrapping',
        'Global threshold 0.35',
        'C=0.01 (stronger regularization)',
        'All roadmap features tried; L1 selection + deduplication',
        'cos_weekday_bedtime removed (not in normalized file)',
    ],
    'created_at': datetime.utcnow().isoformat() + 'Z',
}

with open(os.path.join(MODEL_OUT_DIR, mfname), 'w') as f:
    _json.dump(metadata, f, indent=2)

print(f"Saved: {MODEL_OUT_DIR}/{fname}")
print(f"Saved: {MODEL_OUT_DIR}/{mfname}")
print(f'\nmodel_runner registry: "prediabetes" -> "{fname}"')
print(f'\nSummary:')
print(f'  AUC:     {metadata["cv_auc_mean"]:.4f}  (v1-equiv was 0.6336, +{metadata["cv_auc_mean"]-0.6336:.4f})')
print(f'  AvgPrec: {metadata["cv_avg_precision"]:.4f}  (v1-equiv was 0.1379)')
print(f'  Features: {len(FEATURES_V2)} (v1 was 11)')

Saved: ../models_normalized/prediabetes_lr_deduped34_L2_C001_v2.joblib
Saved: ../models_normalized/prediabetes_lr_deduped34_L2_C001_v2_metadata.json

model_runner registry: "prediabetes" -> "prediabetes_lr_deduped34_L2_C001_v2.joblib"

Summary:
  AUC:     0.7115  (v1-equiv was 0.6336, +0.0779)
  AvgPrec: 0.1797  (v1-equiv was 0.1379)
  Features: 34 (v1 was 11)

## RF+cal Comparison — Decision: Keep LR

**Date tested:** 2026-03-24

Tested `RandomForestClassifier(n_estimators=300, max_depth=6, min_samples_leaf=10, class_weight='balanced') + CalibratedClassifierCV(method='isotonic', cv=3)` against the current LR-L2 model across three L1 feature-selection strengths (C=0.10, 0.03, 0.01).

| Model | Feats | AUC | AUPRC | Best operating point |
|---|---|---|---|---|
| **LR-L2 C=0.01 (current)** | 34 | **0.7099** | **0.1833** | t=0.53: prec=17.5%, recall=55.7%, flags=29.3% |
| RF+cal C=0.10 | 54 | 0.7269 | 0.1783 | t=0.15: prec=18.5%, recall=48.4%, flags=24.0% |
| RF+cal C=0.03 | 32 | 0.7302 | 0.1832 | t=0.15: prec=18.9%, recall=45.0%, flags=26.5% |
| RF+cal C=0.01 | 17 | 0.7214 | 0.1697 | t=0.15: prec=18.2%, recall=51.9%, flags=26.1% |

**Key finding:** All RF+cal variants collapse above t=0.20–0.25 (recall drops to ≤17%), making them unusable at any threshold above the pipeline gate (0.35). The marginal AUC gain (+0.02 for best RF) does not compensate for losing the entire operating range.

**Decision:** Keep LR-L2 (34 feats, C=0.01). Model file: `prediabetes_lr_deduped34_L2_C001_v2.joblib`

This follows the same pattern as electrolyte_imbalance, thyroid, and kidney — moderate-prevalence diseases (~27% prediabetes here) where RF recall collapses while LR maintains useful recall at higher thresholds.